// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layernorm_top_layernorm_64ul_float_float_2ul_s (
        src_TDATA,
        dst_TDATA,
        ap_clk,
        ap_rst,
        src_TVALID,
        src_TREADY,
        ap_start,
        dst_TVALID,
        dst_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [63:0] src_TDATA;
output  [63:0] dst_TDATA;
input   ap_clk;
input   ap_rst;
input   src_TVALID;
output   src_TREADY;
input   ap_start;
output   dst_TVALID;
input   dst_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    mean_stage_64ul_float_float_2ul_U0_ap_start;
wire    mean_stage_64ul_float_float_2ul_U0_ap_done;
wire    mean_stage_64ul_float_float_2ul_U0_ap_continue;
wire    mean_stage_64ul_float_float_2ul_U0_ap_idle;
wire    mean_stage_64ul_float_float_2ul_U0_ap_ready;
wire   [63:0] mean_stage_64ul_float_float_2ul_U0_stage1_s_din;
wire    mean_stage_64ul_float_float_2ul_U0_stage1_s_write;
wire   [31:0] mean_stage_64ul_float_float_2ul_U0_mean_s_din;
wire    mean_stage_64ul_float_float_2ul_U0_mean_s_write;
wire    mean_stage_64ul_float_float_2ul_U0_src_TREADY;
wire    var_stage_64ul_float_float_float_2ul_U0_ap_start;
wire    var_stage_64ul_float_float_float_2ul_U0_ap_done;
wire    var_stage_64ul_float_float_float_2ul_U0_ap_continue;
wire    var_stage_64ul_float_float_float_2ul_U0_ap_idle;
wire    var_stage_64ul_float_float_float_2ul_U0_ap_ready;
wire   [63:0] var_stage_64ul_float_float_float_2ul_U0_stage2_s_din;
wire    var_stage_64ul_float_float_float_2ul_U0_stage2_s_write;
wire   [31:0] var_stage_64ul_float_float_float_2ul_U0_var_s_din;
wire    var_stage_64ul_float_float_float_2ul_U0_var_s_write;
wire    var_stage_64ul_float_float_float_2ul_U0_mean_s_read;
wire    var_stage_64ul_float_float_float_2ul_U0_stage1_s_read;
reg    ap_sync_reg_var_stage_64ul_float_float_float_2ul_U0_ap_start;
wire    inv_sqrt_stage_64ul_float_2ul_U0_ap_start;
wire    inv_sqrt_stage_64ul_float_2ul_U0_ap_done;
wire    inv_sqrt_stage_64ul_float_2ul_U0_ap_continue;
wire    inv_sqrt_stage_64ul_float_2ul_U0_ap_idle;
wire    inv_sqrt_stage_64ul_float_2ul_U0_ap_ready;
wire    inv_sqrt_stage_64ul_float_2ul_U0_var_s_read;
wire    inv_sqrt_stage_64ul_float_2ul_U0_stage2_s_read;
wire   [63:0] inv_sqrt_stage_64ul_float_2ul_U0_dst_TDATA;
wire    inv_sqrt_stage_64ul_float_2ul_U0_dst_TVALID;
reg    ap_sync_reg_inv_sqrt_stage_64ul_float_2ul_U0_ap_start;
wire    stage1_s_full_n;
wire   [63:0] stage1_s_dout;
wire   [5:0] stage1_s_num_data_valid;
wire   [5:0] stage1_s_fifo_cap;
wire    stage1_s_empty_n;
wire    mean_s_full_n;
wire   [31:0] mean_s_dout;
wire   [1:0] mean_s_num_data_valid;
wire   [1:0] mean_s_fifo_cap;
wire    mean_s_empty_n;
wire    stage2_s_full_n;
wire   [63:0] stage2_s_dout;
wire   [5:0] stage2_s_num_data_valid;
wire   [5:0] stage2_s_fifo_cap;
wire    stage2_s_empty_n;
wire    var_s_full_n;
wire   [31:0] var_s_dout;
wire   [1:0] var_s_num_data_valid;
wire   [1:0] var_s_fifo_cap;
wire    var_s_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_var_stage_64ul_float_float_float_2ul_U0_ap_start = 1'b0;
#0 ap_sync_reg_inv_sqrt_stage_64ul_float_2ul_U0_ap_start = 1'b0;
end

layernorm_top_mean_stage_64ul_float_float_2ul_s mean_stage_64ul_float_float_2ul_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(mean_stage_64ul_float_float_2ul_U0_ap_start),
    .ap_done(mean_stage_64ul_float_float_2ul_U0_ap_done),
    .ap_continue(mean_stage_64ul_float_float_2ul_U0_ap_continue),
    .ap_idle(mean_stage_64ul_float_float_2ul_U0_ap_idle),
    .ap_ready(mean_stage_64ul_float_float_2ul_U0_ap_ready),
    .src_TVALID(src_TVALID),
    .stage1_s_din(mean_stage_64ul_float_float_2ul_U0_stage1_s_din),
    .stage1_s_num_data_valid(stage1_s_num_data_valid),
    .stage1_s_fifo_cap(stage1_s_fifo_cap),
    .stage1_s_full_n(stage1_s_full_n),
    .stage1_s_write(mean_stage_64ul_float_float_2ul_U0_stage1_s_write),
    .mean_s_din(mean_stage_64ul_float_float_2ul_U0_mean_s_din),
    .mean_s_num_data_valid(mean_s_num_data_valid),
    .mean_s_fifo_cap(mean_s_fifo_cap),
    .mean_s_full_n(mean_s_full_n),
    .mean_s_write(mean_stage_64ul_float_float_2ul_U0_mean_s_write),
    .src_TDATA(src_TDATA),
    .src_TREADY(mean_stage_64ul_float_float_2ul_U0_src_TREADY)
);

layernorm_top_var_stage_64ul_float_float_float_2ul_s var_stage_64ul_float_float_float_2ul_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(var_stage_64ul_float_float_float_2ul_U0_ap_start),
    .ap_done(var_stage_64ul_float_float_float_2ul_U0_ap_done),
    .ap_continue(var_stage_64ul_float_float_float_2ul_U0_ap_continue),
    .ap_idle(var_stage_64ul_float_float_float_2ul_U0_ap_idle),
    .ap_ready(var_stage_64ul_float_float_float_2ul_U0_ap_ready),
    .stage2_s_din(var_stage_64ul_float_float_float_2ul_U0_stage2_s_din),
    .stage2_s_num_data_valid(stage2_s_num_data_valid),
    .stage2_s_fifo_cap(stage2_s_fifo_cap),
    .stage2_s_full_n(stage2_s_full_n),
    .stage2_s_write(var_stage_64ul_float_float_float_2ul_U0_stage2_s_write),
    .var_s_din(var_stage_64ul_float_float_float_2ul_U0_var_s_din),
    .var_s_num_data_valid(var_s_num_data_valid),
    .var_s_fifo_cap(var_s_fifo_cap),
    .var_s_full_n(var_s_full_n),
    .var_s_write(var_stage_64ul_float_float_float_2ul_U0_var_s_write),
    .mean_s_dout(mean_s_dout),
    .mean_s_num_data_valid(mean_s_num_data_valid),
    .mean_s_fifo_cap(mean_s_fifo_cap),
    .mean_s_empty_n(mean_s_empty_n),
    .mean_s_read(var_stage_64ul_float_float_float_2ul_U0_mean_s_read),
    .stage1_s_dout(stage1_s_dout),
    .stage1_s_num_data_valid(stage1_s_num_data_valid),
    .stage1_s_fifo_cap(stage1_s_fifo_cap),
    .stage1_s_empty_n(stage1_s_empty_n),
    .stage1_s_read(var_stage_64ul_float_float_float_2ul_U0_stage1_s_read)
);

layernorm_top_inv_sqrt_stage_64ul_float_2ul_s inv_sqrt_stage_64ul_float_2ul_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(inv_sqrt_stage_64ul_float_2ul_U0_ap_start),
    .ap_done(inv_sqrt_stage_64ul_float_2ul_U0_ap_done),
    .ap_continue(inv_sqrt_stage_64ul_float_2ul_U0_ap_continue),
    .ap_idle(inv_sqrt_stage_64ul_float_2ul_U0_ap_idle),
    .ap_ready(inv_sqrt_stage_64ul_float_2ul_U0_ap_ready),
    .var_s_dout(var_s_dout),
    .var_s_num_data_valid(var_s_num_data_valid),
    .var_s_fifo_cap(var_s_fifo_cap),
    .var_s_empty_n(var_s_empty_n),
    .var_s_read(inv_sqrt_stage_64ul_float_2ul_U0_var_s_read),
    .stage2_s_dout(stage2_s_dout),
    .stage2_s_num_data_valid(stage2_s_num_data_valid),
    .stage2_s_fifo_cap(stage2_s_fifo_cap),
    .stage2_s_empty_n(stage2_s_empty_n),
    .stage2_s_read(inv_sqrt_stage_64ul_float_2ul_U0_stage2_s_read),
    .dst_TREADY(dst_TREADY),
    .dst_TDATA(inv_sqrt_stage_64ul_float_2ul_U0_dst_TDATA),
    .dst_TVALID(inv_sqrt_stage_64ul_float_2ul_U0_dst_TVALID)
);

layernorm_top_fifo_w64_d32_A stage1_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mean_stage_64ul_float_float_2ul_U0_stage1_s_din),
    .if_full_n(stage1_s_full_n),
    .if_write(mean_stage_64ul_float_float_2ul_U0_stage1_s_write),
    .if_dout(stage1_s_dout),
    .if_num_data_valid(stage1_s_num_data_valid),
    .if_fifo_cap(stage1_s_fifo_cap),
    .if_empty_n(stage1_s_empty_n),
    .if_read(var_stage_64ul_float_float_float_2ul_U0_stage1_s_read)
);

layernorm_top_fifo_w32_d2_S mean_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(mean_stage_64ul_float_float_2ul_U0_mean_s_din),
    .if_full_n(mean_s_full_n),
    .if_write(mean_stage_64ul_float_float_2ul_U0_mean_s_write),
    .if_dout(mean_s_dout),
    .if_num_data_valid(mean_s_num_data_valid),
    .if_fifo_cap(mean_s_fifo_cap),
    .if_empty_n(mean_s_empty_n),
    .if_read(var_stage_64ul_float_float_float_2ul_U0_mean_s_read)
);

layernorm_top_fifo_w64_d32_A stage2_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(var_stage_64ul_float_float_float_2ul_U0_stage2_s_din),
    .if_full_n(stage2_s_full_n),
    .if_write(var_stage_64ul_float_float_float_2ul_U0_stage2_s_write),
    .if_dout(stage2_s_dout),
    .if_num_data_valid(stage2_s_num_data_valid),
    .if_fifo_cap(stage2_s_fifo_cap),
    .if_empty_n(stage2_s_empty_n),
    .if_read(inv_sqrt_stage_64ul_float_2ul_U0_stage2_s_read)
);

layernorm_top_fifo_w32_d2_S var_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(var_stage_64ul_float_float_float_2ul_U0_var_s_din),
    .if_full_n(var_s_full_n),
    .if_write(var_stage_64ul_float_float_float_2ul_U0_var_s_write),
    .if_dout(var_s_dout),
    .if_num_data_valid(var_s_num_data_valid),
    .if_fifo_cap(var_s_fifo_cap),
    .if_empty_n(var_s_empty_n),
    .if_read(inv_sqrt_stage_64ul_float_2ul_U0_var_s_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_inv_sqrt_stage_64ul_float_2ul_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_inv_sqrt_stage_64ul_float_2ul_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_var_stage_64ul_float_float_float_2ul_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_var_stage_64ul_float_float_float_2ul_U0_ap_start <= 1'b1;
        end
    end
end

assign ap_done = inv_sqrt_stage_64ul_float_2ul_U0_ap_done;

assign ap_idle = (var_stage_64ul_float_float_float_2ul_U0_ap_idle & mean_stage_64ul_float_float_2ul_U0_ap_idle & inv_sqrt_stage_64ul_float_2ul_U0_ap_idle);

assign ap_ready = mean_stage_64ul_float_float_2ul_U0_ap_ready;

assign dst_TDATA = inv_sqrt_stage_64ul_float_2ul_U0_dst_TDATA;

assign dst_TVALID = inv_sqrt_stage_64ul_float_2ul_U0_dst_TVALID;

assign inv_sqrt_stage_64ul_float_2ul_U0_ap_continue = ap_continue;

assign inv_sqrt_stage_64ul_float_2ul_U0_ap_start = (ap_sync_reg_inv_sqrt_stage_64ul_float_2ul_U0_ap_start | ap_start);

assign mean_stage_64ul_float_float_2ul_U0_ap_continue = 1'b1;

assign mean_stage_64ul_float_float_2ul_U0_ap_start = ap_start;

assign src_TREADY = mean_stage_64ul_float_float_2ul_U0_src_TREADY;

assign var_stage_64ul_float_float_float_2ul_U0_ap_continue = 1'b1;

assign var_stage_64ul_float_float_float_2ul_U0_ap_start = (ap_sync_reg_var_stage_64ul_float_float_float_2ul_U0_ap_start | ap_start);

endmodule //layernorm_top_layernorm_64ul_float_float_2ul_s
