// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layernorm_top_mean_stage_64ul_float_float_2ul_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_TVALID,
        stage1_s_din,
        stage1_s_num_data_valid,
        stage1_s_fifo_cap,
        stage1_s_full_n,
        stage1_s_write,
        mean_s_din,
        mean_s_num_data_valid,
        mean_s_fifo_cap,
        mean_s_full_n,
        mean_s_write,
        src_TDATA,
        src_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   src_TVALID;
output  [63:0] stage1_s_din;
input  [5:0] stage1_s_num_data_valid;
input  [5:0] stage1_s_fifo_cap;
input   stage1_s_full_n;
output   stage1_s_write;
output  [31:0] mean_s_din;
input  [1:0] mean_s_num_data_valid;
input  [1:0] mean_s_fifo_cap;
input   mean_s_full_n;
output   mean_s_write;
input  [63:0] src_TDATA;
output   src_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stage1_s_write;
reg mean_s_write;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
wire   [0:0] tmp_i_nbreadreq_fu_62_p3;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] tmp_i_reg_201;
reg   [0:0] tmp_i_reg_201_pp0_iter2_reg;
reg   [0:0] ret_reg_215;
reg   [0:0] ret_reg_215_pp0_iter2_reg;
reg    ap_predicate_op43_write_state4;
reg    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
reg   [31:0] sum;
reg   [5:0] count_1;
reg    src_TDATA_blk_n;
reg    stage1_s_blk_n;
reg    mean_s_blk_n;
wire   [0:0] tmp_i_reg_201_pp0_iter0_reg;
reg   [0:0] tmp_i_reg_201_pp0_iter1_reg;
reg   [63:0] src_read_reg_205;
reg   [63:0] src_read_reg_205_pp0_iter1_reg;
reg   [63:0] src_read_reg_205_pp0_iter2_reg;
wire   [31:0] add_i_i_fu_101_p2;
reg   [31:0] add_i_i_reg_210;
wire   [0:0] ret_fu_143_p3;
wire   [0:0] ret_reg_215_pp0_iter0_reg;
reg   [0:0] ret_reg_215_pp0_iter1_reg;
wire   [31:0] add_i_fu_105_p2;
reg   [31:0] add_i_reg_219;
reg   [31:0] ap_phi_mux_sum_new_0_i_phi_fu_94_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_sum_new_0_i_reg_90;
reg   [31:0] ap_phi_reg_pp0_iter1_sum_new_0_i_reg_90;
wire   [5:0] add_ln72_2_fu_173_p2;
wire   [31:0] add_i_i_fu_101_p0;
wire   [31:0] add_i_i_fu_101_p1;
wire   [31:0] trunc_ln41_fu_115_p1;
wire   [31:0] tmp_5_i4_fu_124_p4;
wire   [0:0] tmp_fu_151_p3;
wire   [5:0] and_ln_fu_159_p3;
wire   [5:0] add_ln72_fu_167_p2;
wire   [31:0] grp_fu_110_p2;
reg    grp_fu_110_ce;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
wire    regslice_both_src_U_apdone_blk;
wire   [63:0] src_TDATA_int_regslice;
wire    src_TVALID_int_regslice;
reg    src_TREADY_int_regslice;
wire    regslice_both_src_U_ack_in;
reg    ap_condition_276;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 sum = 32'd0;
#0 count_1 = 6'd30;
end

layernorm_top_fadd_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_primitive_dsp_1_U1(
    .din0(add_i_i_fu_101_p0),
    .din1(add_i_i_fu_101_p1),
    .dout(add_i_i_fu_101_p2)
);

layernorm_top_fadd_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_primitive_dsp_1_U2(
    .din0(sum),
    .din1(add_i_i_reg_210),
    .dout(add_i_fu_105_p2)
);

layernorm_top_fmul_32ns_32ns_32_2_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_primitive_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_i_reg_219),
    .din1(32'd1015021568),
    .ce(grp_fu_110_ce),
    .dout(grp_fu_110_p2)
);

layernorm_top_regslice_both #(
    .DataWidth( 64 ))
regslice_both_src_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(src_TDATA),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_U_ack_in),
    .data_out(src_TDATA_int_regslice),
    .vld_out(src_TVALID_int_regslice),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        count_1 <= 6'd30;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
            count_1 <= add_ln72_2_fu_173_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sum <= 32'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state2) & (tmp_i_reg_201_pp0_iter0_reg == 1'd1))) begin
            sum <= ap_phi_mux_sum_new_0_i_phi_fu_94_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_276)) begin
        if (((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (ret_fu_143_p3 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_sum_new_0_i_reg_90 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_sum_new_0_i_reg_90 <= ap_phi_reg_pp0_iter0_sum_new_0_i_reg_90;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        add_i_i_reg_210 <= add_i_i_fu_101_p2;
        ret_reg_215 <= count_1[32'd5];
        src_read_reg_205 <= src_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state2) & (tmp_i_reg_201_pp0_iter0_reg == 1'd1))) begin
        add_i_reg_219 <= add_i_fu_105_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ret_reg_215_pp0_iter1_reg <= ret_reg_215;
        src_read_reg_205_pp0_iter1_reg <= src_read_reg_205;
        tmp_i_reg_201_pp0_iter1_reg <= tmp_i_reg_201;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ret_reg_215_pp0_iter2_reg <= ret_reg_215_pp0_iter1_reg;
        src_read_reg_205_pp0_iter2_reg <= src_read_reg_205_pp0_iter1_reg;
        tmp_i_reg_201_pp0_iter2_reg <= tmp_i_reg_201_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_i_reg_201 <= tmp_i_nbreadreq_fu_62_p3;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0)))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ret_reg_215_pp0_iter0_reg == 1'd0) & (tmp_i_reg_201_pp0_iter0_reg == 1'd1))) begin
        ap_phi_mux_sum_new_0_i_phi_fu_94_p4 = add_i_fu_105_p2;
    end else begin
        ap_phi_mux_sum_new_0_i_phi_fu_94_p4 = ap_phi_reg_pp0_iter1_sum_new_0_i_reg_90;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
        grp_fu_110_ce = 1'b1;
    end else begin
        grp_fu_110_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op43_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        mean_s_blk_n = mean_s_full_n;
    end else begin
        mean_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))) & (ap_predicate_op43_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        mean_s_write = 1'b1;
    end else begin
        mean_s_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        src_TDATA_blk_n = src_TVALID_int_regslice;
    end else begin
        src_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        src_TREADY_int_regslice = 1'b1;
    end else begin
        src_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        stage1_s_blk_n = stage1_s_full_n;
    end else begin
        stage1_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))) & (tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        stage1_s_write = 1'b1;
    end else begin
        stage1_s_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0))) & ~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

assign add_i_i_fu_101_p0 = trunc_ln41_fu_115_p1;

assign add_i_i_fu_101_p1 = tmp_5_i4_fu_124_p4;

assign add_ln72_2_fu_173_p2 = (add_ln72_fu_167_p2 + count_1);

assign add_ln72_fu_167_p2 = ($signed(and_ln_fu_159_p3) + $signed(6'd63));

assign and_ln_fu_159_p3 = {{tmp_fu_151_p3}, {5'd0}};

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_276 = (~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_i_nbreadreq_fu_62_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (((ap_predicate_op43_write_state4 == 1'b1) & (mean_s_full_n == 1'b0)) | ((tmp_i_reg_201_pp0_iter2_reg == 1'd1) & (stage1_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_phi_reg_pp0_iter0_sum_new_0_i_reg_90 = 'bx;

always @ (*) begin
    ap_predicate_op43_write_state4 = ((ret_reg_215_pp0_iter2_reg == 1'd1) & (tmp_i_reg_201_pp0_iter2_reg == 1'd1));
end

assign mean_s_din = grp_fu_110_p2;

assign ret_fu_143_p3 = count_1[32'd5];

assign ret_reg_215_pp0_iter0_reg = ret_reg_215;

assign src_TREADY = regslice_both_src_U_ack_in;

assign stage1_s_din = src_read_reg_205_pp0_iter2_reg;

assign tmp_5_i4_fu_124_p4 = {{src_TDATA_int_regslice[63:32]}};

assign tmp_fu_151_p3 = count_1[32'd5];

assign tmp_i_nbreadreq_fu_62_p3 = src_TVALID_int_regslice;

assign tmp_i_reg_201_pp0_iter0_reg = tmp_i_reg_201;

assign trunc_ln41_fu_115_p1 = src_TDATA_int_regslice[31:0];

endmodule //layernorm_top_mean_stage_64ul_float_float_2ul_s
