// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module softmax_top_max_extract (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_TVALID,
        sm_inst_max2exp_dat_din,
        sm_inst_max2exp_dat_num_data_valid,
        sm_inst_max2exp_dat_fifo_cap,
        sm_inst_max2exp_dat_full_n,
        sm_inst_max2exp_dat_write,
        sm_inst_max2exp_max_din,
        sm_inst_max2exp_max_num_data_valid,
        sm_inst_max2exp_max_fifo_cap,
        sm_inst_max2exp_max_full_n,
        sm_inst_max2exp_max_write,
        src_TDATA,
        src_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   src_TVALID;
output  [127:0] sm_inst_max2exp_dat_din;
input  [5:0] sm_inst_max2exp_dat_num_data_valid;
input  [5:0] sm_inst_max2exp_dat_fifo_cap;
input   sm_inst_max2exp_dat_full_n;
output   sm_inst_max2exp_dat_write;
output  [31:0] sm_inst_max2exp_max_din;
input  [1:0] sm_inst_max2exp_max_num_data_valid;
input  [1:0] sm_inst_max2exp_max_fifo_cap;
input   sm_inst_max2exp_max_full_n;
output   sm_inst_max2exp_max_write;
input  [127:0] src_TDATA;
output   src_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg sm_inst_max2exp_dat_write;
reg sm_inst_max2exp_max_write;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
wire   [0:0] tmp_i_nbreadreq_fu_104_p3;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] tmp_i_reg_653;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] tmp_i_reg_653_pp0_iter2_reg;
reg   [0:0] ret_reg_683;
reg   [0:0] ret_reg_683_pp0_iter2_reg;
reg    ap_predicate_op102_write_state4;
reg    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
reg   [31:0] sm_inst_exp_valid;
reg   [5:0] sm_inst_max_val;
reg    src_TDATA_blk_n;
reg    sm_inst_max2exp_dat_blk_n;
reg    sm_inst_max2exp_max_blk_n;
reg   [0:0] tmp_i_reg_653_pp0_iter1_reg;
reg   [127:0] src_read_reg_657;
wire   [31:0] tree_4_fu_383_p3;
reg   [31:0] tree_4_reg_662;
wire   [31:0] tree_5_fu_391_p3;
reg   [31:0] tree_5_reg_669;
wire   [31:0] tmp_6_i_fu_489_p6;
reg   [31:0] tmp_6_i_reg_676;
wire   [0:0] ret_fu_505_p3;
wire   [0:0] ret_reg_683_pp0_iter1_reg;
wire   [31:0] select_ln147_fu_635_p3;
reg   [31:0] select_ln147_reg_687;
reg   [31:0] ap_phi_mux_sm_inst_exp_valid_new_0_i_phi_fu_136_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_sm_inst_exp_valid_new_0_i_reg_132;
reg   [31:0] ap_phi_reg_pp0_iter1_sm_inst_exp_valid_new_0_i_reg_132;
reg   [31:0] ap_phi_reg_pp0_iter2_sm_inst_exp_valid_new_0_i_reg_132;
wire   [5:0] add_ln96_1_fu_535_p2;
wire   [31:0] tree_1_fu_193_p1;
wire   [31:0] tree_fu_208_p1;
wire   [31:0] tree_3_fu_163_p1;
wire   [31:0] tree_2_fu_178_p1;
wire   [31:0] trunc_ln146_fu_159_p1;
wire   [31:0] tmp_1_i4_fu_168_p4;
wire   [31:0] tmp_2_i5_fu_183_p4;
wire   [31:0] tmp_3_i6_fu_198_p4;
wire   [7:0] tmp_1_fu_213_p4;
wire   [22:0] tmp_2_fu_223_p4;
wire   [0:0] icmp_ln224_1_fu_259_p2;
wire   [0:0] icmp_ln224_fu_253_p2;
wire   [7:0] tmp_3_fu_233_p4;
wire   [22:0] tmp_4_fu_243_p4;
wire   [0:0] icmp_ln224_3_fu_277_p2;
wire   [0:0] icmp_ln224_2_fu_271_p2;
wire   [0:0] or_ln224_fu_265_p2;
wire   [0:0] or_ln224_1_fu_283_p2;
wire   [0:0] and_ln224_fu_289_p2;
wire   [0:0] tmp_5_fu_143_p2;
wire   [7:0] tmp_6_fu_301_p4;
wire   [22:0] trunc_ln224_fu_311_p1;
wire   [0:0] icmp_ln224_5_fu_341_p2;
wire   [0:0] icmp_ln224_4_fu_335_p2;
wire   [7:0] tmp_7_fu_315_p4;
wire   [22:0] tmp_8_fu_325_p4;
wire   [0:0] icmp_ln224_7_fu_359_p2;
wire   [0:0] icmp_ln224_6_fu_353_p2;
wire   [0:0] or_ln224_2_fu_347_p2;
wire   [0:0] or_ln224_3_fu_365_p2;
wire   [0:0] and_ln224_2_fu_371_p2;
wire   [0:0] tmp_9_fu_147_p2;
wire   [0:0] and_ln224_1_fu_295_p2;
wire   [0:0] and_ln224_3_fu_377_p2;
wire   [31:0] bitcast_ln224_fu_399_p1;
wire   [31:0] bitcast_ln224_1_fu_416_p1;
wire   [7:0] tmp_s_fu_402_p4;
wire   [22:0] trunc_ln224_1_fu_412_p1;
wire   [0:0] icmp_ln224_9_fu_439_p2;
wire   [0:0] icmp_ln224_8_fu_433_p2;
wire   [7:0] tmp_10_fu_419_p4;
wire   [22:0] trunc_ln224_2_fu_429_p1;
wire   [0:0] icmp_ln224_11_fu_457_p2;
wire   [0:0] icmp_ln224_10_fu_451_p2;
wire   [0:0] or_ln224_4_fu_445_p2;
wire   [0:0] or_ln224_5_fu_463_p2;
wire   [0:0] and_ln224_4_fu_469_p2;
wire   [0:0] tmp_11_fu_151_p2;
wire   [0:0] and_ln224_5_fu_475_p2;
wire   [1:0] tmp_6_i_fu_489_p5;
wire   [0:0] tmp_fu_513_p3;
wire   [5:0] and_ln_fu_521_p3;
wire   [5:0] add_ln96_fu_529_p2;
wire   [31:0] bitcast_ln224_2_fu_552_p1;
wire   [31:0] bitcast_ln224_3_fu_570_p1;
wire   [7:0] tmp_12_fu_556_p4;
wire   [22:0] trunc_ln224_3_fu_566_p1;
wire   [0:0] icmp_ln224_13_fu_593_p2;
wire   [0:0] icmp_ln224_12_fu_587_p2;
wire   [7:0] tmp_13_fu_573_p4;
wire   [22:0] trunc_ln224_4_fu_583_p1;
wire   [0:0] icmp_ln224_15_fu_611_p2;
wire   [0:0] icmp_ln224_14_fu_605_p2;
wire   [0:0] or_ln224_6_fu_599_p2;
wire   [0:0] or_ln224_7_fu_617_p2;
wire   [0:0] and_ln224_6_fu_623_p2;
wire   [0:0] tmp_14_fu_155_p2;
wire   [0:0] and_ln224_7_fu_629_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
wire    regslice_both_src_U_apdone_blk;
wire   [127:0] src_TDATA_int_regslice;
wire    src_TVALID_int_regslice;
reg    src_TREADY_int_regslice;
wire    regslice_both_src_U_ack_in;
reg    ap_condition_132;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 sm_inst_exp_valid = 32'd4286578687;
#0 sm_inst_max_val = 6'd30;
end

softmax_top_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U1(
    .din0(tree_1_fu_193_p1),
    .din1(tree_fu_208_p1),
    .opcode(5'd4),
    .dout(tmp_5_fu_143_p2)
);

softmax_top_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U2(
    .din0(tree_3_fu_163_p1),
    .din1(tree_2_fu_178_p1),
    .opcode(5'd4),
    .dout(tmp_9_fu_147_p2)
);

softmax_top_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U3(
    .din0(tree_5_reg_669),
    .din1(tree_4_reg_662),
    .opcode(5'd4),
    .dout(tmp_11_fu_151_p2)
);

softmax_top_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U4(
    .din0(sm_inst_exp_valid),
    .din1(tmp_6_i_reg_676),
    .opcode(5'd4),
    .dout(tmp_14_fu_155_p2)
);

softmax_top_mux_4_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_4_2_32_1_1_U5(
    .din0(32'd0),
    .din1(tree_5_reg_669),
    .din2(tree_4_reg_662),
    .din3(32'd0),
    .din4(tmp_6_i_fu_489_p5),
    .dout(tmp_6_i_fu_489_p6)
);

softmax_top_regslice_both #(
    .DataWidth( 128 ))
regslice_both_src_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(src_TDATA),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_U_ack_in),
    .data_out(src_TDATA_int_regslice),
    .vld_out(src_TVALID_int_regslice),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_132)) begin
        if (((tmp_i_reg_653 == 1'd1) & (ret_fu_505_p3 == 1'd1))) begin
            ap_phi_reg_pp0_iter2_sm_inst_exp_valid_new_0_i_reg_132 <= 32'd4286578687;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_sm_inst_exp_valid_new_0_i_reg_132 <= ap_phi_reg_pp0_iter1_sm_inst_exp_valid_new_0_i_reg_132;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2)) | ((src_TVALID_int_regslice == 1'b0) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_sm_inst_exp_valid_new_0_i_reg_132 <= ap_phi_reg_pp0_iter0_sm_inst_exp_valid_new_0_i_reg_132;
        tmp_i_reg_653 <= tmp_i_nbreadreq_fu_104_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (tmp_i_reg_653 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ret_reg_683 <= sm_inst_max_val[32'd5];
        sm_inst_max_val <= add_ln96_1_fu_535_p2;
        tmp_6_i_reg_676 <= tmp_6_i_fu_489_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ret_reg_683_pp0_iter2_reg <= ret_reg_683;
        tmp_i_reg_653_pp0_iter2_reg <= tmp_i_reg_653_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4))) & (1'b1 == ap_CS_iter2_fsm_state3) & (tmp_i_reg_653_pp0_iter1_reg == 1'd1))) begin
        select_ln147_reg_687 <= select_ln147_fu_635_p3;
        sm_inst_exp_valid <= ap_phi_mux_sm_inst_exp_valid_new_0_i_phi_fu_136_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2)) | ((src_TVALID_int_regslice == 1'b0) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1))) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        src_read_reg_657 <= src_TDATA_int_regslice;
        tree_4_reg_662 <= tree_4_fu_383_p3;
        tree_5_reg_669 <= tree_5_fu_391_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        tmp_i_reg_653_pp0_iter1_reg <= tmp_i_reg_653;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((src_TVALID_int_regslice == 1'b0) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ret_reg_683_pp0_iter1_reg == 1'd0) & (tmp_i_reg_653_pp0_iter1_reg == 1'd1))) begin
        ap_phi_mux_sm_inst_exp_valid_new_0_i_phi_fu_136_p4 = select_ln147_fu_635_p3;
    end else begin
        ap_phi_mux_sm_inst_exp_valid_new_0_i_phi_fu_136_p4 = ap_phi_reg_pp0_iter2_sm_inst_exp_valid_new_0_i_reg_132;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2)) | ((src_TVALID_int_regslice == 1'b0) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_653 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        sm_inst_max2exp_dat_blk_n = sm_inst_max2exp_dat_full_n;
    end else begin
        sm_inst_max2exp_dat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (tmp_i_reg_653 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        sm_inst_max2exp_dat_write = 1'b1;
    end else begin
        sm_inst_max2exp_dat_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op102_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        sm_inst_max2exp_max_blk_n = sm_inst_max2exp_max_full_n;
    end else begin
        sm_inst_max2exp_max_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0))) & (ap_predicate_op102_write_state4 == 1'b1) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        sm_inst_max2exp_max_write = 1'b1;
    end else begin
        sm_inst_max2exp_max_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        src_TDATA_blk_n = src_TVALID_int_regslice;
    end else begin
        src_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2)) | ((src_TVALID_int_regslice == 1'b0) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1))) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        src_TREADY_int_regslice = 1'b1;
    end else begin
        src_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((src_TVALID_int_regslice == 1'b0) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1))) & ~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((src_TVALID_int_regslice == 1'b0) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2)) | ((src_TVALID_int_regslice == 1'b0) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0)) & ~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4))) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

assign add_ln96_1_fu_535_p2 = (add_ln96_fu_529_p2 + sm_inst_max_val);

assign add_ln96_fu_529_p2 = ($signed(and_ln_fu_521_p3) + $signed(6'd63));

assign and_ln224_1_fu_295_p2 = (tmp_5_fu_143_p2 & and_ln224_fu_289_p2);

assign and_ln224_2_fu_371_p2 = (or_ln224_3_fu_365_p2 & or_ln224_2_fu_347_p2);

assign and_ln224_3_fu_377_p2 = (tmp_9_fu_147_p2 & and_ln224_2_fu_371_p2);

assign and_ln224_4_fu_469_p2 = (or_ln224_5_fu_463_p2 & or_ln224_4_fu_445_p2);

assign and_ln224_5_fu_475_p2 = (tmp_11_fu_151_p2 & and_ln224_4_fu_469_p2);

assign and_ln224_6_fu_623_p2 = (or_ln224_7_fu_617_p2 & or_ln224_6_fu_599_p2);

assign and_ln224_7_fu_629_p2 = (tmp_14_fu_155_p2 & and_ln224_6_fu_623_p2);

assign and_ln224_fu_289_p2 = (or_ln224_fu_265_p2 & or_ln224_1_fu_283_p2);

assign and_ln_fu_521_p3 = {{tmp_fu_513_p3}, {5'd0}};

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((src_TVALID_int_regslice == 1'b0) & (tmp_i_nbreadreq_fu_104_p3 == 1'd1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_132 = (~((ap_done_reg == 1'b1) | ((ap_predicate_op102_write_state4 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0) & (1'b1 == ap_CS_iter3_fsm_state4)) | ((tmp_i_reg_653 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2));
end

assign ap_phi_reg_pp0_iter0_sm_inst_exp_valid_new_0_i_reg_132 = 'bx;

always @ (*) begin
    ap_predicate_op102_write_state4 = ((ret_reg_683_pp0_iter2_reg == 1'd1) & (tmp_i_reg_653_pp0_iter2_reg == 1'd1));
end

assign bitcast_ln224_1_fu_416_p1 = tree_4_reg_662;

assign bitcast_ln224_2_fu_552_p1 = sm_inst_exp_valid;

assign bitcast_ln224_3_fu_570_p1 = tmp_6_i_reg_676;

assign bitcast_ln224_fu_399_p1 = tree_5_reg_669;

assign icmp_ln224_10_fu_451_p2 = ((tmp_10_fu_419_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_11_fu_457_p2 = ((trunc_ln224_2_fu_429_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_12_fu_587_p2 = ((tmp_12_fu_556_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_13_fu_593_p2 = ((trunc_ln224_3_fu_566_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_14_fu_605_p2 = ((tmp_13_fu_573_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_15_fu_611_p2 = ((trunc_ln224_4_fu_583_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_1_fu_259_p2 = ((tmp_2_fu_223_p4 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_2_fu_271_p2 = ((tmp_3_fu_233_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_3_fu_277_p2 = ((tmp_4_fu_243_p4 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_4_fu_335_p2 = ((tmp_6_fu_301_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_5_fu_341_p2 = ((trunc_ln224_fu_311_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_6_fu_353_p2 = ((tmp_7_fu_315_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_7_fu_359_p2 = ((tmp_8_fu_325_p4 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_8_fu_433_p2 = ((tmp_s_fu_402_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_9_fu_439_p2 = ((trunc_ln224_1_fu_412_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_253_p2 = ((tmp_1_fu_213_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln224_1_fu_283_p2 = (icmp_ln224_3_fu_277_p2 | icmp_ln224_2_fu_271_p2);

assign or_ln224_2_fu_347_p2 = (icmp_ln224_5_fu_341_p2 | icmp_ln224_4_fu_335_p2);

assign or_ln224_3_fu_365_p2 = (icmp_ln224_7_fu_359_p2 | icmp_ln224_6_fu_353_p2);

assign or_ln224_4_fu_445_p2 = (icmp_ln224_9_fu_439_p2 | icmp_ln224_8_fu_433_p2);

assign or_ln224_5_fu_463_p2 = (icmp_ln224_11_fu_457_p2 | icmp_ln224_10_fu_451_p2);

assign or_ln224_6_fu_599_p2 = (icmp_ln224_13_fu_593_p2 | icmp_ln224_12_fu_587_p2);

assign or_ln224_7_fu_617_p2 = (icmp_ln224_15_fu_611_p2 | icmp_ln224_14_fu_605_p2);

assign or_ln224_fu_265_p2 = (icmp_ln224_fu_253_p2 | icmp_ln224_1_fu_259_p2);

assign ret_fu_505_p3 = sm_inst_max_val[32'd5];

assign ret_reg_683_pp0_iter1_reg = ret_reg_683;

assign select_ln147_fu_635_p3 = ((and_ln224_7_fu_629_p2[0:0] == 1'b1) ? tmp_6_i_reg_676 : sm_inst_exp_valid);

assign sm_inst_max2exp_dat_din = src_read_reg_657;

assign sm_inst_max2exp_max_din = select_ln147_reg_687;

assign src_TREADY = regslice_both_src_U_ack_in;

assign tmp_10_fu_419_p4 = {{bitcast_ln224_1_fu_416_p1[30:23]}};

assign tmp_12_fu_556_p4 = {{bitcast_ln224_2_fu_552_p1[30:23]}};

assign tmp_13_fu_573_p4 = {{bitcast_ln224_3_fu_570_p1[30:23]}};

assign tmp_1_fu_213_p4 = {{src_TDATA_int_regslice[94:87]}};

assign tmp_1_i4_fu_168_p4 = {{src_TDATA_int_regslice[63:32]}};

assign tmp_2_fu_223_p4 = {{src_TDATA_int_regslice[86:64]}};

assign tmp_2_i5_fu_183_p4 = {{src_TDATA_int_regslice[95:64]}};

assign tmp_3_fu_233_p4 = {{src_TDATA_int_regslice[126:119]}};

assign tmp_3_i6_fu_198_p4 = {{src_TDATA_int_regslice[127:96]}};

assign tmp_4_fu_243_p4 = {{src_TDATA_int_regslice[118:96]}};

assign tmp_6_fu_301_p4 = {{src_TDATA_int_regslice[30:23]}};

assign tmp_6_i_fu_489_p5 = ((and_ln224_5_fu_475_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign tmp_7_fu_315_p4 = {{src_TDATA_int_regslice[62:55]}};

assign tmp_8_fu_325_p4 = {{src_TDATA_int_regslice[54:32]}};

assign tmp_fu_513_p3 = sm_inst_max_val[32'd5];

assign tmp_i_nbreadreq_fu_104_p3 = src_TVALID_int_regslice;

assign tmp_s_fu_402_p4 = {{bitcast_ln224_fu_399_p1[30:23]}};

assign tree_1_fu_193_p1 = tmp_2_i5_fu_183_p4;

assign tree_2_fu_178_p1 = tmp_1_i4_fu_168_p4;

assign tree_3_fu_163_p1 = trunc_ln146_fu_159_p1;

assign tree_4_fu_383_p3 = ((and_ln224_1_fu_295_p2[0:0] == 1'b1) ? tree_fu_208_p1 : tree_1_fu_193_p1);

assign tree_5_fu_391_p3 = ((and_ln224_3_fu_377_p2[0:0] == 1'b1) ? tree_2_fu_178_p1 : tree_3_fu_163_p1);

assign tree_fu_208_p1 = tmp_3_i6_fu_198_p4;

assign trunc_ln146_fu_159_p1 = src_TDATA_int_regslice[31:0];

assign trunc_ln224_1_fu_412_p1 = bitcast_ln224_fu_399_p1[22:0];

assign trunc_ln224_2_fu_429_p1 = bitcast_ln224_1_fu_416_p1[22:0];

assign trunc_ln224_3_fu_566_p1 = bitcast_ln224_2_fu_552_p1[22:0];

assign trunc_ln224_4_fu_583_p1 = bitcast_ln224_3_fu_570_p1[22:0];

assign trunc_ln224_fu_311_p1 = src_TDATA_int_regslice[22:0];

endmodule //softmax_top_max_extract
