// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layernorm_top_var_stage_64ul_float_float_float_2ul_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stage2_s_din,
        stage2_s_num_data_valid,
        stage2_s_fifo_cap,
        stage2_s_full_n,
        stage2_s_write,
        var_s_din,
        var_s_num_data_valid,
        var_s_fifo_cap,
        var_s_full_n,
        var_s_write,
        mean_s_dout,
        mean_s_num_data_valid,
        mean_s_fifo_cap,
        mean_s_empty_n,
        mean_s_read,
        stage1_s_dout,
        stage1_s_num_data_valid,
        stage1_s_fifo_cap,
        stage1_s_empty_n,
        stage1_s_read
);

parameter    ap_ST_iter0_fsm_state1 = 4'd1;
parameter    ap_ST_iter0_fsm_state2 = 4'd4;
parameter    ap_ST_iter0_fsm_state3 = 4'd2;
parameter    ap_ST_iter0_fsm_state4 = 4'd8;
parameter    ap_ST_iter1_fsm_state5 = 4'd2;
parameter    ap_ST_iter1_fsm_state6 = 4'd4;
parameter    ap_ST_iter1_fsm_state7 = 4'd8;
parameter    ap_ST_iter1_fsm_state0 = 4'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [63:0] stage2_s_din;
input  [5:0] stage2_s_num_data_valid;
input  [5:0] stage2_s_fifo_cap;
input   stage2_s_full_n;
output   stage2_s_write;
output  [31:0] var_s_din;
input  [1:0] var_s_num_data_valid;
input  [1:0] var_s_fifo_cap;
input   var_s_full_n;
output   var_s_write;
input  [31:0] mean_s_dout;
input  [1:0] mean_s_num_data_valid;
input  [1:0] mean_s_fifo_cap;
input   mean_s_empty_n;
output   mean_s_read;
input  [63:0] stage1_s_dout;
input  [5:0] stage1_s_num_data_valid;
input  [5:0] stage1_s_fifo_cap;
input   stage1_s_empty_n;
output   stage1_s_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stage2_s_write;
reg var_s_write;
reg mean_s_read;
reg stage1_s_read;

reg   [3:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [3:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire    ap_CS_iter0_fsm_state4;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state5;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_CS_iter1_fsm_state6;
reg   [0:0] tmp_i_reg_374;
reg   [0:0] tmp_i_reg_374_pp0_iter0_reg;
reg   [0:0] tmp_2_i_reg_381;
reg   [0:0] tmp_2_i_reg_381_pp0_iter0_reg;
reg   [0:0] valid_load_reg_370;
reg   [0:0] valid_load_reg_370_pp0_iter0_reg;
reg    ap_predicate_op84_write_state7;
reg   [0:0] ret_reg_404;
wire   [0:0] ret_reg_404_pp0_iter0_reg;
reg    ap_predicate_op87_write_state7;
reg    ap_block_state7_pp0_stage2_iter1;
wire    ap_CS_iter1_fsm_state7;
reg    ap_done_reg;
reg   [0:0] valid;
reg   [31:0] mean;
reg   [31:0] sumq;
reg   [5:0] count;
reg    stage1_s_blk_n;
wire   [0:0] tmp_i_nbreadreq_fu_80_p3;
wire   [0:0] tmp_2_i_nbreadreq_fu_94_p3;
wire   [0:0] valid_load_load_fu_235_p1;
reg    stage2_s_blk_n;
reg    var_s_blk_n;
reg   [0:0] valid_flag_0_i_reg_122;
reg    ap_predicate_op41_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [31:0] xm_fu_202_p2;
reg   [31:0] xm_reg_385;
reg   [31:0] xm_reg_385_pp0_iter0_reg;
wire   [31:0] xm_1_fu_206_p2;
reg   [31:0] xm_1_reg_392;
reg   [31:0] xm_1_reg_392_pp0_iter0_reg;
reg   [31:0] grp_fu_214_p2;
wire    ap_CS_iter0_fsm_state2;
wire    ap_block_state2_pp0_stage2_iter0;
wire   [0:0] ret_fu_291_p3;
wire   [31:0] add_i_fu_210_p2;
reg   [0:0] ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_122;
reg   [0:0] ap_phi_mux_valid_flag_1_i_phi_fu_140_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_valid_flag_1_i_reg_136;
reg   [0:0] ap_phi_reg_pp0_iter1_valid_flag_1_i_reg_136;
reg   [0:0] ap_phi_mux_valid_new_1_i_phi_fu_152_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_valid_new_1_i_reg_148;
reg   [0:0] ap_phi_reg_pp0_iter1_valid_new_1_i_reg_148;
reg   [0:0] ap_phi_mux_valid_flag_2_i_phi_fu_164_p6;
reg   [0:0] ap_phi_reg_pp0_iter1_valid_flag_2_i_reg_160;
wire   [0:0] ap_phi_reg_pp0_iter0_valid_flag_2_i_reg_160;
reg   [0:0] ap_phi_mux_valid_new_2_i_phi_fu_180_p6;
reg   [0:0] ap_phi_reg_pp0_iter1_valid_new_2_i_reg_175;
wire   [0:0] ap_phi_reg_pp0_iter0_valid_new_2_i_reg_175;
wire   [31:0] ap_phi_reg_pp0_iter0_sumq_new_0_i_reg_191;
reg   [31:0] ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_191;
reg   [0:0] ap_sig_allocacmp_valid_load;
wire   [31:0] bitcast_ln87_fu_247_p1;
wire   [0:0] p_vld_fu_239_p1;
reg   [31:0] ap_sig_allocacmp_mean_load;
wire   [5:0] add_ln72_1_fu_321_p2;
wire   [0:0] mean_s_read_nbread_fu_88_p2_0;
wire   [31:0] xm_fu_202_p0;
wire   [31:0] xm_1_fu_206_p0;
wire   [31:0] grp_fu_226_p4;
reg   [31:0] grp_fu_214_p0;
reg   [31:0] grp_fu_214_p1;
reg   [31:0] grp_fu_220_p0;
wire   [31:0] grp_fu_220_p1;
wire   [31:0] trunc_ln92_fu_257_p1;
wire   [31:0] tmp_3_i6_fu_266_p4;
wire   [0:0] tmp_fu_299_p3;
wire   [5:0] and_ln_fu_307_p3;
wire   [5:0] add_ln72_fu_315_p2;
wire   [31:0] bitcast_ln103_1_fu_353_p1;
wire   [31:0] bitcast_ln103_fu_350_p1;
reg   [31:0] grp_fu_220_p2;
reg    grp_fu_214_ce;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_CS_iter0_fsm_state3;
wire   [31:0] pre_grp_fu_214_p2;
reg   [31:0] pre_grp_fu_214_p2_reg;
reg    grp_fu_220_ce;
wire   [31:0] pre_grp_fu_220_p2;
reg   [31:0] pre_grp_fu_220_p2_reg;
reg    grp_fu_226_ce;
reg   [3:0] ap_NS_iter0_fsm;
reg   [3:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter0_fsm_state2_blk;
wire    ap_ST_iter0_fsm_state3_blk;
wire    ap_ST_iter0_fsm_state4_blk;
wire    ap_ST_iter1_fsm_state5_blk;
wire    ap_ST_iter1_fsm_state6_blk;
reg    ap_ST_iter1_fsm_state7_blk;
reg    ap_condition_218;
reg    ap_condition_104;
reg    ap_condition_234;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 4'd1;
#0 ap_CS_iter1_fsm = 4'd1;
#0 ap_done_reg = 1'b0;
#0 valid = 1'd0;
#0 mean = 32'd0;
#0 sumq = 32'd0;
#0 count = 6'd30;
end

layernorm_top_fsub_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_1_primitive_dsp_1_U10(
    .din0(xm_fu_202_p0),
    .din1(ap_sig_allocacmp_mean_load),
    .dout(xm_fu_202_p2)
);

layernorm_top_fsub_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_1_primitive_dsp_1_U11(
    .din0(xm_1_fu_206_p0),
    .din1(ap_sig_allocacmp_mean_load),
    .dout(xm_1_fu_206_p2)
);

layernorm_top_fadd_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_primitive_dsp_1_U12(
    .din0(sumq),
    .din1(grp_fu_226_p4),
    .dout(add_i_fu_210_p2)
);

layernorm_top_fmul_32ns_32ns_32_2_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_primitive_dsp_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_214_p0),
    .din1(grp_fu_214_p1),
    .ce(grp_fu_214_ce),
    .dout(pre_grp_fu_214_p2)
);

layernorm_top_fmul_32ns_32ns_32_2_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_primitive_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_220_p0),
    .din1(grp_fu_220_p1),
    .ce(grp_fu_220_ce),
    .dout(pre_grp_fu_220_p2)
);

layernorm_top_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(xm_reg_385),
    .din2(xm_reg_385),
    .din3(grp_fu_214_p2),
    .ce(grp_fu_226_ce),
    .dout(grp_fu_226_p4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        count <= 6'd30;
    end else begin
        if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4) & (((valid_load_reg_370 == 1'd1) & (tmp_2_i_reg_381 == 1'd1)) | ((tmp_2_i_reg_381 == 1'd1) & (tmp_i_reg_374 == 1'd1))))) begin
            count <= add_ln72_1_fu_321_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sumq <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_iter1_fsm_state6) & (ap_done_reg == 1'b0) & (((valid_load_reg_370_pp0_iter0_reg == 1'd1) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1)) | ((tmp_2_i_reg_381_pp0_iter0_reg == 1'd1) & (tmp_i_reg_374_pp0_iter0_reg == 1'd1))))) begin
            sumq <= ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_191;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        valid <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_iter1_fsm_state5) & (ap_phi_mux_valid_flag_2_i_phi_fu_164_p6 == 1'd1) & (ap_done_reg == 1'b0))) begin
            valid <= ap_phi_mux_valid_new_2_i_phi_fu_180_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (valid_load_reg_370 == 1'd0) & (tmp_i_reg_374 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_122 <= 1'd1;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_sig_allocacmp_valid_load == 1'd1))) begin
        ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_122 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter1_fsm_state5) & (ap_done_reg == 1'b0) & (((ret_reg_404_pp0_iter0_reg == 1'd0) & (valid_load_reg_370_pp0_iter0_reg == 1'd1) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1)) | ((ret_reg_404_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1) & (tmp_i_reg_374_pp0_iter0_reg == 1'd1))))) begin
        ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_191 <= add_i_fu_210_p2;
    end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4) & (((valid_load_reg_370 == 1'd1) & (tmp_2_i_reg_381 == 1'd1) & (ret_fu_291_p3 == 1'd1)) | ((tmp_2_i_reg_381 == 1'd1) & (tmp_i_reg_374 == 1'd1) & (ret_fu_291_p3 == 1'd1))))) begin
        ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_191 <= 32'd0;
    end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4))) begin
        ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_191 <= ap_phi_reg_pp0_iter0_sumq_new_0_i_reg_191;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_104)) begin
        if ((1'b1 == ap_condition_218)) begin
            ap_phi_reg_pp0_iter1_valid_flag_1_i_reg_136 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_valid_flag_1_i_reg_136 <= ap_phi_reg_pp0_iter0_valid_flag_1_i_reg_136;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_104)) begin
        if ((1'b1 == ap_condition_234)) begin
            ap_phi_reg_pp0_iter1_valid_flag_2_i_reg_160 <= ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_122;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_valid_flag_2_i_reg_160 <= ap_phi_reg_pp0_iter0_valid_flag_2_i_reg_160;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_104)) begin
        if ((1'b1 == ap_condition_218)) begin
            ap_phi_reg_pp0_iter1_valid_new_1_i_reg_148 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_valid_new_1_i_reg_148 <= ap_phi_reg_pp0_iter0_valid_new_1_i_reg_148;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_104)) begin
        if ((1'b1 == ap_condition_234)) begin
            ap_phi_reg_pp0_iter1_valid_new_2_i_reg_175 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_valid_new_2_i_reg_175 <= ap_phi_reg_pp0_iter0_valid_new_2_i_reg_175;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        grp_fu_214_ce <= 1'b1;
    end else begin
        grp_fu_214_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_iter1_fsm_state6) & (ap_done_reg == 1'b0)) | ((1'b1 == ap_CS_iter1_fsm_state5) & (ap_done_reg == 1'b0)) | (~((ap_done_reg == 1'b1) | ((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state7)))) begin
        grp_fu_220_ce <= 1'b1;
    end else begin
        grp_fu_220_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        grp_fu_214_p0 <= xm_1_fu_206_p2;
        grp_fu_214_p1 <= xm_1_fu_206_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_iter1_fsm_state5)) begin
        grp_fu_220_p0 <= add_i_fu_210_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (p_vld_fu_239_p1 == 1'd1) & (valid_load_load_fu_235_p1 == 1'd0) & (tmp_i_nbreadreq_fu_80_p3 == 1'd1))) begin
        mean <= bitcast_ln87_fu_247_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_214_ce == 1'b1)) begin
        pre_grp_fu_214_p2_reg <= pre_grp_fu_214_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_220_ce == 1'b1)) begin
        pre_grp_fu_220_p2_reg <= pre_grp_fu_220_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4) & (((valid_load_reg_370 == 1'd1) & (tmp_2_i_reg_381 == 1'd1)) | ((tmp_2_i_reg_381 == 1'd1) & (tmp_i_reg_374 == 1'd1))))) begin
        ret_reg_404 <= count[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & ((ap_sig_allocacmp_valid_load == 1'd1) | (tmp_i_nbreadreq_fu_80_p3 == 1'd1)))) begin
        tmp_2_i_reg_381 <= tmp_2_i_nbreadreq_fu_94_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4))) begin
        tmp_2_i_reg_381_pp0_iter0_reg <= tmp_2_i_reg_381;
        tmp_i_reg_374_pp0_iter0_reg <= tmp_i_reg_374;
        valid_flag_0_i_reg_122 <= ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_122;
        valid_load_reg_370_pp0_iter0_reg <= valid_load_reg_370;
        xm_1_reg_392_pp0_iter0_reg <= xm_1_reg_392;
        xm_reg_385_pp0_iter0_reg <= xm_reg_385;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (valid_load_load_fu_235_p1 == 1'd0))) begin
        tmp_i_reg_374 <= tmp_i_nbreadreq_fu_80_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        valid_load_reg_370 <= ap_sig_allocacmp_valid_load;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (((ap_sig_allocacmp_valid_load == 1'd1) & (tmp_2_i_nbreadreq_fu_94_p3 == 1'd1)) | ((tmp_2_i_nbreadreq_fu_94_p3 == 1'd1) & (tmp_i_nbreadreq_fu_80_p3 == 1'd1))))) begin
        xm_1_reg_392 <= xm_1_fu_206_p2;
        xm_reg_385 <= xm_fu_202_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter0_fsm_state2_blk = 1'b0;

assign ap_ST_iter0_fsm_state3_blk = 1'b0;

assign ap_ST_iter0_fsm_state4_blk = 1'b0;

assign ap_ST_iter1_fsm_state5_blk = 1'b0;

assign ap_ST_iter1_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) begin
        ap_ST_iter1_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((ret_reg_404_pp0_iter0_reg == 1'd0) & (valid_load_reg_370_pp0_iter0_reg == 1'd1) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1)) | ((ret_reg_404_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1) & (tmp_i_reg_374_pp0_iter0_reg == 1'd1)))) begin
        ap_phi_mux_valid_flag_1_i_phi_fu_140_p4 = valid_flag_0_i_reg_122;
    end else begin
        ap_phi_mux_valid_flag_1_i_phi_fu_140_p4 = ap_phi_reg_pp0_iter1_valid_flag_1_i_reg_136;
    end
end

always @ (*) begin
    if ((((valid_load_reg_370_pp0_iter0_reg == 1'd1) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1)) | ((tmp_2_i_reg_381_pp0_iter0_reg == 1'd1) & (tmp_i_reg_374_pp0_iter0_reg == 1'd1)))) begin
        ap_phi_mux_valid_flag_2_i_phi_fu_164_p6 = ap_phi_mux_valid_flag_1_i_phi_fu_140_p4;
    end else begin
        ap_phi_mux_valid_flag_2_i_phi_fu_164_p6 = ap_phi_reg_pp0_iter1_valid_flag_2_i_reg_160;
    end
end

always @ (*) begin
    if ((((ret_reg_404_pp0_iter0_reg == 1'd0) & (valid_load_reg_370_pp0_iter0_reg == 1'd1) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1)) | ((ret_reg_404_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1) & (tmp_i_reg_374_pp0_iter0_reg == 1'd1)))) begin
        ap_phi_mux_valid_new_1_i_phi_fu_152_p4 = 1'd1;
    end else begin
        ap_phi_mux_valid_new_1_i_phi_fu_152_p4 = ap_phi_reg_pp0_iter1_valid_new_1_i_reg_148;
    end
end

always @ (*) begin
    if ((((valid_load_reg_370_pp0_iter0_reg == 1'd1) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1)) | ((tmp_2_i_reg_381_pp0_iter0_reg == 1'd1) & (tmp_i_reg_374_pp0_iter0_reg == 1'd1)))) begin
        ap_phi_mux_valid_new_2_i_phi_fu_180_p6 = ap_phi_mux_valid_new_1_i_phi_fu_152_p4;
    end else begin
        ap_phi_mux_valid_new_2_i_phi_fu_180_p6 = ap_phi_reg_pp0_iter1_valid_new_2_i_reg_175;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (p_vld_fu_239_p1 == 1'd1) & (ap_start == 1'b1) & (valid_load_load_fu_235_p1 == 1'd0) & (tmp_i_nbreadreq_fu_80_p3 == 1'd1))) begin
        ap_sig_allocacmp_mean_load = bitcast_ln87_fu_247_p1;
    end else begin
        ap_sig_allocacmp_mean_load = mean;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state5) & (ap_phi_mux_valid_flag_2_i_phi_fu_164_p6 == 1'd1))) begin
        ap_sig_allocacmp_valid_load = ap_phi_mux_valid_new_2_i_phi_fu_180_p6;
    end else begin
        ap_sig_allocacmp_valid_load = valid;
    end
end

always @ (*) begin
    if ((grp_fu_214_ce == 1'b1)) begin
        grp_fu_214_p2 = pre_grp_fu_214_p2;
    end else begin
        grp_fu_214_p2 = pre_grp_fu_214_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_220_ce == 1'b1)) begin
        grp_fu_220_p2 = pre_grp_fu_220_p2;
    end else begin
        grp_fu_220_p2 = pre_grp_fu_220_p2_reg;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter1_fsm_state5) & (ap_done_reg == 1'b0)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        grp_fu_226_ce = 1'b1;
    end else begin
        grp_fu_226_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (valid_load_load_fu_235_p1 == 1'd0) & (tmp_i_nbreadreq_fu_80_p3 == 1'd1) & (mean_s_empty_n == 1'b1))) begin
        mean_s_read = 1'b1;
    end else begin
        mean_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1) & (((ap_sig_allocacmp_valid_load == 1'd1) & (tmp_2_i_nbreadreq_fu_94_p3 == 1'd1)) | ((tmp_2_i_nbreadreq_fu_94_p3 == 1'd1) & (tmp_i_nbreadreq_fu_80_p3 == 1'd1))))) begin
        stage1_s_blk_n = stage1_s_empty_n;
    end else begin
        stage1_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op41_read_state1 == 1'b1))) begin
        stage1_s_read = 1'b1;
    end else begin
        stage1_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op84_write_state7 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state7))) begin
        stage2_s_blk_n = stage2_s_full_n;
    end else begin
        stage2_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))) & (ap_predicate_op84_write_state7 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state7))) begin
        stage2_s_write = 1'b1;
    end else begin
        stage2_s_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op87_write_state7 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state7))) begin
        var_s_blk_n = var_s_full_n;
    end else begin
        var_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))) & (ap_predicate_op87_write_state7 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state7))) begin
        var_s_write = 1'b1;
    end else begin
        var_s_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state3;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end
        end
        ap_ST_iter0_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state4;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end
        end
        ap_ST_iter0_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state3;
            end
        end
        ap_ST_iter0_fsm_state4 : begin
            if (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)))))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state4;
            end
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state5 : begin
            if (((1'b1 == ap_CS_iter1_fsm_state5) & (ap_done_reg == 1'b0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state6;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state5;
            end
        end
        ap_ST_iter1_fsm_state6 : begin
            if (((1'b1 == ap_CS_iter1_fsm_state6) & (ap_done_reg == 1'b0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state7;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state6;
            end
        end
        ap_ST_iter1_fsm_state7 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state4))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state5;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b0 == ap_CS_iter0_fsm_state4))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state7;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state5;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln72_1_fu_321_p2 = (add_ln72_fu_315_p2 + count);

assign add_ln72_fu_315_p2 = ($signed(and_ln_fu_307_p3) + $signed(6'd63));

assign and_ln_fu_307_p3 = {{tmp_fu_299_p3}, {5'd0}};

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter0_fsm_state2 = ap_CS_iter0_fsm[32'd2];

assign ap_CS_iter0_fsm_state3 = ap_CS_iter0_fsm[32'd1];

assign ap_CS_iter0_fsm_state4 = ap_CS_iter0_fsm[32'd3];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state5 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter1_fsm_state6 = ap_CS_iter1_fsm[32'd2];

assign ap_CS_iter1_fsm_state7 = ap_CS_iter1_fsm[32'd3];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op41_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)));
end

assign ap_block_state2_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage2_iter1 = (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_104 = (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state7) & (((ap_predicate_op87_write_state7 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op84_write_state7 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4));
end

always @ (*) begin
    ap_condition_218 = (((valid_load_reg_370 == 1'd1) & (tmp_2_i_reg_381 == 1'd1) & (ret_fu_291_p3 == 1'd1)) | ((tmp_2_i_reg_381 == 1'd1) & (tmp_i_reg_374 == 1'd1) & (ret_fu_291_p3 == 1'd1)));
end

always @ (*) begin
    ap_condition_234 = (((tmp_2_i_reg_381 == 1'd0) & (tmp_i_reg_374 == 1'd1)) | ((valid_load_reg_370 == 1'd1) & (tmp_2_i_reg_381 == 1'd0)));
end

assign ap_phi_reg_pp0_iter0_sumq_new_0_i_reg_191 = 'bx;

assign ap_phi_reg_pp0_iter0_valid_flag_1_i_reg_136 = 'bx;

assign ap_phi_reg_pp0_iter0_valid_flag_2_i_reg_160 = 1'd0;

assign ap_phi_reg_pp0_iter0_valid_new_1_i_reg_148 = 'bx;

assign ap_phi_reg_pp0_iter0_valid_new_2_i_reg_175 = 'bx;

always @ (*) begin
    ap_predicate_op41_read_state1 = (((ap_sig_allocacmp_valid_load == 1'd1) & (tmp_2_i_nbreadreq_fu_94_p3 == 1'd1)) | ((tmp_2_i_nbreadreq_fu_94_p3 == 1'd1) & (tmp_i_nbreadreq_fu_80_p3 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op84_write_state7 = (((valid_load_reg_370_pp0_iter0_reg == 1'd1) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1)) | ((tmp_2_i_reg_381_pp0_iter0_reg == 1'd1) & (tmp_i_reg_374_pp0_iter0_reg == 1'd1)));
end

always @ (*) begin
    ap_predicate_op87_write_state7 = (((ret_reg_404 == 1'd1) & (valid_load_reg_370_pp0_iter0_reg == 1'd1) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1)) | ((ret_reg_404 == 1'd1) & (tmp_2_i_reg_381_pp0_iter0_reg == 1'd1) & (tmp_i_reg_374_pp0_iter0_reg == 1'd1)));
end

assign bitcast_ln103_1_fu_353_p1 = xm_1_reg_392_pp0_iter0_reg;

assign bitcast_ln103_fu_350_p1 = xm_reg_385_pp0_iter0_reg;

assign bitcast_ln87_fu_247_p1 = mean_s_dout;

assign grp_fu_220_p1 = 32'd1015021568;

assign mean_s_read_nbread_fu_88_p2_0 = mean_s_empty_n;

assign p_vld_fu_239_p1 = mean_s_read_nbread_fu_88_p2_0;

assign ret_fu_291_p3 = count[32'd5];

assign ret_reg_404_pp0_iter0_reg = ret_reg_404;

assign stage2_s_din = {{bitcast_ln103_1_fu_353_p1}, {bitcast_ln103_fu_350_p1}};

assign tmp_2_i_nbreadreq_fu_94_p3 = stage1_s_empty_n;

assign tmp_3_i6_fu_266_p4 = {{stage1_s_dout[63:32]}};

assign tmp_fu_299_p3 = count[32'd5];

assign tmp_i_nbreadreq_fu_80_p3 = mean_s_empty_n;

assign trunc_ln92_fu_257_p1 = stage1_s_dout[31:0];

assign valid_load_load_fu_235_p1 = ap_sig_allocacmp_valid_load;

assign var_s_din = grp_fu_220_p2;

assign xm_1_fu_206_p0 = tmp_3_i6_fu_266_p4;

assign xm_fu_202_p0 = trunc_ln92_fu_257_p1;

endmodule //layernorm_top_var_stage_64ul_float_float_float_2ul_s
