// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module OuterShuffle_hls_3_input_gen_1_12288u_1u_12288u_128u_8u_12u_1024u_8u_1u_vector_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src0_dout,
        src0_empty_n,
        src0_read,
        src0_num_data_valid,
        src0_fifo_cap,
        dst0_din,
        dst0_full_n,
        dst0_write,
        dst0_num_data_valid,
        dst0_fifo_cap
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [91:0] src0_dout;
input   src0_empty_n;
output   src0_read;
input  [2:0] src0_num_data_valid;
input  [2:0] src0_fifo_cap;
output  [91:0] dst0_din;
input   dst0_full_n;
output   dst0_write;
input  [2:0] dst0_num_data_valid;
input  [2:0] dst0_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
reg   [14:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp;
reg   [14:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_1;
reg   [14:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_2;
reg   [14:0] fp;
wire   [13:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_address0;
wire   [13:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_address1;
wire   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_q1;
wire   [13:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_address0;
wire   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_d0;
wire   [13:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_address1;
wire   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_q1;
wire   [13:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_address0;
wire   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_d0;
wire   [13:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_address1;
wire   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_q1;
wire   [13:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_address0;
wire   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_d0;
wire   [13:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_address1;
wire   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_q1;
reg   [0:0] ovld;
reg   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_0;
reg   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_1;
reg   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_2;
reg   [22:0] void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_3;
reg   [14:0] rp;
reg   [3:0] nest_inner_inner_inner_cnt;
reg   [4:0] nest_inner_inner_cnt;
reg   [7:0] nest_inner_cnt;
wire   [0:0] ovld_load_load_fu_509_p1;
reg   [0:0] ovld_load_reg_859;
wire   [0:0] tmp_s_nbwrite_fu_142_p3;
reg   [0:0] tmp_s_reg_863;
reg   [0:0] ap_phi_mux_ovld_flag_0_phi_fu_252_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_ovld_flag_0_reg_249;
reg   [0:0] ap_phi_mux_ovld_new_0_phi_fu_263_p4;
wire   [0:0] xor_ln218_fu_546_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_ovld_new_0_reg_260;
reg  signed [2:0] ap_phi_mux_term_2_phi_fu_273_p4;
wire   [2:0] term_1_fu_669_p3;
wire  signed [2:0] ap_phi_reg_pp0_iter0_term_2_reg_270;
wire   [0:0] tmp_1_fu_592_p3;
wire   [0:0] tmp_2_fu_604_p3;
wire   [2:0] select_ln137_fu_632_p3;
reg   [3:0] ap_phi_mux_fp_inc_2_phi_fu_282_p4;
wire   [3:0] fp_inc_fu_678_p3;
wire   [3:0] ap_phi_reg_pp0_iter0_fp_inc_2_reg_279;
reg   [14:0] ap_phi_mux_rp_inc_2_phi_fu_292_p4;
wire   [14:0] rp_inc_fu_687_p3;
wire   [14:0] ap_phi_reg_pp0_iter0_rp_inc_2_reg_289;
reg   [3:0] ap_phi_mux_term_4_phi_fu_302_p6;
wire  signed [3:0] sext_ln135_fu_716_p1;
wire   [3:0] ap_phi_reg_pp0_iter0_term_4_reg_299;
wire   [0:0] tmp_5_fu_722_p3;
wire   [0:0] tmp_6_fu_734_p3;
wire   [3:0] term_3_fu_742_p4;
reg   [13:0] ap_phi_mux_fp_inc_4_phi_fu_313_p6;
wire   [13:0] ap_phi_reg_pp0_iter0_fp_inc_4_reg_310;
wire   [13:0] zext_ln133_fu_710_p1;
reg   [14:0] ap_phi_mux_rp_inc_4_phi_fu_325_p6;
wire   [14:0] ap_phi_reg_pp0_iter0_rp_inc_4_reg_322;
reg   [0:0] ap_phi_mux_ovld_flag_2_phi_fu_339_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_ovld_flag_2_reg_336;
reg   [0:0] ap_phi_mux_ovld_new_2_phi_fu_353_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_ovld_new_2_reg_350;
wire   [63:0] zext_ln214_fu_469_p1;
wire   [0:0] tmp_fu_397_p3;
wire   [63:0] zext_ln222_fu_562_p1;
wire   [14:0] add_ln214_fu_453_p2;
wire   [14:0] add_ln227_fu_811_p2;
reg   [22:0] ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_0_load;
reg   [22:0] ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_1_load;
reg   [22:0] ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_2_load;
reg   [22:0] ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_3_load;
wire   [14:0] add_ln226_fu_787_p2;
wire   [3:0] select_ln138_fu_618_p3;
wire   [4:0] storemerge_fu_696_p3;
wire   [7:0] add_ln145_2_fu_753_p2;
wire   [0:0] src0_read_nbread_fu_136_p2_0;
reg    src0_read_local;
wire   [91:0] p_0_fu_529_p5;
reg    dst0_write_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_we0_local;
wire   [22:0] trunc_ln214_fu_415_p1;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_ce0_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_ce1_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_we0_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_ce0_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_ce1_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_we0_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_ce0_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_ce1_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_we0_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_ce0_local;
reg    void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_ce1_local;
wire   [14:0] sub_ln212_fu_391_p2;
wire   [13:0] trunc_ln214_3_fu_465_p1;
wire   [0:0] xor_ln218_fu_546_p0;
wire   [13:0] trunc_ln222_fu_558_p1;
wire   [14:0] sub_ln224_fu_586_p2;
wire   [3:0] add_ln145_fu_612_p2;
wire   [0:0] tmp_3_fu_645_p3;
wire   [2:0] term_fu_653_p4;
wire   [4:0] add_ln145_1_fu_663_p2;
wire   [0:0] tmp_8_fu_771_p3;
wire   [14:0] select_ln226_fu_779_p3;
wire   [13:0] select_ln227_fu_799_p3;
wire   [14:0] zext_ln227_fu_807_p1;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0;
reg    ap_predicate_op51_store_state1;
reg    ap_enable_operation_51;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op81_load_state1;
reg    ap_enable_operation_81;
reg    ap_predicate_op144_load_state2;
reg    ap_enable_operation_144;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op54_store_state1;
reg    ap_enable_operation_54;
reg    ap_predicate_op84_load_state1;
reg    ap_enable_operation_84;
reg    ap_predicate_op145_load_state2;
reg    ap_enable_operation_145;
reg    ap_predicate_op57_store_state1;
reg    ap_enable_operation_57;
reg    ap_predicate_op87_load_state1;
reg    ap_enable_operation_87;
reg    ap_predicate_op146_load_state2;
reg    ap_enable_operation_146;
reg    ap_predicate_op60_store_state1;
reg    ap_enable_operation_60;
reg    ap_predicate_op90_load_state1;
reg    ap_enable_operation_90;
reg    ap_predicate_op147_load_state2;
reg    ap_enable_operation_147;
reg    ap_condition_220;
reg    ap_condition_214;
reg    ap_condition_43;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp = 15'd0;
#0 void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_1 = 15'd0;
#0 void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_2 = 15'd0;
#0 fp = 15'd0;
#0 ovld = 1'd0;
#0 void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_0 = 23'd0;
#0 void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_1 = 23'd0;
#0 void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_2 = 23'd0;
#0 void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_3 = 23'd0;
#0 rp = 15'd0;
#0 nest_inner_inner_inner_cnt = 4'd6;
#0 nest_inner_inner_cnt = 5'd10;
#0 nest_inner_cnt = 8'd126;
end

OuterShuffle_hls_3_input_gen_1_12288u_1u_12288u_128u_8u_12u_1024u_8u_1u_vector_s_void_input_gen_bkb #(
    .DataWidth( 23 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_address0),
    .ce0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_ce0_local),
    .we0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_we0_local),
    .d0(trunc_ln214_fu_415_p1),
    .address1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_address1),
    .ce1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_ce1_local),
    .q1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_q1)
);

OuterShuffle_hls_3_input_gen_1_12288u_1u_12288u_128u_8u_12u_1024u_8u_1u_vector_s_void_input_gen_bkb #(
    .DataWidth( 23 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_address0),
    .ce0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_ce0_local),
    .we0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_we0_local),
    .d0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_d0),
    .address1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_address1),
    .ce1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_ce1_local),
    .q1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_q1)
);

OuterShuffle_hls_3_input_gen_1_12288u_1u_12288u_128u_8u_12u_1024u_8u_1u_vector_s_void_input_gen_bkb #(
    .DataWidth( 23 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_address0),
    .ce0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_ce0_local),
    .we0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_we0_local),
    .d0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_d0),
    .address1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_address1),
    .ce1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_ce1_local),
    .q1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_q1)
);

OuterShuffle_hls_3_input_gen_1_12288u_1u_12288u_128u_8u_12u_1024u_8u_1u_vector_s_void_input_gen_bkb #(
    .DataWidth( 23 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_address0),
    .ce0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_ce0_local),
    .we0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_we0_local),
    .d0(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_d0),
    .address1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_address1),
    .ce1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_ce1_local),
    .q1(void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_done_reg == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fp <= 15'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (((tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1))))) begin
            fp <= add_ln227_fu_811_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        nest_inner_cnt <= 8'd126;
    end else begin
        if ((1'b1 == ap_condition_43)) begin
            if ((1'b1 == ap_condition_214)) begin
                nest_inner_cnt <= 8'd126;
            end else if ((1'b1 == ap_condition_220)) begin
                nest_inner_cnt <= add_ln145_2_fu_753_p2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        nest_inner_inner_cnt <= 5'd10;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (((tmp_2_fu_604_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_2_fu_604_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1))))) begin
            nest_inner_inner_cnt <= storemerge_fu_696_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        nest_inner_inner_inner_cnt <= 4'd6;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (((tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1))))) begin
            nest_inner_inner_inner_cnt <= select_ln138_fu_618_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ovld <= 1'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_phi_mux_ovld_flag_2_phi_fu_339_p6 == 1'd1))) begin
            ovld <= ap_phi_mux_ovld_new_2_phi_fu_353_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        rp <= 15'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (((tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1))))) begin
            rp <= add_ln226_fu_787_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp <= 15'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
            void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp <= void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_1 <= 15'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
            void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_1 <= void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_2 <= 15'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0))) begin
            void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_2 <= add_ln214_fu_453_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ovld_load_reg_859 <= ovld;
        tmp_s_reg_863 <= dst0_full_n;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_done_reg == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2) & ((tmp_s_reg_863 == 1'd1) | (ovld_load_reg_859 == 1'd0)))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_0 <= void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_q1;
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_1 <= void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_q1;
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_2 <= void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_q1;
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_3 <= void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_q1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_fu_604_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_2_fu_604_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_fp_inc_2_phi_fu_282_p4 = 4'd0;
    end else if ((((tmp_2_fu_604_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_2_fu_604_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_fp_inc_2_phi_fu_282_p4 = fp_inc_fu_678_p3;
    end else begin
        ap_phi_mux_fp_inc_2_phi_fu_282_p4 = ap_phi_reg_pp0_iter0_fp_inc_2_reg_279;
    end
end

always @ (*) begin
    if ((((tmp_5_fu_722_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_5_fu_722_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)) | ((tmp_6_fu_734_p3 == 1'd0) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_6_fu_734_p3 == 1'd0) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_fp_inc_4_phi_fu_313_p6 = zext_ln133_fu_710_p1;
    end else if ((((tmp_6_fu_734_p3 == 1'd1) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_6_fu_734_p3 == 1'd1) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_fp_inc_4_phi_fu_313_p6 = 14'd11272;
    end else begin
        ap_phi_mux_fp_inc_4_phi_fu_313_p6 = ap_phi_reg_pp0_iter0_fp_inc_4_reg_310;
    end
end

always @ (*) begin
    if ((ovld == 1'd0)) begin
        ap_phi_mux_ovld_flag_0_phi_fu_252_p4 = 1'd0;
    end else if (((tmp_s_nbwrite_fu_142_p3 == 1'd1) & (ovld_load_load_fu_509_p1 == 1'd1))) begin
        ap_phi_mux_ovld_flag_0_phi_fu_252_p4 = 1'd1;
    end else begin
        ap_phi_mux_ovld_flag_0_phi_fu_252_p4 = ap_phi_reg_pp0_iter0_ovld_flag_0_reg_249;
    end
end

always @ (*) begin
    if ((((tmp_1_fu_592_p3 == 1'd0) & (ovld == 1'd0)) | ((tmp_1_fu_592_p3 == 1'd0) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_ovld_flag_2_phi_fu_339_p6 = ap_phi_mux_ovld_flag_0_phi_fu_252_p4;
    end else if ((((tmp_s_nbwrite_fu_142_p3 == 1'd0) & (ovld_load_load_fu_509_p1 == 1'd1)) | ((tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_ovld_flag_2_phi_fu_339_p6 = 1'd1;
    end else begin
        ap_phi_mux_ovld_flag_2_phi_fu_339_p6 = ap_phi_reg_pp0_iter0_ovld_flag_2_reg_336;
    end
end

always @ (*) begin
    if (((tmp_s_nbwrite_fu_142_p3 == 1'd1) & (ovld_load_load_fu_509_p1 == 1'd1))) begin
        ap_phi_mux_ovld_new_0_phi_fu_263_p4 = xor_ln218_fu_546_p2;
    end else begin
        ap_phi_mux_ovld_new_0_phi_fu_263_p4 = ap_phi_reg_pp0_iter0_ovld_new_0_reg_260;
    end
end

always @ (*) begin
    if ((((tmp_1_fu_592_p3 == 1'd0) & (ovld == 1'd0)) | ((tmp_1_fu_592_p3 == 1'd0) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_ovld_new_2_phi_fu_353_p6 = ap_phi_mux_ovld_new_0_phi_fu_263_p4;
    end else if ((((tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_ovld_new_2_phi_fu_353_p6 = 1'd1;
    end else if (((tmp_s_nbwrite_fu_142_p3 == 1'd0) & (ovld_load_load_fu_509_p1 == 1'd1))) begin
        ap_phi_mux_ovld_new_2_phi_fu_353_p6 = xor_ln218_fu_546_p2;
    end else begin
        ap_phi_mux_ovld_new_2_phi_fu_353_p6 = ap_phi_reg_pp0_iter0_ovld_new_2_reg_350;
    end
end

always @ (*) begin
    if ((((tmp_2_fu_604_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_2_fu_604_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_rp_inc_2_phi_fu_292_p4 = 15'd1;
    end else if ((((tmp_2_fu_604_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_2_fu_604_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_rp_inc_2_phi_fu_292_p4 = rp_inc_fu_687_p3;
    end else begin
        ap_phi_mux_rp_inc_2_phi_fu_292_p4 = ap_phi_reg_pp0_iter0_rp_inc_2_reg_289;
    end
end

always @ (*) begin
    if ((((tmp_5_fu_722_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_5_fu_722_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)) | ((tmp_6_fu_734_p3 == 1'd0) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_6_fu_734_p3 == 1'd0) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_rp_inc_4_phi_fu_325_p6 = ap_phi_mux_rp_inc_2_phi_fu_292_p4;
    end else if ((((tmp_6_fu_734_p3 == 1'd1) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_6_fu_734_p3 == 1'd1) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_rp_inc_4_phi_fu_325_p6 = 15'd1;
    end else begin
        ap_phi_mux_rp_inc_4_phi_fu_325_p6 = ap_phi_reg_pp0_iter0_rp_inc_4_reg_322;
    end
end

always @ (*) begin
    if ((((tmp_2_fu_604_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_2_fu_604_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_term_2_phi_fu_273_p4 = select_ln137_fu_632_p3;
    end else if ((((tmp_2_fu_604_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_2_fu_604_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_term_2_phi_fu_273_p4 = term_1_fu_669_p3;
    end else begin
        ap_phi_mux_term_2_phi_fu_273_p4 = ap_phi_reg_pp0_iter0_term_2_reg_270;
    end
end

always @ (*) begin
    if ((((tmp_6_fu_734_p3 == 1'd0) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_6_fu_734_p3 == 1'd0) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_term_4_phi_fu_302_p6 = term_3_fu_742_p4;
    end else if ((((tmp_5_fu_722_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_5_fu_722_p3 == 1'd0) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)) | ((tmp_6_fu_734_p3 == 1'd1) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_6_fu_734_p3 == 1'd1) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)))) begin
        ap_phi_mux_term_4_phi_fu_302_p6 = sext_ln135_fu_716_p1;
    end else begin
        ap_phi_mux_term_4_phi_fu_302_p6 = ap_phi_reg_pp0_iter0_term_4_reg_299;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & ((tmp_s_reg_863 == 1'd1) | (ovld_load_reg_859 == 1'd0)))) begin
        ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_0_load = void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_q1;
    end else begin
        ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_0_load = void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & ((tmp_s_reg_863 == 1'd1) | (ovld_load_reg_859 == 1'd0)))) begin
        ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_1_load = void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_q1;
    end else begin
        ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_1_load = void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & ((tmp_s_reg_863 == 1'd1) | (ovld_load_reg_859 == 1'd0)))) begin
        ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_2_load = void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_q1;
    end else begin
        ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_2_load = void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & ((tmp_s_reg_863 == 1'd1) | (ovld_load_reg_859 == 1'd0)))) begin
        ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_3_load = void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_q1;
    end else begin
        ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_3_load = void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_3;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (dst0_full_n == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ovld_load_load_fu_509_p1 == 1'd1))) begin
        dst0_write_local = 1'b1;
    end else begin
        dst0_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (src0_empty_n == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (tmp_fu_397_p3 == 1'd0))) begin
        src0_read_local = 1'b1;
    end else begin
        src0_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_ce0_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & ((tmp_s_nbwrite_fu_142_p3 == 1'd1) | (ovld == 1'd0)))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_ce1_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_we0_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_ce0_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & ((tmp_s_nbwrite_fu_142_p3 == 1'd1) | (ovld == 1'd0)))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_ce1_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_we0_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_ce0_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & ((tmp_s_nbwrite_fu_142_p3 == 1'd1) | (ovld == 1'd0)))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_ce1_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_we0_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_ce0_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & ((tmp_s_nbwrite_fu_142_p3 == 1'd1) | (ovld == 1'd0)))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_ce1_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1) & (src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0))) begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_we0_local = 1'b1;
    end else begin
        void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (ap_done_reg == 1'b0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if (((ap_done_reg == 1'b0) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln145_1_fu_663_p2 = ($signed(nest_inner_inner_cnt) + $signed(5'd31));

assign add_ln145_2_fu_753_p2 = ($signed(nest_inner_cnt) + $signed(8'd255));

assign add_ln145_fu_612_p2 = ($signed(nest_inner_inner_inner_cnt) + $signed(4'd15));

assign add_ln214_fu_453_p2 = (void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_2 + 15'd1);

assign add_ln226_fu_787_p2 = (rp + select_ln226_fu_779_p3);

assign add_ln227_fu_811_p2 = (fp + zext_ln227_fu_807_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_iter0_fsm_state1 == ap_CS_iter0_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_condition_214 = (((tmp_6_fu_734_p3 == 1'd1) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_6_fu_734_p3 == 1'd1) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)));
end

always @ (*) begin
    ap_condition_220 = (((tmp_6_fu_734_p3 == 1'd0) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (ovld == 1'd0)) | ((tmp_6_fu_734_p3 == 1'd0) & (tmp_5_fu_722_p3 == 1'd1) & (tmp_1_fu_592_p3 == 1'd1) & (tmp_s_nbwrite_fu_142_p3 == 1'd1)));
end

always @ (*) begin
    ap_condition_43 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0)) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_enable_operation_144 = (ap_predicate_op144_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_145 = (ap_predicate_op145_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_146 = (ap_predicate_op146_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_147 = (ap_predicate_op147_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_51 = (ap_predicate_op51_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_54 = (ap_predicate_op54_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_57 = (ap_predicate_op57_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_60 = (ap_predicate_op60_store_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_81 = (ap_predicate_op81_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_84 = (ap_predicate_op84_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_87 = (ap_predicate_op87_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_90 = (ap_predicate_op90_load_state1 == 1'b1);
end

assign ap_enable_reg_pp0_iter0 = 1'b0;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2));
end

assign ap_phi_reg_pp0_iter0_fp_inc_2_reg_279 = 'bx;

assign ap_phi_reg_pp0_iter0_fp_inc_4_reg_310 = 'bx;

assign ap_phi_reg_pp0_iter0_ovld_flag_0_reg_249 = 'bx;

assign ap_phi_reg_pp0_iter0_ovld_flag_2_reg_336 = 'bx;

assign ap_phi_reg_pp0_iter0_ovld_new_0_reg_260 = 'bx;

assign ap_phi_reg_pp0_iter0_ovld_new_2_reg_350 = 'bx;

assign ap_phi_reg_pp0_iter0_rp_inc_2_reg_289 = 'bx;

assign ap_phi_reg_pp0_iter0_rp_inc_4_reg_322 = 'bx;

assign ap_phi_reg_pp0_iter0_term_2_reg_270 = 'bx;

assign ap_phi_reg_pp0_iter0_term_4_reg_299 = 'bx;

always @ (*) begin
    ap_predicate_op144_load_state2 = ((tmp_s_reg_863 == 1'd1) | (ovld_load_reg_859 == 1'd0));
end

always @ (*) begin
    ap_predicate_op145_load_state2 = ((tmp_s_reg_863 == 1'd1) | (ovld_load_reg_859 == 1'd0));
end

always @ (*) begin
    ap_predicate_op146_load_state2 = ((tmp_s_reg_863 == 1'd1) | (ovld_load_reg_859 == 1'd0));
end

always @ (*) begin
    ap_predicate_op147_load_state2 = ((tmp_s_reg_863 == 1'd1) | (ovld_load_reg_859 == 1'd0));
end

always @ (*) begin
    ap_predicate_op51_store_state1 = ((src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op54_store_state1 = ((src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op57_store_state1 = ((src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op60_store_state1 = ((src0_read_nbread_fu_136_p2_0 == 1'd1) & (tmp_fu_397_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op81_load_state1 = ((tmp_s_nbwrite_fu_142_p3 == 1'd1) | (ovld == 1'd0));
end

always @ (*) begin
    ap_predicate_op84_load_state1 = ((tmp_s_nbwrite_fu_142_p3 == 1'd1) | (ovld == 1'd0));
end

always @ (*) begin
    ap_predicate_op87_load_state1 = ((tmp_s_nbwrite_fu_142_p3 == 1'd1) | (ovld == 1'd0));
end

always @ (*) begin
    ap_predicate_op90_load_state1 = ((tmp_s_nbwrite_fu_142_p3 == 1'd1) | (ovld == 1'd0));
end

assign dst0_din = p_0_fu_529_p5;

assign dst0_write = dst0_write_local;

assign fp_inc_fu_678_p3 = ((tmp_3_fu_645_p3[0:0] == 1'b1) ? 4'd8 : 4'd0);

assign ovld_load_load_fu_509_p1 = ovld;

assign p_0_fu_529_p5 = {{{{ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_3_load}, {ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_2_load}}, {ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_1_load}}, {ap_sig_allocacmp_void_input_gen_stream_vector_0_stream_conditional_1_type_0_obuf_2_0_load}};

assign rp_inc_fu_687_p3 = ((tmp_3_fu_645_p3[0:0] == 1'b1) ? 15'd21505 : 15'd1017);

assign select_ln137_fu_632_p3 = ((tmp_2_fu_604_p3[0:0] == 1'b1) ? 3'd7 : 3'd1);

assign select_ln138_fu_618_p3 = ((tmp_2_fu_604_p3[0:0] == 1'b1) ? 4'd6 : add_ln145_fu_612_p2);

assign select_ln226_fu_779_p3 = ((tmp_8_fu_771_p3[0:0] == 1'b1) ? 15'd1 : ap_phi_mux_rp_inc_4_phi_fu_325_p6);

assign select_ln227_fu_799_p3 = ((tmp_8_fu_771_p3[0:0] == 1'b1) ? 14'd11272 : ap_phi_mux_fp_inc_4_phi_fu_313_p6);

assign sext_ln135_fu_716_p1 = ap_phi_mux_term_2_phi_fu_273_p4;

assign src0_read = src0_read_local;

assign src0_read_nbread_fu_136_p2_0 = src0_empty_n;

assign storemerge_fu_696_p3 = ((tmp_3_fu_645_p3[0:0] == 1'b1) ? 5'd10 : add_ln145_1_fu_663_p2);

assign sub_ln212_fu_391_p2 = (void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_2 - fp);

assign sub_ln224_fu_586_p2 = (rp - void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp);

assign term_1_fu_669_p3 = ((tmp_3_fu_645_p3[0:0] == 1'b1) ? select_ln137_fu_632_p3 : term_fu_653_p4);

assign term_3_fu_742_p4 = {|(1'd0), sext_ln135_fu_716_p1[3 - 1:0]};

assign term_fu_653_p4 = {|(1'd0), select_ln137_fu_632_p3[2 - 1:0]};

assign tmp_1_fu_592_p3 = sub_ln224_fu_586_p2[32'd14];

assign tmp_2_fu_604_p3 = nest_inner_inner_inner_cnt[32'd3];

assign tmp_3_fu_645_p3 = nest_inner_inner_cnt[32'd4];

assign tmp_5_fu_722_p3 = ap_phi_mux_term_2_phi_fu_273_p4[32'd2];

assign tmp_6_fu_734_p3 = nest_inner_cnt[32'd7];

assign tmp_8_fu_771_p3 = ap_phi_mux_term_4_phi_fu_302_p6[32'd3];

assign tmp_fu_397_p3 = sub_ln212_fu_391_p2[32'd14];

assign tmp_s_nbwrite_fu_142_p3 = dst0_full_n;

assign trunc_ln214_3_fu_465_p1 = void_input_gen_stream_vector_0_stream_conditional_1_type_0_wp_2[13:0];

assign trunc_ln214_fu_415_p1 = src0_dout[22:0];

assign trunc_ln222_fu_558_p1 = rp[13:0];

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_address0 = zext_ln214_fu_469_p1;

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_address1 = zext_ln222_fu_562_p1;

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_1_d0 = {{src0_dout[68:46]}};

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_address0 = zext_ln214_fu_469_p1;

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_address1 = zext_ln222_fu_562_p1;

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_2_d0 = {{src0_dout[45:23]}};

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_address0 = zext_ln214_fu_469_p1;

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_3_address1 = zext_ln222_fu_562_p1;

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_address0 = zext_ln214_fu_469_p1;

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_address1 = zext_ln222_fu_562_p1;

assign void_input_gen_stream_vector_0_stream_conditional_1_type_0_buf_d0 = {{src0_dout[91:69]}};

assign xor_ln218_fu_546_p0 = dst0_full_n;

assign xor_ln218_fu_546_p2 = (xor_ln218_fu_546_p0 ^ 1'd1);

assign zext_ln133_fu_710_p1 = ap_phi_mux_fp_inc_2_phi_fu_282_p4;

assign zext_ln214_fu_469_p1 = trunc_ln214_3_fu_465_p1;

assign zext_ln222_fu_562_p1 = trunc_ln222_fu_558_p1;

assign zext_ln227_fu_807_p1 = select_ln227_fu_799_p3;

always @ (posedge ap_clk) begin
    ap_enable_reg_pp0_iter1 <= 1'b0;
end

endmodule //OuterShuffle_hls_3_input_gen_1_12288u_1u_12288u_128u_8u_12u_1024u_8u_1u_vector_s
