// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module softmax_top_max_extract (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_TVALID,
        sm_inst_max2exp_dat_din,
        sm_inst_max2exp_dat_num_data_valid,
        sm_inst_max2exp_dat_fifo_cap,
        sm_inst_max2exp_dat_full_n,
        sm_inst_max2exp_dat_write,
        sm_inst_max2exp_max_din,
        sm_inst_max2exp_max_num_data_valid,
        sm_inst_max2exp_max_fifo_cap,
        sm_inst_max2exp_max_full_n,
        sm_inst_max2exp_max_write,
        src_TDATA,
        src_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   src_TVALID;
output  [31:0] sm_inst_max2exp_dat_din;
input  [6:0] sm_inst_max2exp_dat_num_data_valid;
input  [6:0] sm_inst_max2exp_dat_fifo_cap;
input   sm_inst_max2exp_dat_full_n;
output   sm_inst_max2exp_dat_write;
output  [31:0] sm_inst_max2exp_max_din;
input  [1:0] sm_inst_max2exp_max_num_data_valid;
input  [1:0] sm_inst_max2exp_max_fifo_cap;
input   sm_inst_max2exp_max_full_n;
output   sm_inst_max2exp_max_write;
input  [31:0] src_TDATA;
output   src_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg sm_inst_max2exp_dat_write;
reg sm_inst_max2exp_max_write;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire   [0:0] tmp_i_nbreadreq_fu_58_p3;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] tmp_i_reg_255;
reg   [0:0] ret_reg_269;
reg    ap_predicate_op47_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [31:0] sm_inst_max_val;
reg   [6:0] sm_inst_max_cnt;
reg    src_TDATA_blk_n;
reg    sm_inst_max2exp_dat_blk_n;
reg    sm_inst_max2exp_max_blk_n;
reg   [31:0] src_read_reg_259;
wire   [31:0] select_ln147_fu_190_p3;
reg   [31:0] select_ln147_reg_264;
wire   [0:0] ret_fu_203_p3;
reg   [31:0] ap_phi_mux_sm_inst_max_val_new_0_i_phi_fu_89_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_sm_inst_max_val_new_0_i_reg_86;
wire   [6:0] add_ln96_1_fu_233_p2;
wire   [31:0] bitcast_ln146_fu_100_p1;
wire   [31:0] bitcast_ln224_fu_110_p1;
wire   [7:0] tmp_1_fu_114_p4;
wire   [22:0] trunc_ln224_fu_124_p1;
wire   [0:0] icmp_ln224_1_fu_148_p2;
wire   [0:0] icmp_ln224_fu_142_p2;
wire   [7:0] tmp_2_fu_128_p4;
wire   [22:0] trunc_ln224_1_fu_138_p1;
wire   [0:0] icmp_ln224_3_fu_166_p2;
wire   [0:0] icmp_ln224_2_fu_160_p2;
wire   [0:0] or_ln224_fu_154_p2;
wire   [0:0] or_ln224_1_fu_172_p2;
wire   [0:0] and_ln224_fu_178_p2;
wire   [0:0] tmp_3_fu_96_p2;
wire   [0:0] and_ln224_1_fu_184_p2;
wire   [0:0] tmp_fu_211_p3;
wire   [6:0] and_ln_fu_219_p3;
wire   [6:0] add_ln96_fu_227_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
wire    regslice_both_src_U_apdone_blk;
wire   [31:0] src_TDATA_int_regslice;
wire    src_TVALID_int_regslice;
reg    src_TREADY_int_regslice;
wire    regslice_both_src_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 sm_inst_max_val = 32'd4286578687;
#0 sm_inst_max_cnt = 7'd62;
end

softmax_top_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U1(
    .din0(sm_inst_max_val),
    .din1(bitcast_ln146_fu_100_p1),
    .opcode(5'd4),
    .dout(tmp_3_fu_96_p2)
);

softmax_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_src_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(src_TDATA),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_U_ack_in),
    .data_out(src_TDATA_int_regslice),
    .vld_out(src_TVALID_int_regslice),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0)))) | ((tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0))) & (tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ret_reg_269 <= sm_inst_max_cnt[32'd6];
        select_ln147_reg_264 <= select_ln147_fu_190_p3;
        sm_inst_max_cnt <= add_ln96_1_fu_233_p2;
        sm_inst_max_val <= ap_phi_mux_sm_inst_max_val_new_0_i_phi_fu_89_p4;
        src_read_reg_259 <= src_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0)))) | ((tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_i_reg_255 <= tmp_i_nbreadreq_fu_58_p3;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_i_nbreadreq_fu_58_p3 == 1'd1)) begin
        if ((ret_fu_203_p3 == 1'd0)) begin
            ap_phi_mux_sm_inst_max_val_new_0_i_phi_fu_89_p4 = select_ln147_fu_190_p3;
        end else if ((ret_fu_203_p3 == 1'd1)) begin
            ap_phi_mux_sm_inst_max_val_new_0_i_phi_fu_89_p4 = 32'd4286578687;
        end else begin
            ap_phi_mux_sm_inst_max_val_new_0_i_phi_fu_89_p4 = ap_phi_reg_pp0_iter0_sm_inst_max_val_new_0_i_reg_86;
        end
    end else begin
        ap_phi_mux_sm_inst_max_val_new_0_i_phi_fu_89_p4 = ap_phi_reg_pp0_iter0_sm_inst_max_val_new_0_i_reg_86;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0)))) | ((tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_255 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        sm_inst_max2exp_dat_blk_n = sm_inst_max2exp_dat_full_n;
    end else begin
        sm_inst_max2exp_dat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (tmp_i_reg_255 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        sm_inst_max2exp_dat_write = 1'b1;
    end else begin
        sm_inst_max2exp_dat_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op47_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        sm_inst_max2exp_max_blk_n = sm_inst_max2exp_max_full_n;
    end else begin
        sm_inst_max2exp_max_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (ap_predicate_op47_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        sm_inst_max2exp_max_write = 1'b1;
    end else begin
        sm_inst_max2exp_max_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        src_TDATA_blk_n = src_TVALID_int_regslice;
    end else begin
        src_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0)))) | ((tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0))) & (tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        src_TREADY_int_regslice = 1'b1;
    end else begin
        src_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0))) & ~((ap_done_reg == 1'b1) | ((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0)))) | ((tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln96_1_fu_233_p2 = (add_ln96_fu_227_p2 + sm_inst_max_cnt);

assign add_ln96_fu_227_p2 = ($signed(and_ln_fu_219_p3) + $signed(7'd127));

assign and_ln224_1_fu_184_p2 = (tmp_3_fu_96_p2 & and_ln224_fu_178_p2);

assign and_ln224_fu_178_p2 = (or_ln224_fu_154_p2 & or_ln224_1_fu_172_p2);

assign and_ln_fu_219_p3 = {{tmp_fu_211_p3}, {6'd0}};

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_i_nbreadreq_fu_58_p3 == 1'd1) & (src_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ap_predicate_op47_write_state2 == 1'b1) & (sm_inst_max2exp_max_full_n == 1'b0)) | ((tmp_i_reg_255 == 1'd1) & (sm_inst_max2exp_dat_full_n == 1'b0)));
end

assign ap_phi_reg_pp0_iter0_sm_inst_max_val_new_0_i_reg_86 = 'bx;

always @ (*) begin
    ap_predicate_op47_write_state2 = ((ret_reg_269 == 1'd1) & (tmp_i_reg_255 == 1'd1));
end

assign bitcast_ln146_fu_100_p1 = src_TDATA_int_regslice;

assign bitcast_ln224_fu_110_p1 = sm_inst_max_val;

assign icmp_ln224_1_fu_148_p2 = ((trunc_ln224_fu_124_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_2_fu_160_p2 = ((tmp_2_fu_128_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln224_3_fu_166_p2 = ((trunc_ln224_1_fu_138_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_142_p2 = ((tmp_1_fu_114_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln224_1_fu_172_p2 = (icmp_ln224_3_fu_166_p2 | icmp_ln224_2_fu_160_p2);

assign or_ln224_fu_154_p2 = (icmp_ln224_fu_142_p2 | icmp_ln224_1_fu_148_p2);

assign ret_fu_203_p3 = sm_inst_max_cnt[32'd6];

assign select_ln147_fu_190_p3 = ((and_ln224_1_fu_184_p2[0:0] == 1'b1) ? bitcast_ln146_fu_100_p1 : sm_inst_max_val);

assign sm_inst_max2exp_dat_din = src_read_reg_259;

assign sm_inst_max2exp_max_din = select_ln147_reg_264;

assign src_TREADY = regslice_both_src_U_ack_in;

assign tmp_1_fu_114_p4 = {{bitcast_ln224_fu_110_p1[30:23]}};

assign tmp_2_fu_128_p4 = {{src_TDATA_int_regslice[30:23]}};

assign tmp_fu_211_p3 = sm_inst_max_cnt[32'd6];

assign tmp_i_nbreadreq_fu_58_p3 = src_TVALID_int_regslice;

assign trunc_ln224_1_fu_138_p1 = src_TDATA_int_regslice[22:0];

assign trunc_ln224_fu_124_p1 = bitcast_ln224_fu_110_p1[22:0];

endmodule //softmax_top_max_extract
