// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module softmax_top_exponentiate (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        sm_inst_max2exp_max_dout,
        sm_inst_max2exp_max_num_data_valid,
        sm_inst_max2exp_max_fifo_cap,
        sm_inst_max2exp_max_empty_n,
        sm_inst_max2exp_max_read,
        sm_inst_max2exp_dat_dout,
        sm_inst_max2exp_dat_num_data_valid,
        sm_inst_max2exp_dat_fifo_cap,
        sm_inst_max2exp_dat_empty_n,
        sm_inst_max2exp_dat_read,
        sm_inst_exp2div_dat_din,
        sm_inst_exp2div_dat_num_data_valid,
        sm_inst_exp2div_dat_fifo_cap,
        sm_inst_exp2div_dat_full_n,
        sm_inst_exp2div_dat_write,
        sm_inst_exp2div_sum_din,
        sm_inst_exp2div_sum_num_data_valid,
        sm_inst_exp2div_sum_fifo_cap,
        sm_inst_exp2div_sum_full_n,
        sm_inst_exp2div_sum_write
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter6_fsm_state7 = 2'd2;
parameter    ap_ST_iter7_fsm_state8 = 2'd2;
parameter    ap_ST_iter8_fsm_state9 = 2'd2;
parameter    ap_ST_iter9_fsm_state10 = 2'd2;
parameter    ap_ST_iter10_fsm_state11 = 2'd2;
parameter    ap_ST_iter11_fsm_state12 = 2'd2;
parameter    ap_ST_iter12_fsm_state13 = 2'd2;
parameter    ap_ST_iter13_fsm_state14 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;
parameter    ap_ST_iter6_fsm_state0 = 2'd1;
parameter    ap_ST_iter7_fsm_state0 = 2'd1;
parameter    ap_ST_iter8_fsm_state0 = 2'd1;
parameter    ap_ST_iter9_fsm_state0 = 2'd1;
parameter    ap_ST_iter10_fsm_state0 = 2'd1;
parameter    ap_ST_iter11_fsm_state0 = 2'd1;
parameter    ap_ST_iter12_fsm_state0 = 2'd1;
parameter    ap_ST_iter13_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] sm_inst_max2exp_max_dout;
input  [1:0] sm_inst_max2exp_max_num_data_valid;
input  [1:0] sm_inst_max2exp_max_fifo_cap;
input   sm_inst_max2exp_max_empty_n;
output   sm_inst_max2exp_max_read;
input  [31:0] sm_inst_max2exp_dat_dout;
input  [6:0] sm_inst_max2exp_dat_num_data_valid;
input  [6:0] sm_inst_max2exp_dat_fifo_cap;
input   sm_inst_max2exp_dat_empty_n;
output   sm_inst_max2exp_dat_read;
output  [31:0] sm_inst_exp2div_dat_din;
input  [6:0] sm_inst_exp2div_dat_num_data_valid;
input  [6:0] sm_inst_exp2div_dat_fifo_cap;
input   sm_inst_exp2div_dat_full_n;
output   sm_inst_exp2div_dat_write;
output  [30:0] sm_inst_exp2div_sum_din;
input  [1:0] sm_inst_exp2div_sum_num_data_valid;
input  [1:0] sm_inst_exp2div_sum_fifo_cap;
input   sm_inst_exp2div_sum_full_n;
output   sm_inst_exp2div_sum_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg sm_inst_max2exp_max_read;
reg sm_inst_max2exp_dat_read;
reg sm_inst_exp2div_dat_write;
reg sm_inst_exp2div_sum_write;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
reg   [1:0] ap_CS_iter6_fsm;
wire    ap_CS_iter6_fsm_state0;
reg   [1:0] ap_CS_iter7_fsm;
wire    ap_CS_iter7_fsm_state0;
reg   [1:0] ap_CS_iter8_fsm;
wire    ap_CS_iter8_fsm_state0;
reg   [1:0] ap_CS_iter9_fsm;
wire    ap_CS_iter9_fsm_state0;
reg   [1:0] ap_CS_iter10_fsm;
wire    ap_CS_iter10_fsm_state0;
reg   [1:0] ap_CS_iter11_fsm;
wire    ap_CS_iter11_fsm_state0;
reg   [1:0] ap_CS_iter12_fsm;
wire    ap_CS_iter12_fsm_state0;
reg   [1:0] ap_CS_iter13_fsm;
wire    ap_CS_iter13_fsm_state0;
wire   [0:0] tmp_1_i_nbreadreq_fu_114_p3;
reg    ap_predicate_op19_read_state1;
wire   [0:0] tmp_i_nbreadreq_fu_128_p3;
reg    ap_predicate_op27_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_CS_iter4_fsm_state5;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_CS_iter5_fsm_state6;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_CS_iter6_fsm_state7;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_CS_iter7_fsm_state8;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_CS_iter8_fsm_state9;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_CS_iter9_fsm_state10;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_CS_iter10_fsm_state11;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_CS_iter11_fsm_state12;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_CS_iter12_fsm_state13;
reg   [0:0] sm_inst_exp_valid_load_reg_646;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter12_reg;
reg   [0:0] tmp_i_reg_669;
reg   [0:0] tmp_i_reg_669_pp0_iter12_reg;
reg    ap_predicate_op138_write_state14;
reg   [0:0] ret_reg_688;
reg   [0:0] ret_reg_688_pp0_iter12_reg;
reg    ap_predicate_op139_write_state14;
reg    ap_block_state14_pp0_stage0_iter13;
wire    ap_CS_iter13_fsm_state14;
reg   [0:0] sm_inst_exp_valid;
reg   [31:0] sm_inst_exp_max_value;
reg   [0:0] sm_inst_exp_has_infty;
reg   [30:0] sm_inst_exp_total;
reg   [6:0] sm_inst_exp_cnt;
reg    sm_inst_max2exp_max_blk_n;
reg    sm_inst_max2exp_dat_blk_n;
reg    sm_inst_exp2div_dat_blk_n;
reg    sm_inst_exp2div_sum_blk_n;
wire   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter0_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter1_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter2_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter3_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter4_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter5_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter6_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter7_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter8_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter9_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter10_reg;
reg   [0:0] sm_inst_exp_valid_load_reg_646_pp0_iter11_reg;
reg   [0:0] tmp_1_i_reg_650;
wire   [0:0] tmp_1_i_reg_650_pp0_iter0_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter1_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter2_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter3_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter4_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter5_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter6_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter7_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter8_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter9_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter10_reg;
reg   [0:0] tmp_1_i_reg_650_pp0_iter11_reg;
reg   [31:0] sm_inst_max2exp_max_read_reg_654;
wire   [0:0] icmp_ln114_2_fu_191_p2;
reg   [0:0] icmp_ln114_2_reg_659;
wire   [0:0] icmp_ln114_3_fu_197_p2;
reg   [0:0] icmp_ln114_3_reg_664;
wire   [0:0] tmp_i_reg_669_pp0_iter0_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter1_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter2_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter3_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter4_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter5_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter6_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter7_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter8_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter9_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter10_reg;
reg   [0:0] tmp_i_reg_669_pp0_iter11_reg;
reg   [31:0] sm_inst_max2exp_dat_read_reg_673;
wire   [0:0] icmp_ln114_fu_223_p2;
reg   [0:0] icmp_ln114_reg_678;
reg   [0:0] icmp_ln114_reg_678_pp0_iter1_reg;
reg   [0:0] icmp_ln114_reg_678_pp0_iter2_reg;
reg   [0:0] icmp_ln114_reg_678_pp0_iter3_reg;
reg   [0:0] icmp_ln114_reg_678_pp0_iter4_reg;
reg   [0:0] icmp_ln114_reg_678_pp0_iter5_reg;
reg   [0:0] icmp_ln114_reg_678_pp0_iter6_reg;
reg   [0:0] icmp_ln114_reg_678_pp0_iter7_reg;
reg   [0:0] icmp_ln114_reg_678_pp0_iter8_reg;
reg   [0:0] icmp_ln114_reg_678_pp0_iter9_reg;
wire   [0:0] icmp_ln114_1_fu_229_p2;
reg   [0:0] icmp_ln114_1_reg_683;
reg   [0:0] icmp_ln114_1_reg_683_pp0_iter1_reg;
reg   [0:0] icmp_ln114_1_reg_683_pp0_iter2_reg;
reg   [0:0] icmp_ln114_1_reg_683_pp0_iter3_reg;
reg   [0:0] icmp_ln114_1_reg_683_pp0_iter4_reg;
reg   [0:0] icmp_ln114_1_reg_683_pp0_iter5_reg;
reg   [0:0] icmp_ln114_1_reg_683_pp0_iter6_reg;
reg   [0:0] icmp_ln114_1_reg_683_pp0_iter7_reg;
reg   [0:0] icmp_ln114_1_reg_683_pp0_iter8_reg;
reg   [0:0] icmp_ln114_1_reg_683_pp0_iter9_reg;
wire   [0:0] ret_fu_239_p3;
reg   [0:0] ret_reg_688_pp0_iter1_reg;
reg   [0:0] ret_reg_688_pp0_iter2_reg;
reg   [0:0] ret_reg_688_pp0_iter3_reg;
reg   [0:0] ret_reg_688_pp0_iter4_reg;
reg   [0:0] ret_reg_688_pp0_iter5_reg;
reg   [0:0] ret_reg_688_pp0_iter6_reg;
reg   [0:0] ret_reg_688_pp0_iter7_reg;
reg   [0:0] ret_reg_688_pp0_iter8_reg;
reg   [0:0] ret_reg_688_pp0_iter9_reg;
reg   [0:0] ret_reg_688_pp0_iter10_reg;
reg   [0:0] ret_reg_688_pp0_iter11_reg;
reg   [0:0] sm_inst_exp_has_infty_load_reg_692;
reg   [0:0] sm_inst_exp_has_infty_load_reg_692_pp0_iter2_reg;
reg   [0:0] sm_inst_exp_has_infty_load_reg_692_pp0_iter3_reg;
reg   [0:0] sm_inst_exp_has_infty_load_reg_692_pp0_iter4_reg;
reg   [0:0] sm_inst_exp_has_infty_load_reg_692_pp0_iter5_reg;
reg   [0:0] sm_inst_exp_has_infty_load_reg_692_pp0_iter6_reg;
reg   [0:0] sm_inst_exp_has_infty_load_reg_692_pp0_iter7_reg;
reg   [0:0] sm_inst_exp_has_infty_load_reg_692_pp0_iter8_reg;
reg   [0:0] sm_inst_exp_has_infty_load_reg_692_pp0_iter9_reg;
wire   [0:0] grp_fu_163_p2;
reg   [0:0] tmp_5_reg_697;
reg   [0:0] tmp_5_reg_697_pp0_iter2_reg;
reg   [0:0] tmp_5_reg_697_pp0_iter3_reg;
reg   [0:0] tmp_5_reg_697_pp0_iter4_reg;
reg   [0:0] tmp_5_reg_697_pp0_iter5_reg;
reg   [0:0] tmp_5_reg_697_pp0_iter6_reg;
reg   [0:0] tmp_5_reg_697_pp0_iter7_reg;
reg   [0:0] tmp_5_reg_697_pp0_iter8_reg;
reg   [0:0] tmp_5_reg_697_pp0_iter9_reg;
wire   [31:0] x_assign_fu_156_p2;
reg   [31:0] x_assign_reg_702;
wire   [31:0] yy_fu_344_p3;
reg   [31:0] yy_reg_707;
reg   [31:0] yy_reg_707_pp0_iter11_reg;
wire   [62:0] trunc_ln194_fu_356_p1;
reg   [62:0] trunc_ln194_reg_712;
reg   [0:0] tmp_1_reg_717;
reg   [0:0] tmp_1_reg_717_pp0_iter11_reg;
reg   [10:0] tmp_3_i6_reg_723;
wire   [51:0] trunc_ln194_1_fu_378_p1;
reg   [51:0] trunc_ln194_1_reg_728;
wire   [53:0] select_ln194_fu_402_p3;
reg   [53:0] select_ln194_reg_733;
wire   [0:0] icmp_ln194_fu_409_p2;
reg   [0:0] icmp_ln194_reg_738;
wire   [0:0] icmp_ln194_reg_738_pp0_iter11_reg;
reg   [0:0] icmp_ln194_reg_738_pp0_iter12_reg;
wire   [0:0] icmp_ln194_1_fu_424_p2;
reg   [0:0] icmp_ln194_1_reg_745;
reg   [0:0] icmp_ln194_1_reg_745_pp0_iter12_reg;
wire   [11:0] add_ln194_fu_430_p2;
reg   [11:0] add_ln194_reg_750;
wire  signed [11:0] select_ln194_1_fu_442_p3;
reg  signed [11:0] select_ln194_1_reg_755;
wire   [0:0] icmp_ln194_2_fu_450_p2;
reg   [0:0] icmp_ln194_2_reg_762;
reg   [0:0] icmp_ln194_2_reg_762_pp0_iter12_reg;
wire   [24:0] trunc_ln194_3_fu_456_p1;
reg   [24:0] trunc_ln194_3_reg_768;
wire   [0:0] bit_select59_i_i_fu_470_p3;
reg   [0:0] bit_select59_i_i_reg_774;
wire   [24:0] add_ln194_2_fu_569_p2;
reg   [24:0] add_ln194_2_reg_779;
wire   [24:0] select_ln194_6_fu_592_p3;
reg   [24:0] select_ln194_6_reg_784;
wire   [31:0] bitcast_ln178_fu_296_p1;
wire   [0:0] and_ln114_1_fu_310_p2;
wire   [30:0] add_ln196_fu_633_p2;
wire   [6:0] add_ln96_2_fu_269_p2;
wire   [31:0] x_assign_fu_156_p0;
wire   [31:0] xx_fu_322_p1;
wire   [31:0] pf_fu_160_p0;
reg   [31:0] grp_fu_163_p0;
wire   [7:0] tmp_fu_177_p4;
wire   [22:0] trunc_ln114_1_fu_187_p1;
wire   [7:0] tmp_4_fu_209_p4;
wire   [22:0] trunc_ln114_fu_219_p1;
wire   [0:0] tmp_7_fu_247_p3;
wire   [6:0] and_ln_fu_255_p3;
wire   [6:0] add_ln96_fu_263_p2;
wire   [0:0] or_ln114_1_fu_306_p2;
wire   [0:0] or_ln114_fu_327_p2;
wire   [0:0] and_ln114_fu_331_p2;
wire   [31:0] select_ln193_fu_336_p3;
wire   [31:0] grp_fu_168_p2;
wire   [63:0] pf_fu_160_p1;
wire   [63:0] bitcast_ln724_fu_352_p1;
wire   [52:0] zext_ln194_1_cast_fu_385_p3;
wire   [53:0] zext_ln194_1_fu_392_p1;
wire   [53:0] sub_ln194_fu_396_p2;
wire   [11:0] zext_ln194_fu_382_p1;
wire   [11:0] sub_ln194_1_fu_414_p2;
wire   [11:0] sub_ln194_2_fu_436_p2;
wire   [10:0] trunc_ln194_2_fu_420_p1;
wire   [10:0] add_ln194_1_fu_460_p2;
wire   [31:0] zext_ln194_4_fu_466_p1;
wire   [31:0] bitcast_ln724_1_fu_492_p1;
wire   [0:0] tmp_2_fu_495_p3;
wire  signed [31:0] sext_ln194_fu_484_p1;
wire   [53:0] zext_ln194_2_fu_511_p1;
wire   [53:0] ashr_ln194_fu_515_p2;
wire   [0:0] icmp_ln194_3_fu_487_p2;
wire   [24:0] trunc_ln194_4_fu_520_p1;
wire   [24:0] select_ln194_8_fu_503_p3;
wire   [24:0] sext_ln194cast_fu_542_p1;
wire   [0:0] icmp_ln194_5_fu_537_p2;
wire   [24:0] shl_ln194_fu_546_p2;
wire   [0:0] icmp_ln194_4_fu_532_p2;
wire   [0:0] select_ln194_4_fu_559_p3;
wire   [24:0] select_ln194_2_fu_524_p3;
wire   [24:0] zext_ln194_5_fu_565_p1;
wire   [24:0] select_ln194_3_fu_551_p3;
wire   [0:0] xor_ln194_fu_582_p2;
wire   [0:0] and_ln194_fu_587_p2;
wire   [24:0] select_ln194_5_fu_575_p3;
wire   [0:0] or_ln194_fu_599_p2;
wire   [0:0] xor_ln194_1_fu_603_p2;
wire   [0:0] and_ln194_1_fu_609_p2;
wire   [24:0] select_ln194_7_fu_614_p3;
wire   [30:0] zext_ln196_1_fu_629_p1;
reg    grp_fu_168_ce;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg   [1:0] ap_NS_iter6_fsm;
reg   [1:0] ap_NS_iter7_fsm;
reg   [1:0] ap_NS_iter8_fsm;
reg   [1:0] ap_NS_iter9_fsm;
reg   [1:0] ap_NS_iter10_fsm;
reg   [1:0] ap_NS_iter11_fsm;
reg   [1:0] ap_NS_iter12_fsm;
reg   [1:0] ap_NS_iter13_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
wire    ap_ST_iter3_fsm_state4_blk;
wire    ap_ST_iter4_fsm_state5_blk;
wire    ap_ST_iter5_fsm_state6_blk;
wire    ap_ST_iter6_fsm_state7_blk;
wire    ap_ST_iter7_fsm_state8_blk;
wire    ap_ST_iter8_fsm_state9_blk;
wire    ap_ST_iter9_fsm_state10_blk;
wire    ap_ST_iter10_fsm_state11_blk;
wire    ap_ST_iter11_fsm_state12_blk;
wire    ap_ST_iter12_fsm_state13_blk;
reg    ap_ST_iter13_fsm_state14_blk;
reg    ap_condition_532;
reg    ap_condition_277;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 ap_CS_iter6_fsm = 2'd1;
#0 ap_CS_iter7_fsm = 2'd1;
#0 ap_CS_iter8_fsm = 2'd1;
#0 ap_CS_iter9_fsm = 2'd1;
#0 ap_CS_iter10_fsm = 2'd1;
#0 ap_CS_iter11_fsm = 2'd1;
#0 ap_CS_iter12_fsm = 2'd1;
#0 ap_CS_iter13_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 sm_inst_exp_valid = 1'd0;
#0 sm_inst_exp_max_value = 32'd0;
#0 sm_inst_exp_has_infty = 1'd0;
#0 sm_inst_exp_total = 31'd0;
#0 sm_inst_exp_cnt = 7'd62;
end

softmax_top_fsub_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_1_primitive_dsp_1_U7(
    .din0(x_assign_fu_156_p0),
    .din1(sm_inst_exp_max_value),
    .dout(x_assign_fu_156_p2)
);

softmax_top_fpext_32ns_64_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_1_no_dsp_1_U8(
    .din0(pf_fu_160_p0),
    .dout(pf_fu_160_p1)
);

softmax_top_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U9(
    .din0(grp_fu_163_p0),
    .din1(32'd2139095040),
    .opcode(5'd1),
    .dout(grp_fu_163_p2)
);

softmax_top_fexp_32ns_32ns_32_9_med_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fexp_32ns_32ns_32_9_med_dsp_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(x_assign_reg_702),
    .ce(grp_fu_168_ce),
    .dout(grp_fu_168_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter10_fsm <= ap_ST_iter10_fsm_state0;
    end else begin
        ap_CS_iter10_fsm <= ap_NS_iter10_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter11_fsm <= ap_ST_iter11_fsm_state0;
    end else begin
        ap_CS_iter11_fsm <= ap_NS_iter11_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter12_fsm <= ap_ST_iter12_fsm_state0;
    end else begin
        ap_CS_iter12_fsm <= ap_NS_iter12_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter13_fsm <= ap_ST_iter13_fsm_state0;
    end else begin
        ap_CS_iter13_fsm <= ap_NS_iter13_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter6_fsm <= ap_ST_iter6_fsm_state0;
    end else begin
        ap_CS_iter6_fsm <= ap_NS_iter6_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter7_fsm <= ap_ST_iter7_fsm_state0;
    end else begin
        ap_CS_iter7_fsm <= ap_NS_iter7_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter8_fsm <= ap_ST_iter8_fsm_state0;
    end else begin
        ap_CS_iter8_fsm <= ap_NS_iter8_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter9_fsm <= ap_ST_iter9_fsm_state0;
    end else begin
        ap_CS_iter9_fsm <= ap_NS_iter9_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (tmp_1_i_reg_650_pp0_iter11_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter11_reg == 1'd0) & (1'b1 == ap_CS_iter12_fsm_state13))) begin
        sm_inst_exp_total <= 31'd0;
    end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))) & (tmp_i_reg_669_pp0_iter12_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter12_reg == 1'd1) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
        sm_inst_exp_total <= add_ln196_fu_633_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_277)) begin
        if ((1'b1 == ap_condition_532)) begin
            sm_inst_exp_valid <= 1'd0;
        end else if (((tmp_1_i_nbreadreq_fu_114_p3 == 1'd1) & (sm_inst_exp_valid == 1'd0))) begin
            sm_inst_exp_valid <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (tmp_i_reg_669_pp0_iter11_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter11_reg == 1'd1) & (1'b1 == ap_CS_iter12_fsm_state13))) begin
        add_ln194_2_reg_779 <= add_ln194_2_fu_569_p2;
        select_ln194_6_reg_784 <= select_ln194_6_fu_592_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (tmp_i_reg_669_pp0_iter10_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter10_reg == 1'd1) & (1'b1 == ap_CS_iter11_fsm_state12))) begin
        add_ln194_reg_750 <= add_ln194_fu_430_p2;
        bit_select59_i_i_reg_774 <= bit_select59_i_i_fu_470_p3;
        icmp_ln194_1_reg_745 <= icmp_ln194_1_fu_424_p2;
        icmp_ln194_2_reg_762 <= icmp_ln194_2_fu_450_p2;
        icmp_ln194_reg_738 <= icmp_ln194_fu_409_p2;
        select_ln194_1_reg_755 <= select_ln194_1_fu_442_p3;
        select_ln194_reg_733 <= select_ln194_fu_402_p3;
        trunc_ln194_3_reg_768 <= trunc_ln194_3_fu_456_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (tmp_i_nbreadreq_fu_128_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (sm_inst_exp_valid == 1'd1))) begin
        icmp_ln114_1_reg_683 <= icmp_ln114_1_fu_229_p2;
        icmp_ln114_reg_678 <= icmp_ln114_fu_223_p2;
        ret_reg_688 <= sm_inst_exp_cnt[32'd6];
        sm_inst_exp_cnt <= add_ln96_2_fu_269_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln114_1_reg_683_pp0_iter1_reg <= icmp_ln114_1_reg_683;
        icmp_ln114_reg_678_pp0_iter1_reg <= icmp_ln114_reg_678;
        ret_reg_688_pp0_iter1_reg <= ret_reg_688;
        sm_inst_exp_has_infty_load_reg_692 <= sm_inst_exp_has_infty;
        sm_inst_exp_valid_load_reg_646_pp0_iter1_reg <= sm_inst_exp_valid_load_reg_646;
        tmp_1_i_reg_650_pp0_iter1_reg <= tmp_1_i_reg_650;
        tmp_i_reg_669_pp0_iter1_reg <= tmp_i_reg_669;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        icmp_ln114_1_reg_683_pp0_iter2_reg <= icmp_ln114_1_reg_683_pp0_iter1_reg;
        icmp_ln114_reg_678_pp0_iter2_reg <= icmp_ln114_reg_678_pp0_iter1_reg;
        ret_reg_688_pp0_iter2_reg <= ret_reg_688_pp0_iter1_reg;
        sm_inst_exp_has_infty_load_reg_692_pp0_iter2_reg <= sm_inst_exp_has_infty_load_reg_692;
        sm_inst_exp_valid_load_reg_646_pp0_iter2_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter1_reg;
        tmp_1_i_reg_650_pp0_iter2_reg <= tmp_1_i_reg_650_pp0_iter1_reg;
        tmp_5_reg_697_pp0_iter2_reg <= tmp_5_reg_697;
        tmp_i_reg_669_pp0_iter2_reg <= tmp_i_reg_669_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        icmp_ln114_1_reg_683_pp0_iter3_reg <= icmp_ln114_1_reg_683_pp0_iter2_reg;
        icmp_ln114_reg_678_pp0_iter3_reg <= icmp_ln114_reg_678_pp0_iter2_reg;
        ret_reg_688_pp0_iter3_reg <= ret_reg_688_pp0_iter2_reg;
        sm_inst_exp_has_infty_load_reg_692_pp0_iter3_reg <= sm_inst_exp_has_infty_load_reg_692_pp0_iter2_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter3_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter2_reg;
        tmp_1_i_reg_650_pp0_iter3_reg <= tmp_1_i_reg_650_pp0_iter2_reg;
        tmp_5_reg_697_pp0_iter3_reg <= tmp_5_reg_697_pp0_iter2_reg;
        tmp_i_reg_669_pp0_iter3_reg <= tmp_i_reg_669_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        icmp_ln114_1_reg_683_pp0_iter4_reg <= icmp_ln114_1_reg_683_pp0_iter3_reg;
        icmp_ln114_reg_678_pp0_iter4_reg <= icmp_ln114_reg_678_pp0_iter3_reg;
        ret_reg_688_pp0_iter4_reg <= ret_reg_688_pp0_iter3_reg;
        sm_inst_exp_has_infty_load_reg_692_pp0_iter4_reg <= sm_inst_exp_has_infty_load_reg_692_pp0_iter3_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter4_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter3_reg;
        tmp_1_i_reg_650_pp0_iter4_reg <= tmp_1_i_reg_650_pp0_iter3_reg;
        tmp_5_reg_697_pp0_iter4_reg <= tmp_5_reg_697_pp0_iter3_reg;
        tmp_i_reg_669_pp0_iter4_reg <= tmp_i_reg_669_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        icmp_ln114_1_reg_683_pp0_iter5_reg <= icmp_ln114_1_reg_683_pp0_iter4_reg;
        icmp_ln114_reg_678_pp0_iter5_reg <= icmp_ln114_reg_678_pp0_iter4_reg;
        ret_reg_688_pp0_iter5_reg <= ret_reg_688_pp0_iter4_reg;
        sm_inst_exp_has_infty_load_reg_692_pp0_iter5_reg <= sm_inst_exp_has_infty_load_reg_692_pp0_iter4_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter5_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter4_reg;
        tmp_1_i_reg_650_pp0_iter5_reg <= tmp_1_i_reg_650_pp0_iter4_reg;
        tmp_5_reg_697_pp0_iter5_reg <= tmp_5_reg_697_pp0_iter4_reg;
        tmp_i_reg_669_pp0_iter5_reg <= tmp_i_reg_669_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
        icmp_ln114_1_reg_683_pp0_iter6_reg <= icmp_ln114_1_reg_683_pp0_iter5_reg;
        icmp_ln114_reg_678_pp0_iter6_reg <= icmp_ln114_reg_678_pp0_iter5_reg;
        ret_reg_688_pp0_iter6_reg <= ret_reg_688_pp0_iter5_reg;
        sm_inst_exp_has_infty_load_reg_692_pp0_iter6_reg <= sm_inst_exp_has_infty_load_reg_692_pp0_iter5_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter6_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter5_reg;
        tmp_1_i_reg_650_pp0_iter6_reg <= tmp_1_i_reg_650_pp0_iter5_reg;
        tmp_5_reg_697_pp0_iter6_reg <= tmp_5_reg_697_pp0_iter5_reg;
        tmp_i_reg_669_pp0_iter6_reg <= tmp_i_reg_669_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
        icmp_ln114_1_reg_683_pp0_iter7_reg <= icmp_ln114_1_reg_683_pp0_iter6_reg;
        icmp_ln114_reg_678_pp0_iter7_reg <= icmp_ln114_reg_678_pp0_iter6_reg;
        ret_reg_688_pp0_iter7_reg <= ret_reg_688_pp0_iter6_reg;
        sm_inst_exp_has_infty_load_reg_692_pp0_iter7_reg <= sm_inst_exp_has_infty_load_reg_692_pp0_iter6_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter7_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter6_reg;
        tmp_1_i_reg_650_pp0_iter7_reg <= tmp_1_i_reg_650_pp0_iter6_reg;
        tmp_5_reg_697_pp0_iter7_reg <= tmp_5_reg_697_pp0_iter6_reg;
        tmp_i_reg_669_pp0_iter7_reg <= tmp_i_reg_669_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter8_fsm_state9))) begin
        icmp_ln114_1_reg_683_pp0_iter8_reg <= icmp_ln114_1_reg_683_pp0_iter7_reg;
        icmp_ln114_reg_678_pp0_iter8_reg <= icmp_ln114_reg_678_pp0_iter7_reg;
        ret_reg_688_pp0_iter8_reg <= ret_reg_688_pp0_iter7_reg;
        sm_inst_exp_has_infty_load_reg_692_pp0_iter8_reg <= sm_inst_exp_has_infty_load_reg_692_pp0_iter7_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter8_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter7_reg;
        tmp_1_i_reg_650_pp0_iter8_reg <= tmp_1_i_reg_650_pp0_iter7_reg;
        tmp_5_reg_697_pp0_iter8_reg <= tmp_5_reg_697_pp0_iter7_reg;
        tmp_i_reg_669_pp0_iter8_reg <= tmp_i_reg_669_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter9_fsm_state10))) begin
        icmp_ln114_1_reg_683_pp0_iter9_reg <= icmp_ln114_1_reg_683_pp0_iter8_reg;
        icmp_ln114_reg_678_pp0_iter9_reg <= icmp_ln114_reg_678_pp0_iter8_reg;
        ret_reg_688_pp0_iter9_reg <= ret_reg_688_pp0_iter8_reg;
        sm_inst_exp_has_infty_load_reg_692_pp0_iter9_reg <= sm_inst_exp_has_infty_load_reg_692_pp0_iter8_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter9_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter8_reg;
        tmp_1_i_reg_650_pp0_iter9_reg <= tmp_1_i_reg_650_pp0_iter8_reg;
        tmp_5_reg_697_pp0_iter9_reg <= tmp_5_reg_697_pp0_iter8_reg;
        tmp_i_reg_669_pp0_iter9_reg <= tmp_i_reg_669_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (tmp_1_i_nbreadreq_fu_114_p3 == 1'd1) & (sm_inst_exp_valid == 1'd0))) begin
        icmp_ln114_2_reg_659 <= icmp_ln114_2_fu_191_p2;
        icmp_ln114_3_reg_664 <= icmp_ln114_3_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter12_fsm_state13))) begin
        icmp_ln194_1_reg_745_pp0_iter12_reg <= icmp_ln194_1_reg_745;
        icmp_ln194_2_reg_762_pp0_iter12_reg <= icmp_ln194_2_reg_762;
        icmp_ln194_reg_738_pp0_iter12_reg <= icmp_ln194_reg_738;
        ret_reg_688_pp0_iter12_reg <= ret_reg_688_pp0_iter11_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter12_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter11_reg;
        tmp_i_reg_669_pp0_iter12_reg <= tmp_i_reg_669_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter10_fsm_state11))) begin
        ret_reg_688_pp0_iter10_reg <= ret_reg_688_pp0_iter9_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter10_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter9_reg;
        tmp_1_i_reg_650_pp0_iter10_reg <= tmp_1_i_reg_650_pp0_iter9_reg;
        tmp_i_reg_669_pp0_iter10_reg <= tmp_i_reg_669_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter11_fsm_state12))) begin
        ret_reg_688_pp0_iter11_reg <= ret_reg_688_pp0_iter10_reg;
        sm_inst_exp_valid_load_reg_646_pp0_iter11_reg <= sm_inst_exp_valid_load_reg_646_pp0_iter10_reg;
        tmp_1_i_reg_650_pp0_iter11_reg <= tmp_1_i_reg_650_pp0_iter10_reg;
        tmp_1_reg_717_pp0_iter11_reg <= tmp_1_reg_717;
        tmp_i_reg_669_pp0_iter11_reg <= tmp_i_reg_669_pp0_iter10_reg;
        yy_reg_707_pp0_iter11_reg <= yy_reg_707;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (tmp_1_i_reg_650_pp0_iter0_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter0_reg == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        sm_inst_exp_has_infty <= and_ln114_1_fu_310_p2;
        sm_inst_exp_max_value <= bitcast_ln178_fu_296_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sm_inst_exp_valid_load_reg_646 <= sm_inst_exp_valid;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (ap_predicate_op27_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sm_inst_max2exp_dat_read_reg_673 <= sm_inst_max2exp_dat_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (ap_predicate_op19_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sm_inst_max2exp_max_read_reg_654 <= sm_inst_max2exp_max_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (sm_inst_exp_valid == 1'd0))) begin
        tmp_1_i_reg_650 <= tmp_1_i_nbreadreq_fu_114_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (tmp_i_reg_669_pp0_iter9_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter9_reg == 1'd1) & (1'b1 == ap_CS_iter10_fsm_state11))) begin
        tmp_1_reg_717 <= bitcast_ln724_fu_352_p1[32'd63];
        tmp_3_i6_reg_723 <= {{bitcast_ln724_fu_352_p1[62:52]}};
        trunc_ln194_1_reg_728 <= trunc_ln194_1_fu_378_p1;
        trunc_ln194_reg_712 <= trunc_ln194_fu_356_p1;
        yy_reg_707 <= yy_fu_344_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (tmp_i_reg_669_pp0_iter0_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter0_reg == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        tmp_5_reg_697 <= grp_fu_163_p2;
        x_assign_reg_702 <= x_assign_fu_156_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (sm_inst_exp_valid == 1'd1))) begin
        tmp_i_reg_669 <= tmp_i_nbreadreq_fu_128_p3;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter10_fsm_state11_blk = 1'b0;

assign ap_ST_iter11_fsm_state12_blk = 1'b0;

assign ap_ST_iter12_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) begin
        ap_ST_iter13_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_iter13_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

assign ap_ST_iter3_fsm_state4_blk = 1'b0;

assign ap_ST_iter4_fsm_state5_blk = 1'b0;

assign ap_ST_iter5_fsm_state6_blk = 1'b0;

assign ap_ST_iter6_fsm_state7_blk = 1'b0;

assign ap_ST_iter7_fsm_state8_blk = 1'b0;

assign ap_ST_iter8_fsm_state9_blk = 1'b0;

assign ap_ST_iter9_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_iter7_fsm_state0) & (1'b1 == ap_CS_iter6_fsm_state0) & (1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_CS_iter13_fsm_state0) & (1'b1 == ap_CS_iter12_fsm_state0) & (1'b1 == ap_CS_iter11_fsm_state0) & (1'b1 == ap_CS_iter10_fsm_state0) & (1'b1 == ap_CS_iter9_fsm_state0) & (1'b1 == ap_CS_iter8_fsm_state0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter1_fsm_state2)) begin
        if (((tmp_i_reg_669_pp0_iter0_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter0_reg == 1'd1))) begin
            grp_fu_163_p0 = xx_fu_322_p1;
        end else if (((tmp_1_i_reg_650_pp0_iter0_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter0_reg == 1'd0))) begin
            grp_fu_163_p0 = bitcast_ln178_fu_296_p1;
        end else begin
            grp_fu_163_p0 = 'bx;
        end
    end else begin
        grp_fu_163_p0 = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter10_fsm_state11)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter9_fsm_state10)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter8_fsm_state9)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 
    1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter7_fsm_state8)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter6_fsm_state7)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter5_fsm_state6)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) 
    & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
        grp_fu_168_ce = 1'b1;
    end else begin
        grp_fu_168_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op138_write_state14 == 1'b1) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
        sm_inst_exp2div_dat_blk_n = sm_inst_exp2div_dat_full_n;
    end else begin
        sm_inst_exp2div_dat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))) & (ap_predicate_op138_write_state14 == 1'b1) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
        sm_inst_exp2div_dat_write = 1'b1;
    end else begin
        sm_inst_exp2div_dat_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op139_write_state14 == 1'b1) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
        sm_inst_exp2div_sum_blk_n = sm_inst_exp2div_sum_full_n;
    end else begin
        sm_inst_exp2div_sum_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))) & (ap_predicate_op139_write_state14 == 1'b1) & (1'b1 == ap_CS_iter13_fsm_state14))) begin
        sm_inst_exp2div_sum_write = 1'b1;
    end else begin
        sm_inst_exp2div_sum_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (ap_predicate_op27_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sm_inst_max2exp_dat_blk_n = sm_inst_max2exp_dat_empty_n;
    end else begin
        sm_inst_max2exp_dat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (ap_predicate_op27_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sm_inst_max2exp_dat_read = 1'b1;
    end else begin
        sm_inst_max2exp_dat_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (ap_predicate_op19_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sm_inst_max2exp_max_blk_n = sm_inst_max2exp_max_empty_n;
    end else begin
        sm_inst_max2exp_max_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (ap_predicate_op19_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sm_inst_max2exp_max_read = 1'b1;
    end else begin
        sm_inst_max2exp_max_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & ~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter6_fsm)
        ap_ST_iter6_fsm_state7 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end
        end
        ap_ST_iter6_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter6_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter7_fsm)
        ap_ST_iter7_fsm_state8 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter6_fsm_state7))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state0;
            end else begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end
        end
        ap_ST_iter7_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state8;
            end else begin
                ap_NS_iter7_fsm = ap_ST_iter7_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter7_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter8_fsm)
        ap_ST_iter8_fsm_state9 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state9;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter7_fsm_state8))) begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state0;
            end else begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state9;
            end
        end
        ap_ST_iter8_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter7_fsm_state8))) begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state9;
            end else begin
                ap_NS_iter8_fsm = ap_ST_iter8_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter8_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter9_fsm)
        ap_ST_iter9_fsm_state10 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter8_fsm_state9))) begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state10;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter8_fsm_state9))) begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state0;
            end else begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state10;
            end
        end
        ap_ST_iter9_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter8_fsm_state9))) begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state10;
            end else begin
                ap_NS_iter9_fsm = ap_ST_iter9_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter9_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter10_fsm)
        ap_ST_iter10_fsm_state11 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter9_fsm_state10))) begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state11;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter9_fsm_state10))) begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state0;
            end else begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state11;
            end
        end
        ap_ST_iter10_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter9_fsm_state10))) begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state11;
            end else begin
                ap_NS_iter10_fsm = ap_ST_iter10_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter10_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter11_fsm)
        ap_ST_iter11_fsm_state12 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter10_fsm_state11))) begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state12;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter10_fsm_state11))) begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state0;
            end else begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state12;
            end
        end
        ap_ST_iter11_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter10_fsm_state11))) begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state12;
            end else begin
                ap_NS_iter11_fsm = ap_ST_iter11_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter11_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter12_fsm)
        ap_ST_iter12_fsm_state13 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter11_fsm_state12))) begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state13;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b0 == ap_CS_iter11_fsm_state12))) begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state0;
            end else begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state13;
            end
        end
        ap_ST_iter12_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter11_fsm_state12))) begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state13;
            end else begin
                ap_NS_iter12_fsm = ap_ST_iter12_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter12_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter13_fsm)
        ap_ST_iter13_fsm_state14 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))) & (1'b1 == ap_CS_iter12_fsm_state13))) begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state14;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))) & (1'b0 == ap_CS_iter12_fsm_state13))) begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state0;
            end else begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state14;
            end
        end
        ap_ST_iter13_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0))))) & (1'b1 == ap_CS_iter12_fsm_state13))) begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state14;
            end else begin
                ap_NS_iter13_fsm = ap_ST_iter13_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter13_fsm = 'bx;
        end
    endcase
end

assign add_ln194_1_fu_460_p2 = ($signed(trunc_ln194_2_fu_420_p1) + $signed(11'd2023));

assign add_ln194_2_fu_569_p2 = (select_ln194_2_fu_524_p3 + zext_ln194_5_fu_565_p1);

assign add_ln194_fu_430_p2 = ($signed(sub_ln194_1_fu_414_p2) + $signed(12'd4072));

assign add_ln196_fu_633_p2 = (sm_inst_exp_total + zext_ln196_1_fu_629_p1);

assign add_ln96_2_fu_269_p2 = (add_ln96_fu_263_p2 + sm_inst_exp_cnt);

assign add_ln96_fu_263_p2 = ($signed(and_ln_fu_255_p3) + $signed(7'd127));

assign and_ln114_1_fu_310_p2 = (or_ln114_1_fu_306_p2 & grp_fu_163_p2);

assign and_ln114_fu_331_p2 = (tmp_5_reg_697_pp0_iter9_reg & or_ln114_fu_327_p2);

assign and_ln194_1_fu_609_p2 = (xor_ln194_1_fu_603_p2 & icmp_ln194_1_reg_745_pp0_iter12_reg);

assign and_ln194_fu_587_p2 = (xor_ln194_fu_582_p2 & icmp_ln194_2_reg_762);

assign and_ln_fu_255_p3 = {{tmp_7_fu_247_p3}, {6'd0}};

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter10_fsm_state0 = ap_CS_iter10_fsm[32'd0];

assign ap_CS_iter10_fsm_state11 = ap_CS_iter10_fsm[32'd1];

assign ap_CS_iter11_fsm_state0 = ap_CS_iter11_fsm[32'd0];

assign ap_CS_iter11_fsm_state12 = ap_CS_iter11_fsm[32'd1];

assign ap_CS_iter12_fsm_state0 = ap_CS_iter12_fsm[32'd0];

assign ap_CS_iter12_fsm_state13 = ap_CS_iter12_fsm[32'd1];

assign ap_CS_iter13_fsm_state0 = ap_CS_iter13_fsm[32'd0];

assign ap_CS_iter13_fsm_state14 = ap_CS_iter13_fsm[32'd1];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

assign ap_CS_iter6_fsm_state0 = ap_CS_iter6_fsm[32'd0];

assign ap_CS_iter6_fsm_state7 = ap_CS_iter6_fsm[32'd1];

assign ap_CS_iter7_fsm_state0 = ap_CS_iter7_fsm[32'd0];

assign ap_CS_iter7_fsm_state8 = ap_CS_iter7_fsm[32'd1];

assign ap_CS_iter8_fsm_state0 = ap_CS_iter8_fsm[32'd0];

assign ap_CS_iter8_fsm_state9 = ap_CS_iter8_fsm[32'd1];

assign ap_CS_iter9_fsm_state0 = ap_CS_iter9_fsm[32'd0];

assign ap_CS_iter9_fsm_state10 = ap_CS_iter9_fsm[32'd1];

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage0_iter13 = (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_277 = (~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter13_fsm_state14) & (((ap_predicate_op139_write_state14 == 1'b1) & (sm_inst_exp2div_sum_full_n == 1'b0)) | ((ap_predicate_op138_write_state14 == 1'b1) & (sm_inst_exp2div_dat_full_n == 1'b0)))) | ((ap_predicate_op27_read_state1 == 1'b1) & (sm_inst_max2exp_dat_empty_n == 1'b0)) | ((ap_predicate_op19_read_state1 == 1'b1) & (sm_inst_max2exp_max_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_532 = ((ret_fu_239_p3 == 1'd1) & (tmp_i_nbreadreq_fu_128_p3 == 1'd1) & (sm_inst_exp_valid == 1'd1));
end

always @ (*) begin
    ap_predicate_op138_write_state14 = ((tmp_i_reg_669_pp0_iter12_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter12_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op139_write_state14 = ((ret_reg_688_pp0_iter12_reg == 1'd1) & (tmp_i_reg_669_pp0_iter12_reg == 1'd1) & (sm_inst_exp_valid_load_reg_646_pp0_iter12_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op19_read_state1 = ((tmp_1_i_nbreadreq_fu_114_p3 == 1'd1) & (sm_inst_exp_valid == 1'd0));
end

always @ (*) begin
    ap_predicate_op27_read_state1 = ((tmp_i_nbreadreq_fu_128_p3 == 1'd1) & (sm_inst_exp_valid == 1'd1));
end

assign ashr_ln194_fu_515_p2 = $signed(select_ln194_reg_733) >>> zext_ln194_2_fu_511_p1;

assign bit_select59_i_i_fu_470_p3 = select_ln194_fu_402_p3[zext_ln194_4_fu_466_p1];

assign bitcast_ln178_fu_296_p1 = sm_inst_max2exp_max_read_reg_654;

assign bitcast_ln724_1_fu_492_p1 = yy_reg_707_pp0_iter11_reg;

assign bitcast_ln724_fu_352_p1 = pf_fu_160_p1;

assign icmp_ln114_1_fu_229_p2 = ((trunc_ln114_fu_219_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln114_2_fu_191_p2 = ((tmp_fu_177_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln114_3_fu_197_p2 = ((trunc_ln114_1_fu_187_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln114_fu_223_p2 = ((tmp_4_fu_209_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln194_1_fu_424_p2 = (($signed(sub_ln194_1_fu_414_p2) > $signed(12'd24)) ? 1'b1 : 1'b0);

assign icmp_ln194_2_fu_450_p2 = ((sub_ln194_1_fu_414_p2 == 12'd24) ? 1'b1 : 1'b0);

assign icmp_ln194_3_fu_487_p2 = ((select_ln194_1_reg_755 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln194_4_fu_532_p2 = (($signed(add_ln194_reg_750) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln194_5_fu_537_p2 = ((select_ln194_1_reg_755 < 12'd25) ? 1'b1 : 1'b0);

assign icmp_ln194_fu_409_p2 = ((trunc_ln194_reg_712 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln194_reg_738_pp0_iter11_reg = icmp_ln194_reg_738;

assign or_ln114_1_fu_306_p2 = (icmp_ln114_3_reg_664 | icmp_ln114_2_reg_659);

assign or_ln114_fu_327_p2 = (icmp_ln114_reg_678_pp0_iter9_reg | icmp_ln114_1_reg_683_pp0_iter9_reg);

assign or_ln194_fu_599_p2 = (icmp_ln194_reg_738_pp0_iter12_reg | icmp_ln194_2_reg_762_pp0_iter12_reg);

assign pf_fu_160_p0 = ((sm_inst_exp_has_infty_load_reg_692_pp0_iter9_reg[0:0] == 1'b1) ? select_ln193_fu_336_p3 : grp_fu_168_p2);

assign ret_fu_239_p3 = sm_inst_exp_cnt[32'd6];

assign select_ln193_fu_336_p3 = ((and_ln114_fu_331_p2[0:0] == 1'b1) ? 32'd1065353216 : 32'd0);

assign select_ln194_1_fu_442_p3 = ((icmp_ln194_1_fu_424_p2[0:0] == 1'b1) ? add_ln194_fu_430_p2 : sub_ln194_2_fu_436_p2);

assign select_ln194_2_fu_524_p3 = ((icmp_ln194_3_fu_487_p2[0:0] == 1'b1) ? trunc_ln194_4_fu_520_p1 : select_ln194_8_fu_503_p3);

assign select_ln194_3_fu_551_p3 = ((icmp_ln194_5_fu_537_p2[0:0] == 1'b1) ? shl_ln194_fu_546_p2 : 25'd0);

assign select_ln194_4_fu_559_p3 = ((icmp_ln194_4_fu_532_p2[0:0] == 1'b1) ? tmp_1_reg_717_pp0_iter11_reg : bit_select59_i_i_reg_774);

assign select_ln194_5_fu_575_p3 = ((icmp_ln194_reg_738[0:0] == 1'b1) ? 25'd0 : select_ln194_3_fu_551_p3);

assign select_ln194_6_fu_592_p3 = ((and_ln194_fu_587_p2[0:0] == 1'b1) ? trunc_ln194_3_reg_768 : select_ln194_5_fu_575_p3);

assign select_ln194_7_fu_614_p3 = ((and_ln194_1_fu_609_p2[0:0] == 1'b1) ? add_ln194_2_reg_779 : select_ln194_6_reg_784);

assign select_ln194_8_fu_503_p3 = ((tmp_2_fu_495_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln194_fu_402_p3 = ((tmp_1_reg_717[0:0] == 1'b1) ? sub_ln194_fu_396_p2 : zext_ln194_1_fu_392_p1);

assign sext_ln194_fu_484_p1 = select_ln194_1_reg_755;

assign sext_ln194cast_fu_542_p1 = sext_ln194_fu_484_p1[24:0];

assign shl_ln194_fu_546_p2 = trunc_ln194_3_reg_768 << sext_ln194cast_fu_542_p1;

assign sm_inst_exp2div_dat_din = select_ln194_7_fu_614_p3;

assign sm_inst_exp2div_sum_din = (sm_inst_exp_total + zext_ln196_1_fu_629_p1);

assign sm_inst_exp_valid_load_reg_646_pp0_iter0_reg = sm_inst_exp_valid_load_reg_646;

assign sub_ln194_1_fu_414_p2 = (12'd1075 - zext_ln194_fu_382_p1);

assign sub_ln194_2_fu_436_p2 = (12'd24 - sub_ln194_1_fu_414_p2);

assign sub_ln194_fu_396_p2 = (54'd0 - zext_ln194_1_fu_392_p1);

assign tmp_1_i_nbreadreq_fu_114_p3 = sm_inst_max2exp_max_empty_n;

assign tmp_1_i_reg_650_pp0_iter0_reg = tmp_1_i_reg_650;

assign tmp_2_fu_495_p3 = bitcast_ln724_1_fu_492_p1[32'd31];

assign tmp_4_fu_209_p4 = {{sm_inst_max2exp_dat_dout[30:23]}};

assign tmp_7_fu_247_p3 = sm_inst_exp_cnt[32'd6];

assign tmp_fu_177_p4 = {{sm_inst_max2exp_max_dout[30:23]}};

assign tmp_i_nbreadreq_fu_128_p3 = sm_inst_max2exp_dat_empty_n;

assign tmp_i_reg_669_pp0_iter0_reg = tmp_i_reg_669;

assign trunc_ln114_1_fu_187_p1 = sm_inst_max2exp_max_dout[22:0];

assign trunc_ln114_fu_219_p1 = sm_inst_max2exp_dat_dout[22:0];

assign trunc_ln194_1_fu_378_p1 = bitcast_ln724_fu_352_p1[51:0];

assign trunc_ln194_2_fu_420_p1 = sub_ln194_1_fu_414_p2[10:0];

assign trunc_ln194_3_fu_456_p1 = select_ln194_fu_402_p3[24:0];

assign trunc_ln194_4_fu_520_p1 = ashr_ln194_fu_515_p2[24:0];

assign trunc_ln194_fu_356_p1 = bitcast_ln724_fu_352_p1[62:0];

assign x_assign_fu_156_p0 = sm_inst_max2exp_dat_read_reg_673;

assign xor_ln194_1_fu_603_p2 = (or_ln194_fu_599_p2 ^ 1'd1);

assign xor_ln194_fu_582_p2 = (icmp_ln194_reg_738 ^ 1'd1);

assign xx_fu_322_p1 = sm_inst_max2exp_dat_read_reg_673;

assign yy_fu_344_p3 = ((sm_inst_exp_has_infty_load_reg_692_pp0_iter9_reg[0:0] == 1'b1) ? select_ln193_fu_336_p3 : grp_fu_168_p2);

assign zext_ln194_1_cast_fu_385_p3 = {{1'd1}, {trunc_ln194_1_reg_728}};

assign zext_ln194_1_fu_392_p1 = zext_ln194_1_cast_fu_385_p3;

assign zext_ln194_2_fu_511_p1 = $unsigned(sext_ln194_fu_484_p1);

assign zext_ln194_4_fu_466_p1 = add_ln194_1_fu_460_p2;

assign zext_ln194_5_fu_565_p1 = select_ln194_4_fu_559_p3;

assign zext_ln194_fu_382_p1 = tmp_3_i6_reg_723;

assign zext_ln196_1_fu_629_p1 = select_ln194_7_fu_614_p3;

endmodule //softmax_top_exponentiate
