// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module DuplicateStreams_hls_1_StreamingDup_vector_vector_vector_ap_int_8_8ul_vector_ap_int_8_8ul_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        out0_V_TREADY,
        out1_V_TREADY,
        out2_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out0_V_TDATA,
        out0_V_TVALID,
        out1_V_TDATA,
        out1_V_TVALID,
        out2_V_TDATA,
        out2_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   out0_V_TREADY;
input   out1_V_TREADY;
input   out2_V_TREADY;
input  [63:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [63:0] out0_V_TDATA;
output   out0_V_TVALID;
output  [63:0] out1_V_TDATA;
output   out1_V_TVALID;
output  [63:0] out2_V_TDATA;
output   out2_V_TVALID;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] tmp_nbreadreq_fu_32_p3;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] tmp_reg_67;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] tmp_reg_67_pp0_iter1_reg;
wire    regslice_both_out0_V_U_apdone_blk;
wire    regslice_both_out1_V_U_apdone_blk;
wire    regslice_both_out2_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg    in0_V_TDATA_blk_n;
reg    out0_V_TDATA_blk_n;
reg    out1_V_TDATA_blk_n;
reg    out2_V_TDATA_blk_n;
reg   [63:0] in0_V_read_reg_71;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [63:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
reg    out0_V_TVALID_int_regslice;
wire    out0_V_TREADY_int_regslice;
wire    regslice_both_out0_V_U_vld_out;
reg    out1_V_TVALID_int_regslice;
wire    out1_V_TREADY_int_regslice;
wire    regslice_both_out1_V_U_vld_out;
reg    out2_V_TVALID_int_regslice;
wire    out2_V_TREADY_int_regslice;
wire    regslice_both_out2_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

DuplicateStreams_hls_1_regslice_both #(
    .DataWidth( 64 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

DuplicateStreams_hls_1_regslice_both #(
    .DataWidth( 64 ))
regslice_both_out0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in0_V_read_reg_71),
    .vld_in(out0_V_TVALID_int_regslice),
    .ack_in(out0_V_TREADY_int_regslice),
    .data_out(out0_V_TDATA),
    .vld_out(regslice_both_out0_V_U_vld_out),
    .ack_out(out0_V_TREADY),
    .apdone_blk(regslice_both_out0_V_U_apdone_blk)
);

DuplicateStreams_hls_1_regslice_both #(
    .DataWidth( 64 ))
regslice_both_out1_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in0_V_read_reg_71),
    .vld_in(out1_V_TVALID_int_regslice),
    .ack_in(out1_V_TREADY_int_regslice),
    .data_out(out1_V_TDATA),
    .vld_out(regslice_both_out1_V_U_vld_out),
    .ack_out(out1_V_TREADY),
    .apdone_blk(regslice_both_out1_V_U_apdone_blk)
);

DuplicateStreams_hls_1_regslice_both #(
    .DataWidth( 64 ))
regslice_both_out2_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in0_V_read_reg_71),
    .vld_in(out2_V_TVALID_int_regslice),
    .ack_in(out2_V_TREADY_int_regslice),
    .data_out(out2_V_TDATA),
    .vld_out(regslice_both_out2_V_U_vld_out),
    .ack_out(out2_V_TREADY),
    .apdone_blk(regslice_both_out2_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_read_reg_71 <= in0_V_TDATA_int_regslice;
        tmp_reg_67 <= tmp_nbreadreq_fu_32_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        tmp_reg_67_pp0_iter1_reg <= tmp_reg_67;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage0_iter1)) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage0_iter2)) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (tmp_nbreadreq_fu_32_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_nbreadreq_fu_32_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_67_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((tmp_reg_67 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        out0_V_TDATA_blk_n = out0_V_TREADY_int_regslice;
    end else begin
        out0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_reg_67 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out0_V_TVALID_int_regslice = 1'b1;
    end else begin
        out0_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_67_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((tmp_reg_67 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        out1_V_TDATA_blk_n = out1_V_TREADY_int_regslice;
    end else begin
        out1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_reg_67 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out1_V_TVALID_int_regslice = 1'b1;
    end else begin
        out1_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_67_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((tmp_reg_67 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        out2_V_TDATA_blk_n = out2_V_TREADY_int_regslice;
    end else begin
        out2_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (tmp_reg_67 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out2_V_TVALID_int_regslice = 1'b1;
    end else begin
        out2_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter1_fsm_state2) & (1'b0 == ap_block_state2_pp0_stage0_iter1))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_32_p3 == 1'd1) & (in0_V_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((tmp_reg_67 == 1'd1) & (out2_V_TREADY_int_regslice == 1'b0)) | ((tmp_reg_67 == 1'd1) & (out1_V_TREADY_int_regslice == 1'b0)) | ((tmp_reg_67 == 1'd1) & (out0_V_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_out2_V_U_apdone_blk == 1'b1) | (regslice_both_out1_V_U_apdone_blk == 1'b1) | (regslice_both_out0_V_U_apdone_blk == 1'b1) | ((tmp_reg_67_pp0_iter1_reg == 1'd1) & (out2_V_TREADY_int_regslice == 1'b0)) | ((tmp_reg_67_pp0_iter1_reg == 1'd1) & (out1_V_TREADY_int_regslice == 1'b0)) | ((tmp_reg_67_pp0_iter1_reg == 1'd1) & (out0_V_TREADY_int_regslice == 1'b0)));
end

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign out0_V_TVALID = regslice_both_out0_V_U_vld_out;

assign out1_V_TVALID = regslice_both_out1_V_U_vld_out;

assign out2_V_TVALID = regslice_both_out2_V_U_vld_out;

assign tmp_nbreadreq_fu_32_p3 = in0_V_TVALID_int_regslice;

endmodule //DuplicateStreams_hls_1_StreamingDup_vector_vector_vector_ap_int_8_8ul_vector_ap_int_8_8ul_s
