// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="OuterShuffle_hls_1_OuterShuffle_hls_1,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.761125,HLS_SYN_LAT=5,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1018,HLS_SYN_LUT=603,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module OuterShuffle_hls_1 (
        in0_V_TDATA,
        out0_V_TDATA,
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        in0_V_TREADY,
        out0_V_TVALID,
        out0_V_TREADY
);


input  [127:0] in0_V_TDATA;
output  [127:0] out0_V_TDATA;
input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
output   in0_V_TREADY;
output   out0_V_TVALID;
input   out0_V_TREADY;

 reg    ap_rst_n_inv;
wire    move_vector_float_4ul_U0_ap_start;
wire    move_vector_float_4ul_U0_ap_done;
wire    move_vector_float_4ul_U0_ap_continue;
wire    move_vector_float_4ul_U0_ap_idle;
wire    move_vector_float_4ul_U0_ap_ready;
wire   [127:0] move_vector_float_4ul_U0_src0_din;
wire    move_vector_float_4ul_U0_src0_write;
wire    move_vector_float_4ul_U0_in0_V_TREADY;
wire    input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_start;
wire    input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_done;
wire    input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_continue;
wire    input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_idle;
wire    input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_ready;
wire    input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_src0_read;
wire   [127:0] input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_dst0_din;
wire    input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_dst0_write;
wire    move_vector_float_4ul_1_U0_ap_start;
wire    move_vector_float_4ul_1_U0_ap_done;
wire    move_vector_float_4ul_1_U0_ap_continue;
wire    move_vector_float_4ul_1_U0_ap_idle;
wire    move_vector_float_4ul_1_U0_ap_ready;
wire    move_vector_float_4ul_1_U0_dst0_read;
wire   [127:0] move_vector_float_4ul_1_U0_out0_V_TDATA;
wire    move_vector_float_4ul_1_U0_out0_V_TVALID;
wire    src0_full_n;
wire   [127:0] src0_dout;
wire    src0_empty_n;
wire   [2:0] src0_num_data_valid;
wire   [2:0] src0_fifo_cap;
wire    dst0_full_n;
wire   [127:0] dst0_dout;
wire    dst0_empty_n;
wire   [2:0] dst0_num_data_valid;
wire   [2:0] dst0_fifo_cap;

OuterShuffle_hls_1_move_vector_float_4ul_s move_vector_float_4ul_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(move_vector_float_4ul_U0_ap_start),
    .ap_done(move_vector_float_4ul_U0_ap_done),
    .ap_continue(move_vector_float_4ul_U0_ap_continue),
    .ap_idle(move_vector_float_4ul_U0_ap_idle),
    .ap_ready(move_vector_float_4ul_U0_ap_ready),
    .in0_V_TVALID(in0_V_TVALID),
    .src0_din(move_vector_float_4ul_U0_src0_din),
    .src0_full_n(src0_full_n),
    .src0_write(move_vector_float_4ul_U0_src0_write),
    .src0_num_data_valid(src0_num_data_valid),
    .src0_fifo_cap(src0_fifo_cap),
    .in0_V_TDATA(in0_V_TDATA),
    .in0_V_TREADY(move_vector_float_4ul_U0_in0_V_TREADY)
);

OuterShuffle_hls_1_input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_s input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_start),
    .ap_done(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_done),
    .ap_continue(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_continue),
    .ap_idle(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_idle),
    .ap_ready(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_ready),
    .src0_dout(src0_dout),
    .src0_empty_n(src0_empty_n),
    .src0_read(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_src0_read),
    .src0_num_data_valid(src0_num_data_valid),
    .src0_fifo_cap(src0_fifo_cap),
    .dst0_din(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_dst0_din),
    .dst0_full_n(dst0_full_n),
    .dst0_write(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_dst0_write),
    .dst0_num_data_valid(dst0_num_data_valid),
    .dst0_fifo_cap(dst0_fifo_cap)
);

OuterShuffle_hls_1_move_vector_float_4ul_1 move_vector_float_4ul_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(move_vector_float_4ul_1_U0_ap_start),
    .ap_done(move_vector_float_4ul_1_U0_ap_done),
    .ap_continue(move_vector_float_4ul_1_U0_ap_continue),
    .ap_idle(move_vector_float_4ul_1_U0_ap_idle),
    .ap_ready(move_vector_float_4ul_1_U0_ap_ready),
    .dst0_dout(dst0_dout),
    .dst0_empty_n(dst0_empty_n),
    .dst0_read(move_vector_float_4ul_1_U0_dst0_read),
    .dst0_num_data_valid(dst0_num_data_valid),
    .dst0_fifo_cap(dst0_fifo_cap),
    .out0_V_TREADY(out0_V_TREADY),
    .out0_V_TDATA(move_vector_float_4ul_1_U0_out0_V_TDATA),
    .out0_V_TVALID(move_vector_float_4ul_1_U0_out0_V_TVALID)
);

OuterShuffle_hls_1_fifo_w128_d2_S src0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(move_vector_float_4ul_U0_src0_din),
    .if_full_n(src0_full_n),
    .if_write(move_vector_float_4ul_U0_src0_write),
    .if_dout(src0_dout),
    .if_empty_n(src0_empty_n),
    .if_read(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_src0_read),
    .if_num_data_valid(src0_num_data_valid),
    .if_fifo_cap(src0_fifo_cap)
);

OuterShuffle_hls_1_fifo_w128_d2_S dst0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_dst0_din),
    .if_full_n(dst0_full_n),
    .if_write(input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_dst0_write),
    .if_dout(dst0_dout),
    .if_empty_n(dst0_empty_n),
    .if_read(move_vector_float_4ul_1_U0_dst0_read),
    .if_num_data_valid(dst0_num_data_valid),
    .if_fifo_cap(dst0_fifo_cap)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign in0_V_TREADY = move_vector_float_4ul_U0_in0_V_TREADY;

assign input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_continue = 1'b1;

assign input_gen_1_12288u_1u_12288u_12u_8u_128u_96u_8u_1u_vector_U0_ap_start = 1'b1;

assign move_vector_float_4ul_1_U0_ap_continue = 1'b1;

assign move_vector_float_4ul_1_U0_ap_start = 1'b1;

assign move_vector_float_4ul_U0_ap_continue = 1'b1;

assign move_vector_float_4ul_U0_ap_start = 1'b1;

assign out0_V_TDATA = move_vector_float_4ul_1_U0_out0_V_TDATA;

assign out0_V_TVALID = move_vector_float_4ul_1_U0_out0_V_TVALID;

endmodule //OuterShuffle_hls_1
