// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="layernorm_top_layernorm_top,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=3.300000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.069000,HLS_SYN_LAT=77,HLS_SYN_TPT=5,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=10131,HLS_SYN_LUT=1019,HLS_VERSION=2023_1}" *)

module layernorm_top (
        src_TDATA,
        dst_TDATA,
        ap_clk,
        ap_rst_n,
        src_TVALID,
        src_TREADY,
        dst_TVALID,
        dst_TREADY
);


input  [127:0] src_TDATA;
output  [127:0] dst_TDATA;
input   ap_clk;
input   ap_rst_n;
input   src_TVALID;
output   src_TREADY;
output   dst_TVALID;
input   dst_TREADY;

wire   [127:0] layernorm_384ul_float_float_4ul_U0_dst_TDATA;
(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    layernorm_384ul_float_float_4ul_U0_src_TREADY;
wire    layernorm_384ul_float_float_4ul_U0_ap_start;
wire    layernorm_384ul_float_float_4ul_U0_dst_TVALID;
wire    layernorm_384ul_float_float_4ul_U0_ap_done;
wire    layernorm_384ul_float_float_4ul_U0_ap_ready;
wire    layernorm_384ul_float_float_4ul_U0_ap_idle;
wire    layernorm_384ul_float_float_4ul_U0_ap_continue;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
end

layernorm_top_layernorm_384ul_float_float_4ul_s layernorm_384ul_float_float_4ul_U0(
    .src_TDATA(src_TDATA),
    .dst_TDATA(layernorm_384ul_float_float_4ul_U0_dst_TDATA),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .src_TVALID(src_TVALID),
    .src_TREADY(layernorm_384ul_float_float_4ul_U0_src_TREADY),
    .ap_start(layernorm_384ul_float_float_4ul_U0_ap_start),
    .dst_TVALID(layernorm_384ul_float_float_4ul_U0_dst_TVALID),
    .dst_TREADY(dst_TREADY),
    .ap_done(layernorm_384ul_float_float_4ul_U0_ap_done),
    .ap_ready(layernorm_384ul_float_float_4ul_U0_ap_ready),
    .ap_idle(layernorm_384ul_float_float_4ul_U0_ap_idle),
    .ap_continue(layernorm_384ul_float_float_4ul_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign dst_TDATA = layernorm_384ul_float_float_4ul_U0_dst_TDATA;

assign dst_TVALID = layernorm_384ul_float_float_4ul_U0_dst_TVALID;

assign layernorm_384ul_float_float_4ul_U0_ap_continue = 1'b1;

assign layernorm_384ul_float_float_4ul_U0_ap_start = 1'b1;

assign src_TREADY = layernorm_384ul_float_float_4ul_U0_src_TREADY;

endmodule //layernorm_top
