// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module layernorm_top_var_stage_384ul_float_float_float_4ul_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stage2_s_din,
        stage2_s_num_data_valid,
        stage2_s_fifo_cap,
        stage2_s_full_n,
        stage2_s_write,
        var_s_din,
        var_s_num_data_valid,
        var_s_fifo_cap,
        var_s_full_n,
        var_s_write,
        mean_s_dout,
        mean_s_num_data_valid,
        mean_s_fifo_cap,
        mean_s_empty_n,
        mean_s_read,
        stage1_s_dout,
        stage1_s_num_data_valid,
        stage1_s_fifo_cap,
        stage1_s_empty_n,
        stage1_s_read
);

parameter    ap_ST_iter0_fsm_state1 = 5'd1;
parameter    ap_ST_iter0_fsm_state2 = 5'd8;
parameter    ap_ST_iter0_fsm_state3 = 5'd2;
parameter    ap_ST_iter0_fsm_state4 = 5'd4;
parameter    ap_ST_iter0_fsm_state5 = 5'd16;
parameter    ap_ST_iter1_fsm_state6 = 6'd2;
parameter    ap_ST_iter1_fsm_state7 = 6'd4;
parameter    ap_ST_iter1_fsm_state8 = 6'd8;
parameter    ap_ST_iter1_fsm_state9 = 6'd16;
parameter    ap_ST_iter1_fsm_state10 = 6'd32;
parameter    ap_ST_iter2_fsm_state11 = 6'd2;
parameter    ap_ST_iter2_fsm_state12 = 6'd4;
parameter    ap_ST_iter2_fsm_state13 = 6'd8;
parameter    ap_ST_iter2_fsm_state14 = 6'd16;
parameter    ap_ST_iter2_fsm_state15 = 6'd32;
parameter    ap_ST_iter3_fsm_state16 = 6'd2;
parameter    ap_ST_iter3_fsm_state17 = 6'd4;
parameter    ap_ST_iter3_fsm_state18 = 6'd8;
parameter    ap_ST_iter3_fsm_state19 = 6'd16;
parameter    ap_ST_iter3_fsm_state20 = 6'd32;
parameter    ap_ST_iter4_fsm_state21 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 6'd1;
parameter    ap_ST_iter2_fsm_state0 = 6'd1;
parameter    ap_ST_iter3_fsm_state0 = 6'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [127:0] stage2_s_din;
input  [7:0] stage2_s_num_data_valid;
input  [7:0] stage2_s_fifo_cap;
input   stage2_s_full_n;
output   stage2_s_write;
output  [31:0] var_s_din;
input  [1:0] var_s_num_data_valid;
input  [1:0] var_s_fifo_cap;
input   var_s_full_n;
output   var_s_write;
input  [31:0] mean_s_dout;
input  [1:0] mean_s_num_data_valid;
input  [1:0] mean_s_fifo_cap;
input   mean_s_empty_n;
output   mean_s_read;
input  [127:0] stage1_s_dout;
input  [7:0] stage1_s_num_data_valid;
input  [7:0] stage1_s_fifo_cap;
input   stage1_s_empty_n;
output   stage1_s_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stage2_s_write;
reg var_s_write;
reg mean_s_read;
reg stage1_s_read;

reg   [4:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [5:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [5:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [5:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
wire    ap_CS_iter0_fsm_state5;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state6;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_CS_iter1_fsm_state7;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_CS_iter1_fsm_state8;
wire    ap_block_state9_pp0_stage3_iter1;
wire    ap_CS_iter1_fsm_state9;
wire    ap_block_state10_pp0_stage4_iter1;
wire    ap_CS_iter1_fsm_state10;
wire    ap_block_state11_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state11;
wire    ap_block_state12_pp0_stage1_iter2;
wire    ap_CS_iter2_fsm_state12;
wire    ap_block_state13_pp0_stage2_iter2;
wire    ap_CS_iter2_fsm_state13;
wire    ap_block_state14_pp0_stage3_iter2;
wire    ap_CS_iter2_fsm_state14;
wire    ap_block_state15_pp0_stage4_iter2;
wire    ap_CS_iter2_fsm_state15;
wire    ap_block_state16_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state16;
wire    ap_block_state17_pp0_stage1_iter3;
wire    ap_CS_iter3_fsm_state17;
wire    ap_block_state18_pp0_stage2_iter3;
wire    ap_CS_iter3_fsm_state18;
wire    ap_block_state19_pp0_stage3_iter3;
wire    ap_CS_iter3_fsm_state19;
wire    ap_block_state20_pp0_stage4_iter3;
wire    ap_CS_iter3_fsm_state20;
reg   [0:0] tmp_i_reg_443;
reg   [0:0] tmp_i_reg_443_pp0_iter3_reg;
reg   [0:0] tmp_2_i_reg_450;
reg   [0:0] tmp_2_i_reg_450_pp0_iter3_reg;
reg   [0:0] valid_load_reg_439;
reg   [0:0] valid_load_reg_439_pp0_iter3_reg;
reg    ap_predicate_op128_write_state21;
reg   [0:0] ret_reg_520;
reg   [0:0] ret_reg_520_pp0_iter3_reg;
reg    ap_predicate_op131_write_state21;
reg    ap_block_state21_pp0_stage0_iter4;
wire    ap_CS_iter4_fsm_state21;
reg    ap_done_reg;
reg   [0:0] valid;
reg   [31:0] mean;
reg   [31:0] sumq;
reg   [7:0] count;
reg    stage1_s_blk_n;
wire   [0:0] tmp_i_nbreadreq_fu_86_p3;
wire   [0:0] tmp_2_i_nbreadreq_fu_100_p3;
wire   [0:0] valid_load_load_fu_268_p1;
reg    stage2_s_blk_n;
reg    var_s_blk_n;
reg   [0:0] valid_flag_0_i_reg_128;
reg    ap_predicate_op55_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] valid_load_reg_439_pp0_iter0_reg;
reg   [0:0] valid_load_reg_439_pp0_iter1_reg;
reg   [0:0] valid_load_reg_439_pp0_iter2_reg;
reg   [0:0] tmp_i_reg_443_pp0_iter0_reg;
reg   [0:0] tmp_i_reg_443_pp0_iter1_reg;
reg   [0:0] tmp_i_reg_443_pp0_iter2_reg;
reg   [0:0] tmp_2_i_reg_450_pp0_iter0_reg;
reg   [0:0] tmp_2_i_reg_450_pp0_iter1_reg;
reg   [0:0] tmp_2_i_reg_450_pp0_iter2_reg;
wire   [31:0] bitcast_ln92_fu_294_p1;
wire   [31:0] bitcast_ln92_1_fu_309_p1;
wire   [31:0] bitcast_ln92_2_fu_324_p1;
wire   [31:0] bitcast_ln92_3_fu_339_p1;
reg   [31:0] grp_fu_233_p2;
wire    ap_CS_iter0_fsm_state2;
wire    ap_block_state2_pp0_stage3_iter0;
reg   [31:0] grp_fu_239_p2;
wire   [31:0] grp_fu_208_p2;
reg   [31:0] xm_reg_492;
wire    ap_CS_iter0_fsm_state3;
wire    ap_block_state3_pp0_stage1_iter0;
reg   [31:0] xm_reg_492_pp0_iter0_reg;
reg   [31:0] xm_reg_492_pp0_iter1_reg;
reg   [31:0] xm_reg_492_pp0_iter2_reg;
reg   [31:0] xm_reg_492_pp0_iter3_reg;
wire   [31:0] grp_fu_212_p2;
reg   [31:0] xm_1_reg_499;
reg   [31:0] xm_1_reg_499_pp0_iter0_reg;
reg   [31:0] xm_1_reg_499_pp0_iter1_reg;
reg   [31:0] xm_1_reg_499_pp0_iter2_reg;
reg   [31:0] xm_1_reg_499_pp0_iter3_reg;
wire   [31:0] grp_fu_216_p2;
reg   [31:0] xm_2_reg_506;
reg   [31:0] xm_2_reg_506_pp0_iter0_reg;
reg   [31:0] xm_2_reg_506_pp0_iter1_reg;
reg   [31:0] xm_2_reg_506_pp0_iter2_reg;
reg   [31:0] xm_2_reg_506_pp0_iter3_reg;
wire   [31:0] grp_fu_220_p2;
reg   [31:0] xm_3_reg_513;
reg   [31:0] xm_3_reg_513_pp0_iter0_reg;
reg   [31:0] xm_3_reg_513_pp0_iter1_reg;
reg   [31:0] xm_3_reg_513_pp0_iter2_reg;
reg   [31:0] xm_3_reg_513_pp0_iter3_reg;
wire   [0:0] ret_fu_356_p3;
wire   [0:0] ret_reg_520_pp0_iter0_reg;
reg   [0:0] ret_reg_520_pp0_iter1_reg;
reg   [0:0] ret_reg_520_pp0_iter2_reg;
wire   [31:0] add_i_fu_228_p2;
reg   [31:0] add_i_reg_524;
reg   [0:0] ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_128;
reg   [0:0] ap_phi_mux_valid_flag_1_i_phi_fu_146_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_valid_flag_1_i_reg_142;
reg   [0:0] ap_phi_reg_pp0_iter1_valid_flag_1_i_reg_142;
reg   [0:0] ap_phi_mux_valid_new_1_i_phi_fu_158_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_valid_new_1_i_reg_154;
reg   [0:0] ap_phi_reg_pp0_iter1_valid_new_1_i_reg_154;
reg   [0:0] ap_phi_mux_valid_flag_2_i_phi_fu_170_p6;
reg   [0:0] ap_phi_reg_pp0_iter1_valid_flag_2_i_reg_166;
wire   [0:0] ap_phi_reg_pp0_iter0_valid_flag_2_i_reg_166;
reg   [0:0] ap_phi_mux_valid_new_2_i_phi_fu_186_p6;
reg   [0:0] ap_phi_reg_pp0_iter1_valid_new_2_i_reg_181;
wire   [0:0] ap_phi_reg_pp0_iter0_valid_new_2_i_reg_181;
wire   [31:0] ap_phi_reg_pp0_iter0_sumq_new_0_i_reg_197;
reg   [31:0] ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_197;
reg   [0:0] ap_sig_allocacmp_valid_load;
wire   [31:0] bitcast_ln87_fu_280_p1;
wire   [0:0] p_vld_fu_272_p1;
reg   [31:0] ap_sig_allocacmp_mean_load;
wire   [7:0] add_ln72_fu_380_p2;
wire   [0:0] mean_s_read_nbread_fu_94_p2_0;
reg   [31:0] grp_fu_208_p0;
reg   [31:0] grp_fu_208_p1;
reg   [31:0] grp_fu_212_p0;
reg   [31:0] grp_fu_212_p1;
reg   [31:0] grp_fu_216_p0;
reg   [31:0] grp_fu_216_p1;
reg   [31:0] grp_fu_220_p0;
reg   [31:0] grp_fu_220_p1;
wire   [31:0] grp_fu_259_p4;
wire   [31:0] grp_fu_250_p4;
wire   [31:0] add_i2_i_fu_224_p2;
reg   [31:0] grp_fu_233_p0;
reg   [31:0] grp_fu_233_p1;
reg   [31:0] grp_fu_239_p0;
reg   [31:0] grp_fu_239_p1;
wire   [31:0] trunc_ln92_fu_290_p1;
wire   [31:0] tmp_3_i6_fu_299_p4;
wire   [31:0] tmp_4_i7_fu_314_p4;
wire   [31:0] tmp_5_i8_fu_329_p4;
wire   [0:0] tmp_fu_364_p3;
wire   [7:0] select_ln72_fu_372_p3;
wire   [31:0] bitcast_ln103_3_fu_418_p1;
wire   [31:0] bitcast_ln103_2_fu_415_p1;
wire   [31:0] bitcast_ln103_1_fu_412_p1;
wire   [31:0] bitcast_ln103_fu_409_p1;
wire   [31:0] grp_fu_245_p2;
reg    grp_fu_233_ce;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_CS_iter0_fsm_state4;
wire   [31:0] pre_grp_fu_233_p2;
reg   [31:0] pre_grp_fu_233_p2_reg;
reg    grp_fu_239_ce;
wire   [31:0] pre_grp_fu_239_p2;
reg   [31:0] pre_grp_fu_239_p2_reg;
reg    grp_fu_245_ce;
reg    grp_fu_250_ce;
reg    grp_fu_259_ce;
reg   [4:0] ap_NS_iter0_fsm;
reg   [5:0] ap_NS_iter1_fsm;
reg   [5:0] ap_NS_iter2_fsm;
reg   [5:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter0_fsm_state2_blk;
wire    ap_ST_iter0_fsm_state3_blk;
wire    ap_ST_iter0_fsm_state4_blk;
wire    ap_ST_iter0_fsm_state5_blk;
wire    ap_ST_iter1_fsm_state6_blk;
wire    ap_ST_iter1_fsm_state7_blk;
wire    ap_ST_iter1_fsm_state8_blk;
wire    ap_ST_iter1_fsm_state9_blk;
wire    ap_ST_iter1_fsm_state10_blk;
wire    ap_ST_iter2_fsm_state11_blk;
wire    ap_ST_iter2_fsm_state12_blk;
wire    ap_ST_iter2_fsm_state13_blk;
wire    ap_ST_iter2_fsm_state14_blk;
wire    ap_ST_iter2_fsm_state15_blk;
wire    ap_ST_iter3_fsm_state16_blk;
wire    ap_ST_iter3_fsm_state17_blk;
wire    ap_ST_iter3_fsm_state18_blk;
wire    ap_ST_iter3_fsm_state19_blk;
wire    ap_ST_iter3_fsm_state20_blk;
reg    ap_ST_iter4_fsm_state21_blk;
reg    ap_condition_766;
reg    ap_condition_769;
reg    ap_condition_208;
reg    ap_condition_388;
reg    ap_condition_209;
reg    ap_condition_404;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 5'd1;
#0 ap_CS_iter1_fsm = 6'd1;
#0 ap_CS_iter2_fsm = 6'd1;
#0 ap_CS_iter3_fsm = 6'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 valid = 1'd0;
#0 mean = 32'd0;
#0 sumq = 32'd0;
#0 count = 8'd94;
end

layernorm_top_fsub_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_1_primitive_dsp_1_U12(
    .din0(grp_fu_208_p0),
    .din1(grp_fu_208_p1),
    .dout(grp_fu_208_p2)
);

layernorm_top_fsub_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_1_primitive_dsp_1_U13(
    .din0(grp_fu_212_p0),
    .din1(grp_fu_212_p1),
    .dout(grp_fu_212_p2)
);

layernorm_top_fsub_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_1_primitive_dsp_1_U14(
    .din0(grp_fu_216_p0),
    .din1(grp_fu_216_p1),
    .dout(grp_fu_216_p2)
);

layernorm_top_fsub_32ns_32ns_32_1_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_1_primitive_dsp_1_U15(
    .din0(grp_fu_220_p0),
    .din1(grp_fu_220_p1),
    .dout(grp_fu_220_p2)
);

layernorm_top_fadd_32ns_32ns_32_1_primitive_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_primitive_dsp_1_x_U16(
    .din0(grp_fu_259_p4),
    .din1(grp_fu_250_p4),
    .dout(add_i2_i_fu_224_p2)
);

layernorm_top_fadd_32ns_32ns_32_1_primitive_dsp_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_primitive_dsp_1_x_U17(
    .din0(sumq),
    .din1(add_i2_i_fu_224_p2),
    .dout(add_i_fu_228_p2)
);

layernorm_top_fmul_32ns_32ns_32_2_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_primitive_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_233_p0),
    .din1(grp_fu_233_p1),
    .ce(grp_fu_233_ce),
    .dout(pre_grp_fu_233_p2)
);

layernorm_top_fmul_32ns_32ns_32_2_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_primitive_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_239_p0),
    .din1(grp_fu_239_p1),
    .ce(grp_fu_239_ce),
    .dout(pre_grp_fu_239_p2)
);

layernorm_top_fdiv_32ns_32ns_32_15_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_15_no_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_i_reg_524),
    .din1(32'd1136656384),
    .ce(grp_fu_245_ce),
    .dout(grp_fu_245_p2)
);

layernorm_top_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(xm_2_reg_506),
    .din2(xm_2_reg_506),
    .din3(grp_fu_239_p2),
    .ce(grp_fu_250_ce),
    .dout(grp_fu_250_p4)
);

layernorm_top_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(xm_reg_492),
    .din2(xm_reg_492),
    .din3(grp_fu_233_p2),
    .ce(grp_fu_259_ce),
    .dout(grp_fu_259_p4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter4_fsm_state21))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        count <= 8'd94;
    end else begin
        if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state5) & (((valid_load_reg_439 == 1'd1) & (tmp_2_i_reg_450 == 1'd1)) | ((tmp_2_i_reg_450 == 1'd1) & (tmp_i_reg_443 == 1'd1))))) begin
            count <= add_ln72_fu_380_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        sumq <= 32'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state7) & (((tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (valid_load_reg_439_pp0_iter0_reg == 1'd1)) | ((tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (tmp_i_reg_443_pp0_iter0_reg == 1'd1))))) begin
            sumq <= ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_197;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        valid <= 1'd0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state6) & (ap_phi_mux_valid_flag_2_i_phi_fu_170_p6 == 1'd1))) begin
            valid <= ap_phi_mux_valid_new_2_i_phi_fu_186_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2) & (valid_load_reg_439 == 1'd0) & (tmp_i_reg_443 == 1'd1))) begin
        ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_128 <= 1'd1;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_sig_allocacmp_valid_load == 1'd1))) begin
        ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_128 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_208)) begin
        if ((1'b1 == ap_condition_769)) begin
            ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_197 <= add_i_fu_228_p2;
        end else if ((1'b1 == ap_condition_766)) begin
            ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_197 <= 32'd0;
        end else if ((1'b1 == ap_CS_iter0_fsm_state5)) begin
            ap_phi_reg_pp0_iter1_sumq_new_0_i_reg_197 <= ap_phi_reg_pp0_iter0_sumq_new_0_i_reg_197;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_209)) begin
        if ((1'b1 == ap_condition_388)) begin
            ap_phi_reg_pp0_iter1_valid_flag_1_i_reg_142 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_valid_flag_1_i_reg_142 <= ap_phi_reg_pp0_iter0_valid_flag_1_i_reg_142;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_209)) begin
        if ((1'b1 == ap_condition_404)) begin
            ap_phi_reg_pp0_iter1_valid_flag_2_i_reg_166 <= ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_128;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_valid_flag_2_i_reg_166 <= ap_phi_reg_pp0_iter0_valid_flag_2_i_reg_166;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_209)) begin
        if ((1'b1 == ap_condition_388)) begin
            ap_phi_reg_pp0_iter1_valid_new_1_i_reg_154 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_valid_new_1_i_reg_154 <= ap_phi_reg_pp0_iter0_valid_new_1_i_reg_154;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_209)) begin
        if ((1'b1 == ap_condition_404)) begin
            ap_phi_reg_pp0_iter1_valid_new_2_i_reg_181 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_valid_new_2_i_reg_181 <= ap_phi_reg_pp0_iter0_valid_new_2_i_reg_181;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        grp_fu_233_ce <= 1'b1;
    end else begin
        grp_fu_233_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state3)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        grp_fu_239_ce <= 1'b1;
    end else begin
        grp_fu_239_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state6) & (((tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (valid_load_reg_439_pp0_iter0_reg == 1'd1)) | ((tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (tmp_i_reg_443_pp0_iter0_reg == 1'd1))))) begin
        add_i_reg_524 <= add_i_fu_228_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        grp_fu_208_p0 <= bitcast_ln92_fu_294_p1;
        grp_fu_208_p1 <= ap_sig_allocacmp_mean_load;
        grp_fu_212_p0 <= bitcast_ln92_1_fu_309_p1;
        grp_fu_212_p1 <= ap_sig_allocacmp_mean_load;
        grp_fu_216_p0 <= bitcast_ln92_2_fu_324_p1;
        grp_fu_216_p1 <= ap_sig_allocacmp_mean_load;
        grp_fu_220_p0 <= bitcast_ln92_3_fu_339_p1;
        grp_fu_220_p1 <= ap_sig_allocacmp_mean_load;
        valid_load_reg_439 <= ap_sig_allocacmp_valid_load;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_iter0_fsm_state3)) begin
        grp_fu_233_p0 <= grp_fu_212_p2;
        grp_fu_233_p1 <= grp_fu_212_p2;
        grp_fu_239_p0 <= grp_fu_220_p2;
        grp_fu_239_p1 <= grp_fu_220_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (p_vld_fu_272_p1 == 1'd1) & (valid_load_load_fu_268_p1 == 1'd0) & (tmp_i_nbreadreq_fu_86_p3 == 1'd1))) begin
        mean <= bitcast_ln87_fu_280_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_233_ce == 1'b1)) begin
        pre_grp_fu_233_p2_reg <= pre_grp_fu_233_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_239_ce == 1'b1)) begin
        pre_grp_fu_239_p2_reg <= pre_grp_fu_239_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state5) & (((valid_load_reg_439 == 1'd1) & (tmp_2_i_reg_450 == 1'd1)) | ((tmp_2_i_reg_450 == 1'd1) & (tmp_i_reg_443 == 1'd1))))) begin
        ret_reg_520 <= count[32'd7];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state10))) begin
        ret_reg_520_pp0_iter1_reg <= ret_reg_520;
        tmp_2_i_reg_450_pp0_iter1_reg <= tmp_2_i_reg_450_pp0_iter0_reg;
        tmp_i_reg_443_pp0_iter1_reg <= tmp_i_reg_443_pp0_iter0_reg;
        valid_load_reg_439_pp0_iter1_reg <= valid_load_reg_439_pp0_iter0_reg;
        xm_1_reg_499_pp0_iter1_reg <= xm_1_reg_499_pp0_iter0_reg;
        xm_2_reg_506_pp0_iter1_reg <= xm_2_reg_506_pp0_iter0_reg;
        xm_3_reg_513_pp0_iter1_reg <= xm_3_reg_513_pp0_iter0_reg;
        xm_reg_492_pp0_iter1_reg <= xm_reg_492_pp0_iter0_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state15))) begin
        ret_reg_520_pp0_iter2_reg <= ret_reg_520_pp0_iter1_reg;
        tmp_2_i_reg_450_pp0_iter2_reg <= tmp_2_i_reg_450_pp0_iter1_reg;
        tmp_i_reg_443_pp0_iter2_reg <= tmp_i_reg_443_pp0_iter1_reg;
        valid_load_reg_439_pp0_iter2_reg <= valid_load_reg_439_pp0_iter1_reg;
        xm_1_reg_499_pp0_iter2_reg <= xm_1_reg_499_pp0_iter1_reg;
        xm_2_reg_506_pp0_iter2_reg <= xm_2_reg_506_pp0_iter1_reg;
        xm_3_reg_513_pp0_iter2_reg <= xm_3_reg_513_pp0_iter1_reg;
        xm_reg_492_pp0_iter2_reg <= xm_reg_492_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state20))) begin
        ret_reg_520_pp0_iter3_reg <= ret_reg_520_pp0_iter2_reg;
        tmp_2_i_reg_450_pp0_iter3_reg <= tmp_2_i_reg_450_pp0_iter2_reg;
        tmp_i_reg_443_pp0_iter3_reg <= tmp_i_reg_443_pp0_iter2_reg;
        valid_load_reg_439_pp0_iter3_reg <= valid_load_reg_439_pp0_iter2_reg;
        xm_1_reg_499_pp0_iter3_reg <= xm_1_reg_499_pp0_iter2_reg;
        xm_2_reg_506_pp0_iter3_reg <= xm_2_reg_506_pp0_iter2_reg;
        xm_3_reg_513_pp0_iter3_reg <= xm_3_reg_513_pp0_iter2_reg;
        xm_reg_492_pp0_iter3_reg <= xm_reg_492_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & ((ap_sig_allocacmp_valid_load == 1'd1) | (tmp_i_nbreadreq_fu_86_p3 == 1'd1)))) begin
        tmp_2_i_reg_450 <= tmp_2_i_nbreadreq_fu_100_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state5))) begin
        tmp_2_i_reg_450_pp0_iter0_reg <= tmp_2_i_reg_450;
        tmp_i_reg_443_pp0_iter0_reg <= tmp_i_reg_443;
        valid_flag_0_i_reg_128 <= ap_phi_reg_pp0_iter0_valid_flag_0_i_reg_128;
        valid_load_reg_439_pp0_iter0_reg <= valid_load_reg_439;
        xm_1_reg_499_pp0_iter0_reg <= xm_1_reg_499;
        xm_2_reg_506_pp0_iter0_reg <= xm_2_reg_506;
        xm_3_reg_513_pp0_iter0_reg <= xm_3_reg_513;
        xm_reg_492_pp0_iter0_reg <= xm_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (valid_load_load_fu_268_p1 == 1'd0))) begin
        tmp_i_reg_443 <= tmp_i_nbreadreq_fu_86_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state3) & (((valid_load_reg_439 == 1'd1) & (tmp_2_i_reg_450 == 1'd1)) | ((tmp_2_i_reg_450 == 1'd1) & (tmp_i_reg_443 == 1'd1))))) begin
        xm_1_reg_499 <= grp_fu_212_p2;
        xm_2_reg_506 <= grp_fu_216_p2;
        xm_3_reg_513 <= grp_fu_220_p2;
        xm_reg_492 <= grp_fu_208_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter0_fsm_state2_blk = 1'b0;

assign ap_ST_iter0_fsm_state3_blk = 1'b0;

assign ap_ST_iter0_fsm_state4_blk = 1'b0;

assign ap_ST_iter0_fsm_state5_blk = 1'b0;

assign ap_ST_iter1_fsm_state10_blk = 1'b0;

assign ap_ST_iter1_fsm_state6_blk = 1'b0;

assign ap_ST_iter1_fsm_state7_blk = 1'b0;

assign ap_ST_iter1_fsm_state8_blk = 1'b0;

assign ap_ST_iter1_fsm_state9_blk = 1'b0;

assign ap_ST_iter2_fsm_state11_blk = 1'b0;

assign ap_ST_iter2_fsm_state12_blk = 1'b0;

assign ap_ST_iter2_fsm_state13_blk = 1'b0;

assign ap_ST_iter2_fsm_state14_blk = 1'b0;

assign ap_ST_iter2_fsm_state15_blk = 1'b0;

assign ap_ST_iter3_fsm_state16_blk = 1'b0;

assign ap_ST_iter3_fsm_state17_blk = 1'b0;

assign ap_ST_iter3_fsm_state18_blk = 1'b0;

assign ap_ST_iter3_fsm_state19_blk = 1'b0;

assign ap_ST_iter3_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0)))) begin
        ap_ST_iter4_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_iter4_fsm_state21_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter4_fsm_state21))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((ret_reg_520_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (valid_load_reg_439_pp0_iter0_reg == 1'd1)) | ((ret_reg_520_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (tmp_i_reg_443_pp0_iter0_reg == 1'd1)))) begin
        ap_phi_mux_valid_flag_1_i_phi_fu_146_p4 = valid_flag_0_i_reg_128;
    end else begin
        ap_phi_mux_valid_flag_1_i_phi_fu_146_p4 = ap_phi_reg_pp0_iter1_valid_flag_1_i_reg_142;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (valid_load_reg_439_pp0_iter0_reg == 1'd1)) | ((tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (tmp_i_reg_443_pp0_iter0_reg == 1'd1)))) begin
        ap_phi_mux_valid_flag_2_i_phi_fu_170_p6 = ap_phi_mux_valid_flag_1_i_phi_fu_146_p4;
    end else begin
        ap_phi_mux_valid_flag_2_i_phi_fu_170_p6 = ap_phi_reg_pp0_iter1_valid_flag_2_i_reg_166;
    end
end

always @ (*) begin
    if ((((ret_reg_520_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (valid_load_reg_439_pp0_iter0_reg == 1'd1)) | ((ret_reg_520_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (tmp_i_reg_443_pp0_iter0_reg == 1'd1)))) begin
        ap_phi_mux_valid_new_1_i_phi_fu_158_p4 = 1'd1;
    end else begin
        ap_phi_mux_valid_new_1_i_phi_fu_158_p4 = ap_phi_reg_pp0_iter1_valid_new_1_i_reg_154;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (valid_load_reg_439_pp0_iter0_reg == 1'd1)) | ((tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (tmp_i_reg_443_pp0_iter0_reg == 1'd1)))) begin
        ap_phi_mux_valid_new_2_i_phi_fu_186_p6 = ap_phi_mux_valid_new_1_i_phi_fu_158_p4;
    end else begin
        ap_phi_mux_valid_new_2_i_phi_fu_186_p6 = ap_phi_reg_pp0_iter1_valid_new_2_i_reg_181;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (p_vld_fu_272_p1 == 1'd1) & (ap_start == 1'b1) & (valid_load_load_fu_268_p1 == 1'd0) & (tmp_i_nbreadreq_fu_86_p3 == 1'd1))) begin
        ap_sig_allocacmp_mean_load = bitcast_ln87_fu_280_p1;
    end else begin
        ap_sig_allocacmp_mean_load = mean;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state6) & (ap_phi_mux_valid_flag_2_i_phi_fu_170_p6 == 1'd1))) begin
        ap_sig_allocacmp_valid_load = ap_phi_mux_valid_new_2_i_phi_fu_186_p6;
    end else begin
        ap_sig_allocacmp_valid_load = valid;
    end
end

always @ (*) begin
    if ((grp_fu_233_ce == 1'b1)) begin
        grp_fu_233_p2 = pre_grp_fu_233_p2;
    end else begin
        grp_fu_233_p2 = pre_grp_fu_233_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_239_ce == 1'b1)) begin
        grp_fu_239_p2 = pre_grp_fu_239_p2;
    end else begin
        grp_fu_239_p2 = pre_grp_fu_239_p2_reg;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter4_fsm_state21)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state8)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state7)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state20)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) 
    & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state19)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state18)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state17)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state16)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 
    == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state15)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state14)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state13)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state12)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n 
    == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state11)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state10)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state9)))) begin
        grp_fu_245_ce = 1'b1;
    end else begin
        grp_fu_245_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state6)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state5)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        grp_fu_250_ce = 1'b1;
    end else begin
        grp_fu_250_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state6)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state5)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        grp_fu_259_ce = 1'b1;
    end else begin
        grp_fu_259_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (valid_load_load_fu_268_p1 == 1'd0) & (tmp_i_nbreadreq_fu_86_p3 == 1'd1) & (mean_s_empty_n == 1'b1))) begin
        mean_s_read = 1'b1;
    end else begin
        mean_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1) & (((ap_sig_allocacmp_valid_load == 1'd1) & (tmp_2_i_nbreadreq_fu_100_p3 == 1'd1)) | ((tmp_2_i_nbreadreq_fu_100_p3 == 1'd1) & (tmp_i_nbreadreq_fu_86_p3 == 1'd1))))) begin
        stage1_s_blk_n = stage1_s_empty_n;
    end else begin
        stage1_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op55_read_state1 == 1'b1))) begin
        stage1_s_read = 1'b1;
    end else begin
        stage1_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state21) & (ap_predicate_op128_write_state21 == 1'b1))) begin
        stage2_s_blk_n = stage2_s_full_n;
    end else begin
        stage2_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter4_fsm_state21) & (ap_predicate_op128_write_state21 == 1'b1))) begin
        stage2_s_write = 1'b1;
    end else begin
        stage2_s_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state21) & (ap_predicate_op131_write_state21 == 1'b1))) begin
        var_s_blk_n = var_s_full_n;
    end else begin
        var_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter4_fsm_state21) & (ap_predicate_op131_write_state21 == 1'b1))) begin
        var_s_write = 1'b1;
    end else begin
        var_s_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state3;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end
        end
        ap_ST_iter0_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state5;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end
        end
        ap_ST_iter0_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state4;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state3;
            end
        end
        ap_ST_iter0_fsm_state4 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state4))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state4;
            end
        end
        ap_ST_iter0_fsm_state5 : begin
            if (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0)))))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state5;
            end
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state6 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state6))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state7;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state6;
            end
        end
        ap_ST_iter1_fsm_state7 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state7))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state8;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state7;
            end
        end
        ap_ST_iter1_fsm_state8 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state8))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state9;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state8;
            end
        end
        ap_ST_iter1_fsm_state9 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state9))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state10;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state9;
            end
        end
        ap_ST_iter1_fsm_state10 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state5))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state6;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b0 == ap_CS_iter0_fsm_state5))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state10;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state5))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state6;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state11 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state11))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state12;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state11;
            end
        end
        ap_ST_iter2_fsm_state12 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state12))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state13;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state12;
            end
        end
        ap_ST_iter2_fsm_state13 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state13))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state14;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state13;
            end
        end
        ap_ST_iter2_fsm_state14 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state14))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state15;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state14;
            end
        end
        ap_ST_iter2_fsm_state15 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state10))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state11;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b0 == ap_CS_iter1_fsm_state10))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state15;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter1_fsm_state10))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state11;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state16 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state16))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state17;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state16;
            end
        end
        ap_ST_iter3_fsm_state17 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state17))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state18;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state17;
            end
        end
        ap_ST_iter3_fsm_state18 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state18))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state19;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state18;
            end
        end
        ap_ST_iter3_fsm_state19 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state19))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state20;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state19;
            end
        end
        ap_ST_iter3_fsm_state20 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state15))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state16;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b0 == ap_CS_iter2_fsm_state15))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state20;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter2_fsm_state15))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state16;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state21 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b1 == ap_CS_iter3_fsm_state20))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state21;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))) & (1'b0 == ap_CS_iter3_fsm_state20))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state21;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter3_fsm_state20))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state21;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

assign add_ln72_fu_380_p2 = (select_ln72_fu_372_p3 + count);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter0_fsm_state2 = ap_CS_iter0_fsm[32'd3];

assign ap_CS_iter0_fsm_state3 = ap_CS_iter0_fsm[32'd1];

assign ap_CS_iter0_fsm_state4 = ap_CS_iter0_fsm[32'd2];

assign ap_CS_iter0_fsm_state5 = ap_CS_iter0_fsm[32'd4];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state10 = ap_CS_iter1_fsm[32'd5];

assign ap_CS_iter1_fsm_state6 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter1_fsm_state7 = ap_CS_iter1_fsm[32'd2];

assign ap_CS_iter1_fsm_state8 = ap_CS_iter1_fsm[32'd3];

assign ap_CS_iter1_fsm_state9 = ap_CS_iter1_fsm[32'd4];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state11 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter2_fsm_state12 = ap_CS_iter2_fsm[32'd2];

assign ap_CS_iter2_fsm_state13 = ap_CS_iter2_fsm[32'd3];

assign ap_CS_iter2_fsm_state14 = ap_CS_iter2_fsm[32'd4];

assign ap_CS_iter2_fsm_state15 = ap_CS_iter2_fsm[32'd5];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state16 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter3_fsm_state17 = ap_CS_iter3_fsm[32'd2];

assign ap_CS_iter3_fsm_state18 = ap_CS_iter3_fsm[32'd3];

assign ap_CS_iter3_fsm_state19 = ap_CS_iter3_fsm[32'd4];

assign ap_CS_iter3_fsm_state20 = ap_CS_iter3_fsm[32'd5];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state21 = ap_CS_iter4_fsm[32'd1];

assign ap_block_state10_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op55_read_state1 == 1'b1) & (stage1_s_empty_n == 1'b0)));
end

assign ap_block_state20_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state21_pp0_stage0_iter4 = (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0)));
end

assign ap_block_state2_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_208 = ~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0)))));
end

always @ (*) begin
    ap_condition_209 = (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter4_fsm_state21) & (((ap_predicate_op131_write_state21 == 1'b1) & (var_s_full_n == 1'b0)) | ((ap_predicate_op128_write_state21 == 1'b1) & (stage2_s_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state5));
end

always @ (*) begin
    ap_condition_388 = (((ret_fu_356_p3 == 1'd1) & (valid_load_reg_439 == 1'd1) & (tmp_2_i_reg_450 == 1'd1)) | ((ret_fu_356_p3 == 1'd1) & (tmp_2_i_reg_450 == 1'd1) & (tmp_i_reg_443 == 1'd1)));
end

always @ (*) begin
    ap_condition_404 = (((tmp_2_i_reg_450 == 1'd0) & (tmp_i_reg_443 == 1'd1)) | ((valid_load_reg_439 == 1'd1) & (tmp_2_i_reg_450 == 1'd0)));
end

always @ (*) begin
    ap_condition_766 = ((1'b1 == ap_CS_iter0_fsm_state5) & (((ret_fu_356_p3 == 1'd1) & (valid_load_reg_439 == 1'd1) & (tmp_2_i_reg_450 == 1'd1)) | ((ret_fu_356_p3 == 1'd1) & (tmp_2_i_reg_450 == 1'd1) & (tmp_i_reg_443 == 1'd1))));
end

always @ (*) begin
    ap_condition_769 = ((1'b1 == ap_CS_iter1_fsm_state6) & (((ret_reg_520_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (valid_load_reg_439_pp0_iter0_reg == 1'd1)) | ((ret_reg_520_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_450_pp0_iter0_reg == 1'd1) & (tmp_i_reg_443_pp0_iter0_reg == 1'd1))));
end

assign ap_phi_reg_pp0_iter0_sumq_new_0_i_reg_197 = 'bx;

assign ap_phi_reg_pp0_iter0_valid_flag_1_i_reg_142 = 'bx;

assign ap_phi_reg_pp0_iter0_valid_flag_2_i_reg_166 = 1'd0;

assign ap_phi_reg_pp0_iter0_valid_new_1_i_reg_154 = 'bx;

assign ap_phi_reg_pp0_iter0_valid_new_2_i_reg_181 = 'bx;

always @ (*) begin
    ap_predicate_op128_write_state21 = (((valid_load_reg_439_pp0_iter3_reg == 1'd1) & (tmp_2_i_reg_450_pp0_iter3_reg == 1'd1)) | ((tmp_2_i_reg_450_pp0_iter3_reg == 1'd1) & (tmp_i_reg_443_pp0_iter3_reg == 1'd1)));
end

always @ (*) begin
    ap_predicate_op131_write_state21 = (((ret_reg_520_pp0_iter3_reg == 1'd1) & (valid_load_reg_439_pp0_iter3_reg == 1'd1) & (tmp_2_i_reg_450_pp0_iter3_reg == 1'd1)) | ((ret_reg_520_pp0_iter3_reg == 1'd1) & (tmp_2_i_reg_450_pp0_iter3_reg == 1'd1) & (tmp_i_reg_443_pp0_iter3_reg == 1'd1)));
end

always @ (*) begin
    ap_predicate_op55_read_state1 = (((ap_sig_allocacmp_valid_load == 1'd1) & (tmp_2_i_nbreadreq_fu_100_p3 == 1'd1)) | ((tmp_2_i_nbreadreq_fu_100_p3 == 1'd1) & (tmp_i_nbreadreq_fu_86_p3 == 1'd1)));
end

assign bitcast_ln103_1_fu_412_p1 = xm_1_reg_499_pp0_iter3_reg;

assign bitcast_ln103_2_fu_415_p1 = xm_2_reg_506_pp0_iter3_reg;

assign bitcast_ln103_3_fu_418_p1 = xm_3_reg_513_pp0_iter3_reg;

assign bitcast_ln103_fu_409_p1 = xm_reg_492_pp0_iter3_reg;

assign bitcast_ln87_fu_280_p1 = mean_s_dout;

assign bitcast_ln92_1_fu_309_p1 = tmp_3_i6_fu_299_p4;

assign bitcast_ln92_2_fu_324_p1 = tmp_4_i7_fu_314_p4;

assign bitcast_ln92_3_fu_339_p1 = tmp_5_i8_fu_329_p4;

assign bitcast_ln92_fu_294_p1 = trunc_ln92_fu_290_p1;

assign mean_s_read_nbread_fu_94_p2_0 = mean_s_empty_n;

assign p_vld_fu_272_p1 = mean_s_read_nbread_fu_94_p2_0;

assign ret_fu_356_p3 = count[32'd7];

assign ret_reg_520_pp0_iter0_reg = ret_reg_520;

assign select_ln72_fu_372_p3 = ((tmp_fu_364_p3[0:0] == 1'b1) ? 8'd95 : 8'd255);

assign stage2_s_din = {{{{bitcast_ln103_3_fu_418_p1}, {bitcast_ln103_2_fu_415_p1}}, {bitcast_ln103_1_fu_412_p1}}, {bitcast_ln103_fu_409_p1}};

assign tmp_2_i_nbreadreq_fu_100_p3 = stage1_s_empty_n;

assign tmp_3_i6_fu_299_p4 = {{stage1_s_dout[63:32]}};

assign tmp_4_i7_fu_314_p4 = {{stage1_s_dout[95:64]}};

assign tmp_5_i8_fu_329_p4 = {{stage1_s_dout[127:96]}};

assign tmp_fu_364_p3 = count[32'd7];

assign tmp_i_nbreadreq_fu_86_p3 = mean_s_empty_n;

assign trunc_ln92_fu_290_p1 = stage1_s_dout[31:0];

assign valid_load_load_fu_268_p1 = ap_sig_allocacmp_valid_load;

assign var_s_din = grp_fu_245_p2;

endmodule //layernorm_top_var_stage_384ul_float_float_float_4ul_s
